const escapeHtml = (input) => String(input || '')
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/\"/g, '&quot;')
  .replace(/'/g, '&#39;');

const renderProjectCard = (project) => {
  const stack = Array.isArray(project.stack) ? project.stack : [];
  const stackHtml = stack.map((item) => `<span class=\"chip\">${escapeHtml(item)}</span>`).join('');

  return `
    <article class=\"project\">
      <h3>${escapeHtml(project.name)}</h3>
      <p>${escapeHtml(project.description || '')}</p>
      <div class=\"stack\">${stackHtml}</div>
      <div class=\"links\">
        ${project.repoUrl ? `<a href=\"${escapeHtml(project.repoUrl)}\" target=\"_blank\" rel=\"noreferrer\">Repository</a>` : ''}
        ${project.liveUrl ? `<a href=\"${escapeHtml(project.liveUrl)}\" target=\"_blank\" rel=\"noreferrer\">Live Demo</a>` : ''}
      </div>
    </article>
  `;
};

export const renderPortfolioHtml = ({ profile, template = 'minimal', theme = {} }) => {
  const featuredProjects = (Array.isArray(profile?.projects) ? profile.projects : []).filter((project) => project.featured);

  const primaryColor = theme.primaryColor || '#0c4a6e';
  const accentColor = theme.accentColor || '#0284c7';
  const fontFamily = theme.fontFamily || "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif";

  return `<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>${escapeHtml(profile?.basicInfo?.fullName || 'Portfolio')} - Portfolio</title>
  <meta name=\"description\" content=${JSON.stringify(profile?.basicInfo?.summary || 'Professional portfolio generated by Preploop')} />
  <style>
    :root { --primary: ${primaryColor}; --accent: ${accentColor}; }
    * { box-sizing: border-box; }
    body { margin: 0; font-family: ${fontFamily}; color: #0f172a; background: linear-gradient(180deg, #f8fafc 0%, #e2e8f0 100%); }
    .container { max-width: 980px; margin: 0 auto; padding: 24px; }
    .hero { background: var(--primary); color: white; padding: 28px; border-radius: 16px; box-shadow: 0 12px 30px rgba(15, 23, 42, 0.14); }
    .headline { margin-top: 6px; opacity: 0.95; }
    .section { margin-top: 24px; background: white; border-radius: 14px; padding: 20px; box-shadow: 0 8px 18px rgba(15, 23, 42, 0.08); }
    .chips { display: flex; gap: 8px; flex-wrap: wrap; }
    .chip { background: #e0f2fe; color: #075985; border-radius: 999px; padding: 4px 10px; font-size: 12px; font-weight: 600; }
    .timeline-item { padding-bottom: 12px; margin-bottom: 12px; border-bottom: 1px solid #e2e8f0; }
    .timeline-item:last-child { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }
    .project { border: 1px solid #e2e8f0; border-radius: 12px; padding: 14px; margin-bottom: 12px; }
    .project:last-child { margin-bottom: 0; }
    .stack { display: flex; flex-wrap: wrap; gap: 8px; margin: 10px 0; }
    .links a { color: var(--accent); margin-right: 14px; font-weight: 600; text-decoration: none; }
    .links a:hover { text-decoration: underline; }
    .footer { text-align: center; margin: 24px 0 12px; color: #475569; font-size: 13px; }
    @media (max-width: 680px) {
      .container { padding: 14px; }
      .hero { padding: 20px; border-radius: 12px; }
      .section { padding: 16px; border-radius: 12px; }
    }
  </style>
</head>
<body data-template=\"${escapeHtml(template)}\">
  <main class=\"container\">
    <header class=\"hero\">
      <h1>${escapeHtml(profile?.basicInfo?.fullName || 'Portfolio')}</h1>
      <p class=\"headline\">${escapeHtml(profile?.basicInfo?.headline || '')}</p>
      <p>${escapeHtml(profile?.basicInfo?.summary || '')}</p>
    </header>

    <section class=\"section\">
      <h2>Skills</h2>
      <div class=\"chips\">
        ${(profile?.skills?.languages || []).map((skill) => `<span class=\"chip\">${escapeHtml(skill)}</span>`).join('')}
        ${(profile?.skills?.frameworks || []).map((skill) => `<span class=\"chip\">${escapeHtml(skill)}</span>`).join('')}
      </div>
    </section>

    <section class=\"section\">
      <h2>Experience</h2>
      ${(profile?.experience || []).map((item) => `
        <div class=\"timeline-item\">
          <h3>${escapeHtml(item.role)} · ${escapeHtml(item.company)}</h3>
          <p>${escapeHtml(item.startDate || '')}${item.endDate ? ` - ${escapeHtml(item.endDate)}` : ''}</p>
        </div>
      `).join('')}
    </section>

    <section class=\"section\">
      <h2>Featured Projects</h2>
      ${featuredProjects.map(renderProjectCard).join('')}
    </section>

    <section class=\"section\">
      <h2>Contact</h2>
      <p>${escapeHtml(profile?.basicInfo?.email || '')}</p>
      <p>${escapeHtml(profile?.socials?.linkedin || '')}</p>
      <p>${escapeHtml(profile?.socials?.github || '')}</p>
    </section>

    <footer class=\"footer\">Generated by Preploop Portfolio Generator</footer>
  </main>
</body>
</html>`;
};

export default {
  renderPortfolioHtml,
};
