import { supabaseAdmin } from '../db/supabaseClient.js';

const solutions = {
    303: { python: `def change(amount, coins):\n    dp = [0] * (amount + 1)\n    dp[0] = 1\n    for c in coins:\n        for i in range(c, amount + 1):\n            dp[i] += dp[i - c]\n    return dp[amount]` },
    304: { javascript: `function combinationSum4(nums, target) {\n    const dp = new Array(target+1).fill(0);\n    dp[0] = 1;\n    for (let i = 1; i <= target; i++) {\n        for (const n of nums) if (i >= n) dp[i] += dp[i-n];\n    }\n    return dp[target];\n}` },
    318: { javascript: `function minDistance(word1, word2) {\n    const m = word1.length, n = word2.length;\n    const dp = Array.from({length:m+1}, ()=>new Array(n+1).fill(0));\n    for (let i=0;i<=m;i++) dp[i][0]=i;\n    for (let j=0;j<=n;j++) dp[0][j]=j;\n    for (let i=1;i<=m;i++) for (let j=1;j<=n;j++) {\n        if (word1[i-1]===word2[j-1]) dp[i][j]=dp[i-1][j-1];\n        else dp[i][j]=1+Math.min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1]);\n    }\n    return dp[m][n];\n}` },
    320: { python: `def isInterleave(s1, s2, s3):\n    if len(s1)+len(s2)!=len(s3): return False\n    dp = [[False]*(len(s2)+1) for _ in range(len(s1)+1)]\n    dp[0][0] = True\n    for i in range(len(s1)+1):\n        for j in range(len(s2)+1):\n            if i>0 and s1[i-1]==s3[i+j-1]: dp[i][j] = dp[i][j] or dp[i-1][j]\n            if j>0 and s2[j-1]==s3[i+j-1]: dp[i][j] = dp[i][j] or dp[i][j-1]\n    return dp[len(s1)][len(s2)]` },
    334: { python: `def canPartition(nums):\n    total = sum(nums)\n    if total % 2: return False\n    target = total // 2\n    dp = {0}\n    for n in nums:\n        dp = dp | {n + x for x in dp}\n        if target in dp: return True\n    return False` },
    335: { python: `def findTargetSumWays(nums, target):\n    from collections import defaultdict\n    dp = defaultdict(int)\n    dp[0] = 1\n    for n in nums:\n        new_dp = defaultdict(int)\n        for s, c in dp.items():\n            new_dp[s + n] += c\n            new_dp[s - n] += c\n        dp = new_dp\n    return dp[target]` },
    337: { javascript: `function lastStoneWeightII(stones) {\n    let total = stones.reduce((a,b)=>a+b,0);\n    let dp = new Set([0]);\n    for (const s of stones) {\n        const next = new Set();\n        for (const v of dp) { next.add(v+s); next.add(v); }\n        dp = next;\n    }\n    let res = Infinity;\n    for (const v of dp) res = Math.min(res, Math.abs(total - 2*v));\n    return res;\n}` },
    345: { python: `def maxCoins(nums):\n    nums = [1] + nums + [1]\n    n = len(nums)\n    dp = [[0]*n for _ in range(n)]\n    for length in range(2, n):\n        for l in range(0, n - length):\n            r = l + length\n            for k in range(l+1, r):\n                dp[l][r] = max(dp[l][r], dp[l][k] + dp[k][r] + nums[l]*nums[k]*nums[r])\n    return dp[0][n-1]` },
    348: { javascript: `function subsetsWithDup(nums) {\n    nums.sort((a,b)=>a-b);\n    const result = [];\n    const bt = (start, path) => {\n        result.push([...path]);\n        for (let i = start; i < nums.length; i++) {\n            if (i > start && nums[i] === nums[i-1]) continue;\n            path.push(nums[i]);\n            bt(i+1, path);\n            path.pop();\n        }\n    };\n    bt(0, []);\n    return result;\n}` },
    354: { javascript: `function combine(n, k) {\n    const result = [];\n    const bt = (start, path) => {\n        if (path.length === k) { result.push([...path]); return; }\n        for (let i = start; i <= n; i++) { path.push(i); bt(i+1, path); path.pop(); }\n    };\n    bt(1, []);\n    return result;\n}` },
    356: { python: `def generateParenthesis(n):\n    result = []\n    def bt(s, open, close):\n        if len(s) == 2 * n:\n            result.append(s)\n            return\n        if open < n: bt(s + '(', open + 1, close)\n        if close < open: bt(s + ')', open, close + 1)\n    bt('', 0, 0)\n    return result`, javascript: `function generateParenthesis(n) {\n    const result = [];\n    const bt = (s, open, close) => {\n        if (s.length === 2*n) { result.push(s); return; }\n        if (open < n) bt(s+'(', open+1, close);\n        if (close < open) bt(s+')', open, close+1);\n    };\n    bt('', 0, 0);\n    return result;\n}` },
    363: { python: `def solveSudoku(board):\n    def isValid(r, c, ch):\n        for i in range(9):\n            if board[r][i] == ch or board[i][c] == ch: return False\n            if board[3*(r//3)+i//3][3*(c//3)+i%3] == ch: return False\n        return True\n    def solve():\n        for i in range(9):\n            for j in range(9):\n                if board[i][j] == '.':\n                    for ch in '123456789':\n                        if isValid(i, j, ch):\n                            board[i][j] = ch\n                            if solve(): return True\n                            board[i][j] = '.'\n                    return False\n        return True\n    solve()` },
    364: { python: `def isValidSudoku(board):\n    rows = [set() for _ in range(9)]\n    cols = [set() for _ in range(9)]\n    boxes = [set() for _ in range(9)]\n    for i in range(9):\n        for j in range(9):\n            if board[i][j] != '.':\n                num = board[i][j]\n                box = (i//3)*3 + j//3\n                if num in rows[i] or num in cols[j] or num in boxes[box]:\n                    return False\n                rows[i].add(num)\n                cols[j].add(num)\n                boxes[box].add(num)\n    return True` },
    365: { python: `def letterCasePermutation(s):\n    result = []\n    def bt(i, path):\n        if i == len(s):\n            result.append(path)\n            return\n        if s[i].isalpha():\n            bt(i+1, path + s[i].lower())\n            bt(i+1, path + s[i].upper())\n        else:\n            bt(i+1, path + s[i])\n    bt(0, '')\n    return result`, javascript: `function letterCasePermutation(s) {\n    const result = [];\n    const bt = (i, path) => {\n        if (i === s.length) { result.push(path); return; }\n        if (/[a-zA-Z]/.test(s[i])) {\n            bt(i+1, path + s[i].toLowerCase());\n            bt(i+1, path + s[i].toUpperCase());\n        } else bt(i+1, path + s[i]);\n    };\n    bt(0, '');\n    return result;\n}` },
    366: { python: `def countArrangement(n):\n    count = 0\n    visited = [False] * (n + 1)\n    def bt(pos):\n        nonlocal count\n        if pos > n:\n            count += 1\n            return\n        for i in range(1, n + 1):\n            if not visited[i] and (i % pos == 0 or pos % i == 0):\n                visited[i] = True\n                bt(pos + 1)\n                visited[i] = False\n    bt(1)\n    return count` },
    367: { python: `def makesquare(matchsticks):\n    total = sum(matchsticks)\n    if total % 4: return False\n    side = total // 4\n    matchsticks.sort(reverse=True)\n    sides = [0] * 4\n    def bt(i):\n        if i == len(matchsticks): return all(s == side for s in sides)\n        for j in range(4):\n            if sides[j] + matchsticks[i] <= side:\n                sides[j] += matchsticks[i]\n                if bt(i + 1): return True\n                sides[j] -= matchsticks[i]\n            if sides[j] == 0: break\n        return False\n    return bt(0)` },
    369: { python: `def isAdditiveNumber(num):\n    n = len(num)\n    def bt(i, prev1, prev2):\n        if i == n: return True\n        for j in range(i+1, n+1):\n            if num[i] == '0' and j > i+1: break\n            curr = int(num[i:j])\n            if prev1 is not None and prev2 is not None:\n                if curr < prev1 + prev2: continue\n                if curr > prev1 + prev2: break\n            if prev1 is None or prev2 is None or curr == prev1 + prev2:\n                if bt(j, prev2 if prev2 is not None else curr, curr if prev2 is not None else None):\n                    return True\n        return False\n    for i in range(1, n):\n        for j in range(i+1, n):\n            if num[0] == '0' and i > 1: break\n            if num[i] == '0' and j > i+1: break\n            n1, n2 = int(num[:i]), int(num[i:j])\n            rest = num[j:]\n            if check(n1, n2, rest): return True\n    return False\ndef check(n1, n2, rest):\n    if not rest: return True\n    s = str(n1 + n2)\n    if not rest.startswith(s): return False\n    return check(n2, n1+n2, rest[len(s):])` },
    375: { python: `def findStrobogrammatic(n):\n    def build(n, is_outer):\n        if n == 0: return ['']\n        if n == 1: return ['0', '1', '8']\n        middles = build(n - 2, False)\n        result = []\n        for m in middles:\n            for pair in [('0','0'),('1','1'),('6','9'),('8','8'),('9','6')]:\n                if pair[0] != '0' or not is_outer:\n                    result.append(pair[0] + m + pair[1])\n        return result\n    return build(n, True)`, javascript: `function findStrobogrammatic(n) {\n    const build = (n, outer) => {\n        if (n===0) return [''];\n        if (n===1) return ['0','1','8'];\n        const mids = build(n-2, false);\n        const res = [];\n        for (const m of mids) {\n            for (const [a,b] of [['0','0'],['1','1'],['6','9'],['8','8'],['9','6']]) {\n                if (a!=='0'||!outer) res.push(a+m+b);\n            }\n        }\n        return res;\n    };\n    return build(n, true);\n}` },
    386: { javascript: `function leastInterval(tasks, n) {\n    const freq = new Array(26).fill(0);\n    for (const t of tasks) freq[t.charCodeAt(0)-65]++;\n    freq.sort((a,b)=>b-a);\n    const maxF = freq[0] - 1;\n    let idle = maxF * n;\n    for (let i = 1; i < 26 && freq[i] > 0; i++) idle -= Math.min(maxF, freq[i]);\n    return Math.max(tasks.length, tasks.length + idle);\n}` },
    394: { python: `def mostBooked(n, meetings):\n    import heapq\n    meetings.sort()\n    avail = list(range(n))\n    heapq.heapify(avail)\n    busy = []\n    count = [0] * n\n    for start, end in meetings:\n        while busy and busy[0][0] <= start:\n            _, room = heapq.heappop(busy)\n            heapq.heappush(avail, room)\n        if avail:\n            room = heapq.heappop(avail)\n            heapq.heappush(busy, (end, room))\n            count[room] += 1\n        else:\n            end_time, room = heapq.heappop(busy)\n            heapq.heappush(busy, (end_time + end - start, room))\n            count[room] += 1\n    return count.index(max(count))` },
    397: { python: `class Trie:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n    def insert(self, word):\n        node = self\n        for c in word:\n            if c not in node.children: node.children[c] = Trie()\n            node = node.children[c]\n        node.is_end = True\n    def search(self, word):\n        node = self._find(word)\n        return node is not None and node.is_end\n    def startsWith(self, prefix):\n        return self._find(prefix) is not None\n    def _find(self, word):\n        node = self\n        for c in word:\n            if c not in node.children: return None\n            node = node.children[c]\n        return node` },
    398: { python: `class WordDictionary:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n    def addWord(self, word):\n        node = self\n        for c in word:\n            if c not in node.children: node.children[c] = WordDictionary()\n            node = node.children[c]\n        node.is_end = True\n    def search(self, word):\n        def dfs(node, i):\n            if i == len(word): return node.is_end\n            if word[i] == '.':\n                return any(dfs(child, i+1) for child in node.children.values())\n            if word[i] not in node.children: return False\n            return dfs(node.children[word[i]], i+1)\n        return dfs(self, 0)` },
    400: { python: `def replaceWords(dictionary, sentence):\n    trie = {}\n    for root in dictionary:\n        node = trie\n        for c in root:\n            if c not in node: node[c] = {}\n            node = node[c]\n        node['#'] = True\n    def replace(word):\n        node = trie\n        for i, c in enumerate(word):\n            if '#' in node: return word[:i]\n            if c not in node: return word\n            node = node[c]\n        return word\n    return ' '.join(replace(w) for w in sentence.split())` },
    401: { python: `class MagicDictionary:\n    def __init__(self):\n        self.words = set()\n    def buildDict(self, dictionary):\n        self.words = set(dictionary)\n    def search(self, searchWord):\n        for w in self.words:\n            if len(w) != len(searchWord): continue\n            diff = sum(1 for a, b in zip(w, searchWord) if a != b)\n            if diff == 1: return True\n        return False` },
    404: { python: `class AutocompleteSystem:\n    def __init__(self, sentences, times):\n        self.freq = {}\n        for s, t in zip(sentences, times): self.freq[s] = t\n        self.prefix = ''\n    def input(self, c):\n        if c == '#':\n            self.freq[self.prefix] = self.freq.get(self.prefix, 0) + 1\n            self.prefix = ''\n            return []\n        self.prefix += c\n        matches = [(s, t) for s, t in self.freq.items() if s.startswith(self.prefix)]\n        matches.sort(key=lambda x: (-x[1], x[0]))\n        return [s for s, t in matches[:3]]` },
    405: { python: `class StreamChecker:\n    def __init__(self, words):\n        self.trie = {}\n        for w in words:\n            node = self.trie\n            for c in reversed(w):\n                if c not in node: node[c] = {}\n                node = node[c]\n            node['#'] = True\n        self.stream = []\n    def query(self, letter):\n        self.stream.append(letter)\n        node = self.trie\n        for c in reversed(self.stream):\n            if '#' in node: return True\n            if c not in node: return False\n            node = node[c]\n        return '#' in node` },
    406: { python: `def findAllConcatenatedWordsInADict(words):\n    word_set = set(words)\n    def canForm(word):\n        dp = [False] * (len(word) + 1)\n        dp[0] = True\n        for i in range(1, len(word) + 1):\n            for j in range(i):\n                if dp[j] and word[j:i] in word_set and word[j:i] != word:\n                    dp[i] = True\n                    break\n        return dp[len(word)]\n    return [w for w in words if w and canForm(w)]` },
    408: { python: `def findMaximumXOR(nums):\n    max_xor = 0\n    mask = 0\n    for i in range(31, -1, -1):\n        mask |= (1 << i)\n        prefixes = {n & mask for n in nums}\n        candidate = max_xor | (1 << i)\n        if any(candidate ^ p in prefixes for p in prefixes):\n            max_xor = candidate\n    return max_xor` },
    410: { python: `class MapSum:\n    def __init__(self):\n        self.map = {}\n        self.trie = {}\n    def insert(self, key, val):\n        delta = val - self.map.get(key, 0)\n        self.map[key] = val\n        node = self.trie\n        for c in key:\n            if c not in node: node[c] = {'_sum': 0}\n            node = node[c]\n            node['_sum'] += delta\n    def sum(self, prefix):\n        node = self.trie\n        for c in prefix:\n            if c not in node: return 0\n            node = node[c]\n        return node.get('_sum', 0)` },
    414: { python: `def canCompleteCircuit(gas, cost):\n    if sum(gas) < sum(cost): return -1\n    start = tank = 0\n    for i in range(len(gas)):\n        tank += gas[i] - cost[i]\n        if tank < 0:\n            start = i + 1\n            tank = 0\n    return start`, javascript: `function canCompleteCircuit(gas, cost) {\n    if (gas.reduce((a,b)=>a+b) < cost.reduce((a,b)=>a+b)) return -1;\n    let start = 0, tank = 0;\n    for (let i = 0; i < gas.length; i++) {\n        tank += gas[i] - cost[i];\n        if (tank < 0) { start = i+1; tank = 0; }\n    }\n    return start;\n}` },
    423: { python: `def maximumSwap(num):\n    digits = list(str(num))\n    last = {int(d): i for i, d in enumerate(digits)}\n    for i, d in enumerate(digits):\n        for k in range(9, int(d), -1):\n            if last.get(k, -1) > i:\n                digits[i], digits[last[k]] = digits[last[k]], digits[i]\n                return int(''.join(digits))\n    return num` },
    426: { python: `def minSetSize(arr):\n    from collections import Counter\n    counts = sorted(Counter(arr).values(), reverse=True)\n    total, removed = len(arr), 0\n    for i, c in enumerate(counts):\n        removed += c\n        if removed >= total // 2:\n            return i + 1\n    return len(counts)` },
};

async function run() {
    console.log('Fixing remaining solutions - Batch 3...\n');
    let updated = 0, failed = 0;
    for (const [id, langSolutions] of Object.entries(solutions)) {
        const { data: problem } = await supabaseAdmin.from('problems').select('solution_code').eq('id', parseInt(id)).single();
        if (!problem) { console.log(`  Problem #${id} not found`); continue; }
        const merged = { ...(problem.solution_code || {}), ...langSolutions };
        const { error } = await supabaseAdmin.from('problems').update({ solution_code: merged }).eq('id', parseInt(id));
        if (error) { console.error(`  #${id}: ${error.message}`); failed++; }
        else { console.log(`  #${id} done`); updated++; }
    }
    console.log(`\nDone: ${updated} updated, ${failed} failed`);
}
run();
