import { supabaseAdmin } from '../db/supabaseClient.js';

const solutions = {
    142: { javascript: `class MyLinkedList {\n    constructor() { this.head = null; this.size = 0; }\n    get(index) { if(index<0||index>=this.size) return -1; let c=this.head; for(let i=0;i<index;i++) c=c.next; return c.val; }\n    addAtHead(val) { this.head={val,next:this.head}; this.size++; }\n    addAtTail(val) { const n={val,next:null}; if(!this.head){this.head=n;}else{let c=this.head;while(c.next)c=c.next;c.next=n;} this.size++; }\n    addAtIndex(i,val) { if(i>this.size)return; if(i<=0){this.addAtHead(val);return;} let c=this.head;for(let j=0;j<i-1;j++)c=c.next; c.next={val,next:c.next}; this.size++; }\n    deleteAtIndex(i) { if(i<0||i>=this.size)return; if(i===0){this.head=this.head.next;}else{let c=this.head;for(let j=0;j<i-1;j++)c=c.next;c.next=c.next.next;} this.size--; }\n}` },
    150: { javascript: `class LRUCache {\n    constructor(capacity) { this.cap = capacity; this.cache = new Map(); }\n    get(key) { if(!this.cache.has(key)) return -1; const v=this.cache.get(key); this.cache.delete(key); this.cache.set(key,v); return v; }\n    put(key, value) { if(this.cache.has(key)) this.cache.delete(key); this.cache.set(key,value); if(this.cache.size>this.cap) this.cache.delete(this.cache.keys().next().value); }\n}` },
    170: { javascript: `function removeKdigits(num, k) {\n    const stack = [];\n    for (const d of num) {\n        while (k > 0 && stack.length && stack[stack.length-1] > d) { stack.pop(); k--; }\n        stack.push(d);\n    }\n    while (k > 0) { stack.pop(); k--; }\n    const res = stack.join('').replace(/^0+/, '');\n    return res || '0';\n}` },
    173: { python: `def countOfAtoms(formula):\n    import re\n    from collections import Counter\n    stack = [Counter()]\n    i, n = 0, len(formula)\n    while i < n:\n        if formula[i] == '(':\n            stack.append(Counter())\n            i += 1\n        elif formula[i] == ')':\n            i += 1\n            j = i\n            while i < n and formula[i].isdigit(): i += 1\n            mult = int(formula[j:i] or 1)\n            top = stack.pop()\n            for k, v in top.items(): stack[-1][k] += v * mult\n        else:\n            j = i; i += 1\n            while i < n and formula[i].islower(): i += 1\n            name = formula[j:i]\n            j = i\n            while i < n and formula[i].isdigit(): i += 1\n            stack[-1][name] += int(formula[j:i] or 1)\n    return ''.join(k + (str(v) if v > 1 else '') for k, v in sorted(stack[-1].items()))`, javascript: `function countOfAtoms(formula) {\n    const stack = [{}];\n    let i = 0;\n    while (i < formula.length) {\n        if (formula[i] === '(') { stack.push({}); i++; }\n        else if (formula[i] === ')') {\n            i++; let j = i;\n            while (i < formula.length && /\\d/.test(formula[i])) i++;\n            const mult = parseInt(formula.slice(j, i)) || 1;\n            const top = stack.pop();\n            for (const [k, v] of Object.entries(top)) stack[stack.length-1][k] = (stack[stack.length-1][k]||0) + v*mult;\n        } else {\n            let j = i; i++;\n            while (i < formula.length && /[a-z]/.test(formula[i])) i++;\n            const name = formula.slice(j, i); j = i;\n            while (i < formula.length && /\\d/.test(formula[i])) i++;\n            stack[stack.length-1][name] = (stack[stack.length-1][name]||0) + (parseInt(formula.slice(j, i)) || 1);\n        }\n    }\n    return Object.entries(stack[0]).sort().map(([k,v]) => k + (v>1?v:'')).join('');\n}` },
    177: { javascript: `function nextGreaterElements(nums) {\n    const n = nums.length, res = new Array(n).fill(-1), stack = [];\n    for (let i = 0; i < 2*n; i++) {\n        while (stack.length && nums[stack[stack.length-1]] < nums[i%n]) res[stack.pop()] = nums[i%n];\n        if (i < n) stack.push(i);\n    }\n    return res;\n}` },
    189: { python: `def firstBadVersion(n):\n    lo, hi = 1, n\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if isBadVersion(mid): hi = mid\n        else: lo = mid + 1\n    return lo` },
    190: { javascript: `function mySqrt(x) {\n    if (x < 2) return x;\n    let lo = 1, hi = Math.floor(x / 2);\n    while (lo <= hi) {\n        const mid = Math.floor((lo + hi) / 2);\n        if (mid * mid === x) return mid;\n        else if (mid * mid < x) lo = mid + 1;\n        else hi = mid - 1;\n    }\n    return hi;\n}` },
    192: { python: `def guessNumber(n):\n    lo, hi = 1, n\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        result = guess(mid)\n        if result == 0: return mid\n        elif result == -1: hi = mid - 1\n        else: lo = mid + 1\n    return lo` },
    200: { javascript: `function singleNonDuplicate(nums) {\n    let lo = 0, hi = nums.length - 1;\n    while (lo < hi) {\n        let mid = Math.floor((lo + hi) / 2);\n        if (mid % 2 === 1) mid--;\n        if (nums[mid] === nums[mid + 1]) lo = mid + 2;\n        else hi = mid;\n    }\n    return nums[lo];\n}` },
    209: { python: `def minDays(bloomDay, m, k):\n    if m * k > len(bloomDay): return -1\n    def canMake(days):\n        bouquets = flowers = 0\n        for b in bloomDay:\n            if b <= days: flowers += 1\n            else: flowers = 0\n            if flowers == k:\n                bouquets += 1\n                flowers = 0\n        return bouquets >= m\n    lo, hi = min(bloomDay), max(bloomDay)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if canMake(mid): hi = mid\n        else: lo = mid + 1\n    return lo` },
    210: { python: `def maxDistance(position, m):\n    position.sort()\n    def canPlace(dist):\n        count, last = 1, position[0]\n        for p in position[1:]:\n            if p - last >= dist:\n                count += 1\n                last = p\n        return count >= m\n    lo, hi = 1, position[-1] - position[0]\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if canPlace(mid): lo = mid + 1\n        else: hi = mid - 1\n    return hi`, javascript: `function maxDistance(position, m) {\n    position.sort((a,b)=>a-b);\n    const canPlace = (dist) => {\n        let count = 1, last = position[0];\n        for (let i = 1; i < position.length; i++) {\n            if (position[i] - last >= dist) { count++; last = position[i]; }\n        }\n        return count >= m;\n    };\n    let lo = 1, hi = position[position.length-1] - position[0];\n    while (lo <= hi) {\n        const mid = Math.floor((lo+hi)/2);\n        if (canPlace(mid)) lo = mid+1; else hi = mid-1;\n    }\n    return hi;\n}` },
    221: { javascript: `function divide(dividend, divisor) {\n    const MAX = 2**31-1, MIN = -(2**31);\n    if (dividend === MIN && divisor === -1) return MAX;\n    const sign = (dividend > 0) ^ (divisor > 0) ? -1 : 1;\n    let a = Math.abs(dividend), b = Math.abs(divisor), res = 0;\n    while (a >= b) {\n        let temp = b, mult = 1;\n        while (a >= temp * 2) { temp *= 2; mult *= 2; }\n        a -= temp; res += mult;\n    }\n    return sign * res;\n}` },
    223: { javascript: `function minDepth(root) {\n    if (!root) return 0;\n    if (!root.left) return 1 + minDepth(root.right);\n    if (!root.right) return 1 + minDepth(root.left);\n    return 1 + Math.min(minDepth(root.left), minDepth(root.right));\n}` },
    226: { javascript: `function isBalanced(root) {\n    const height = (node) => {\n        if (!node) return 0;\n        const l = height(node.left), r = height(node.right);\n        if (l === -1 || r === -1 || Math.abs(l-r) > 1) return -1;\n        return 1 + Math.max(l, r);\n    };\n    return height(root) !== -1;\n}` },
    228: { javascript: `function isSymmetric(root) {\n    const check = (l, r) => {\n        if (!l && !r) return true;\n        if (!l || !r) return false;\n        return l.val === r.val && check(l.left, r.right) && check(l.right, r.left);\n    };\n    return check(root?.left, root?.right);\n}` },
    231: { python: `def binaryTreePaths(root):\n    if not root: return []\n    result = []\n    def dfs(node, path):\n        if not node.left and not node.right:\n            result.append(path)\n            return\n        if node.left: dfs(node.left, path + '->' + str(node.left.val))\n        if node.right: dfs(node.right, path + '->' + str(node.right.val))\n    dfs(root, str(root.val))\n    return result` },
    236: { python: `def sumNumbers(root):\n    def dfs(node, num):\n        if not node: return 0\n        num = num * 10 + node.val\n        if not node.left and not node.right: return num\n        return dfs(node.left, num) + dfs(node.right, num)\n    return dfs(root, 0)` },
    237: { python: `def lowestCommonAncestor(root, p, q):\n    while root:\n        if p.val < root.val and q.val < root.val: root = root.left\n        elif p.val > root.val and q.val > root.val: root = root.right\n        else: return root`, javascript: `function lowestCommonAncestor(root, p, q) {\n    while (root) {\n        if (p.val < root.val && q.val < root.val) root = root.left;\n        else if (p.val > root.val && q.val > root.val) root = root.right;\n        else return root;\n    }\n}` },
    238: { python: `def lowestCommonAncestor(root, p, q):\n    if not root or root == p or root == q: return root\n    left = lowestCommonAncestor(root.left, p, q)\n    right = lowestCommonAncestor(root.right, p, q)\n    if left and right: return root\n    return left if left else right` },
    240: { python: `def zigzagLevelOrder(root):\n    if not root: return []\n    from collections import deque\n    result, q = [], deque([root])\n    left_to_right = True\n    while q:\n        level = []\n        for _ in range(len(q)):\n            node = q.popleft()\n            level.append(node.val)\n            if node.left: q.append(node.left)\n            if node.right: q.append(node.right)\n        result.append(level if left_to_right else level[::-1])\n        left_to_right = not left_to_right\n    return result` },
    241: { python: `def rightSideView(root):\n    if not root: return []\n    from collections import deque\n    result, q = [], deque([root])\n    while q:\n        for i in range(len(q)):\n            node = q.popleft()\n            if i == 0: result.append(node.val)\n            if node.right: q.append(node.right)\n            if node.left: q.append(node.left)\n        \n    return result` },
    242: { python: `def levelOrderBottom(root):\n    if not root: return []\n    from collections import deque\n    result, q = [], deque([root])\n    while q:\n        level = []\n        for _ in range(len(q)):\n            node = q.popleft()\n            level.append(node.val)\n            if node.left: q.append(node.left)\n            if node.right: q.append(node.right)\n        result.append(level)\n    return result[::-1]` },
    243: { python: `def averageOfLevels(root):\n    if not root: return []\n    from collections import deque\n    result, q = [], deque([root])\n    while q:\n        level_sum, count = 0, len(q)\n        for _ in range(count):\n            node = q.popleft()\n            level_sum += node.val\n            if node.left: q.append(node.left)\n            if node.right: q.append(node.right)\n        result.append(level_sum / count)\n    return result` },
    245: { javascript: `function connect(root) {\n    if (!root) return root;\n    let level = [root];\n    while (level.length) {\n        const next = [];\n        for (let i = 0; i < level.length; i++) {\n            level[i].next = level[i+1] || null;\n            if (level[i].left) next.push(level[i].left);\n            if (level[i].right) next.push(level[i].right);\n        }\n        level = next;\n    }\n    return root;\n}` },
    246: { javascript: `function connect(root) {\n    if (!root) return root;\n    let level = [root];\n    while (level.length) {\n        const next = [];\n        for (let i = 0; i < level.length; i++) {\n            level[i].next = level[i+1] || null;\n            if (level[i].left) next.push(level[i].left);\n            if (level[i].right) next.push(level[i].right);\n        }\n        level = next;\n    }\n    return root;\n}` },
    248: { javascript: `function kthSmallest(root, k) {\n    const stack = [];\n    let curr = root;\n    while (curr || stack.length) {\n        while (curr) { stack.push(curr); curr = curr.left; }\n        curr = stack.pop();\n        k--;\n        if (k === 0) return curr.val;\n        curr = curr.right;\n    }\n}` },
    249: { javascript: `class BSTIterator {\n    constructor(root) { this.stack = []; this._pushLeft(root); }\n    next() { const n = this.stack.pop(); this._pushLeft(n.right); return n.val; }\n    hasNext() { return this.stack.length > 0; }\n    _pushLeft(n) { while(n) { this.stack.push(n); n = n.left; } }\n}` },
    250: { python: `def sortedArrayToBST(nums):\n    if not nums: return None\n    mid = len(nums) // 2\n    root = TreeNode(nums[mid])\n    root.left = sortedArrayToBST(nums[:mid])\n    root.right = sortedArrayToBST(nums[mid+1:])\n    return root` },
    252: { javascript: `function buildTree(inorder, postorder) {\n    const map = new Map();\n    inorder.forEach((v, i) => map.set(v, i));\n    let pi = postorder.length - 1;\n    const build = (lo, hi) => {\n        if (lo > hi) return null;\n        const val = postorder[pi--];\n        const node = { val, left: null, right: null };\n        const idx = map.get(val);\n        node.right = build(idx + 1, hi);\n        node.left = build(lo, idx - 1);\n        return node;\n    };\n    return build(0, inorder.length - 1);\n}` },
    253: { python: `class Codec:\n    def serialize(self, root):\n        if not root: return 'null'\n        return str(root.val) + ',' + self.serialize(root.left) + ',' + self.serialize(root.right)\n    def deserialize(self, data):\n        vals = iter(data.split(','))\n        def build():\n            v = next(vals)\n            if v == 'null': return None\n            node = TreeNode(int(v))\n            node.left = build()\n            node.right = build()\n            return node\n        return build()` },
    254: { python: `class Codec:\n    def serialize(self, root):\n        if not root: return ''\n        return str(root.val) + ',' + self.serialize(root.left) + ',' + self.serialize(root.right)\n    def deserialize(self, data):\n        if not data: return None\n        vals = iter(data.split(','))\n        def build():\n            v = next(vals, '')\n            if not v: return None\n            node = TreeNode(int(v))\n            node.left = build()\n            node.right = build()\n            return node\n        return build()` },
    255: { javascript: `function countNodes(root) {\n    if (!root) return 0;\n    return 1 + countNodes(root.left) + countNodes(root.right);\n}` },
    256: { javascript: `function goodNodes(root) {\n    let count = 0;\n    const dfs = (node, maxSoFar) => {\n        if (!node) return;\n        if (node.val >= maxSoFar) count++;\n        dfs(node.left, Math.max(maxSoFar, node.val));\n        dfs(node.right, Math.max(maxSoFar, node.val));\n    };\n    dfs(root, -Infinity);\n    return count;\n}` },
    268: { javascript: `function solve(board) {\n    const m = board.length, n = board[0].length;\n    const dfs = (i, j) => {\n        if (i<0||i>=m||j<0||j>=n||board[i][j]!=='O') return;\n        board[i][j] = '#';\n        dfs(i+1,j); dfs(i-1,j); dfs(i,j+1); dfs(i,j-1);\n    };\n    for (let i=0;i<m;i++) { dfs(i,0); dfs(i,n-1); }\n    for (let j=0;j<n;j++) { dfs(0,j); dfs(m-1,j); }\n    for (let i=0;i<m;i++) for (let j=0;j<n;j++) {\n        if (board[i][j]==='O') board[i][j]='X';\n        else if (board[i][j]==='#') board[i][j]='O';\n    }\n}` },
    271: { javascript: `function countComponents(n, edges) {\n    const parent = Array.from({length:n},(_,i)=>i);\n    const find = (x) => { while(parent[x]!==x) { parent[x]=parent[parent[x]]; x=parent[x]; } return x; };\n    let count = n;\n    for (const [a,b] of edges) {\n        const ra = find(a), rb = find(b);\n        if (ra !== rb) { parent[ra] = rb; count--; }\n    }\n    return count;\n}` },
    274: { python: `def accountsMerge(accounts):\n    from collections import defaultdict\n    parent = {}\n    def find(x):\n        if parent[x] != x: parent[x] = find(parent[x])\n        return parent[x]\n    def union(x, y):\n        parent[find(x)] = find(y)\n    email_to_name = {}\n    for acc in accounts:\n        name = acc[0]\n        for email in acc[1:]:\n            if email not in parent: parent[email] = email\n            email_to_name[email] = name\n            union(acc[1], email)\n    groups = defaultdict(list)\n    for email in parent:\n        groups[find(email)].append(email)\n    return [[email_to_name[root]] + sorted(emails) for root, emails in groups.items()]` },
    280: { python: `def alienOrder(words):\n    from collections import defaultdict, deque\n    graph = defaultdict(set)\n    indeg = {c: 0 for w in words for c in w}\n    for i in range(len(words)-1):\n        w1, w2 = words[i], words[i+1]\n        minLen = min(len(w1), len(w2))\n        if len(w1) > len(w2) and w1[:minLen] == w2[:minLen]: return ""\n        for j in range(minLen):\n            if w1[j] != w2[j]:\n                if w2[j] not in graph[w1[j]]:\n                    graph[w1[j]].add(w2[j])\n                    indeg[w2[j]] += 1\n                break\n    q = deque([c for c in indeg if indeg[c] == 0])\n    result = []\n    while q:\n        c = q.popleft()\n        result.append(c)\n        for n in graph[c]:\n            indeg[n] -= 1\n            if indeg[n] == 0: q.append(n)\n    return "".join(result) if len(result) == len(indeg) else ""`, javascript: `function alienOrder(words) {\n    const graph = new Map(), indeg = new Map();\n    for (const w of words) for (const c of w) { graph.set(c, new Set()); indeg.set(c, 0); }\n    for (let i = 0; i < words.length-1; i++) {\n        const [w1,w2] = [words[i],words[i+1]];\n        if (w1.length > w2.length && w1.startsWith(w2)) return "";\n        for (let j = 0; j < Math.min(w1.length,w2.length); j++) {\n            if (w1[j] !== w2[j]) {\n                if (!graph.get(w1[j]).has(w2[j])) { graph.get(w1[j]).add(w2[j]); indeg.set(w2[j], indeg.get(w2[j])+1); }\n                break;\n            }\n        }\n    }\n    const q = []; indeg.forEach((v,k) => { if(v===0) q.push(k); });\n    const res = [];\n    while (q.length) { const c = q.shift(); res.push(c); for (const n of graph.get(c)) { indeg.set(n,indeg.get(n)-1); if(indeg.get(n)===0) q.push(n); } }\n    return res.length === indeg.size ? res.join('') : "";\n}` },
    285: { javascript: `function minimumEffortPath(heights) {\n    const m = heights.length, n = heights[0].length;\n    const dist = Array.from({length:m}, ()=>new Array(n).fill(Infinity));\n    dist[0][0] = 0;\n    const pq = [[0,0,0]];\n    const dirs = [[0,1],[0,-1],[1,0],[-1,0]];\n    while (pq.length) {\n        pq.sort((a,b)=>a[0]-b[0]);\n        const [d,r,c] = pq.shift();\n        if (r===m-1 && c===n-1) return d;\n        if (d > dist[r][c]) continue;\n        for (const [dr,dc] of dirs) {\n            const nr=r+dr, nc=c+dc;\n            if (nr>=0&&nr<m&&nc>=0&&nc<n) {\n                const nd = Math.max(d, Math.abs(heights[nr][nc]-heights[r][c]));\n                if (nd < dist[nr][nc]) { dist[nr][nc]=nd; pq.push([nd,nr,nc]); }\n            }\n        }\n    }\n    return 0;\n}` },
    293: { javascript: `function calcEquation(equations, values, queries) {\n    const graph = new Map();\n    equations.forEach(([a,b], i) => {\n        if(!graph.has(a)) graph.set(a, []);\n        if(!graph.has(b)) graph.set(b, []);\n        graph.get(a).push([b, values[i]]);\n        graph.get(b).push([a, 1/values[i]]);\n    });\n    return queries.map(([a,b]) => {\n        if (!graph.has(a)||!graph.has(b)) return -1;\n        if (a===b) return 1;\n        const visited = new Set();\n        const q = [[a, 1]];\n        visited.add(a);\n        while (q.length) {\n            const [node, val] = q.shift();\n            if (node === b) return val;\n            for (const [next, w] of graph.get(node)||[]) {\n                if (!visited.has(next)) { visited.add(next); q.push([next, val*w]); }\n            }\n        }\n        return -1;\n    });\n}` },
    294: { python: `def shortestPathBinaryMatrix(grid):\n    from collections import deque\n    n = len(grid)\n    if grid[0][0] or grid[n-1][n-1]: return -1\n    q = deque([(0, 0, 1)])\n    grid[0][0] = 1\n    while q:\n        r, c, d = q.popleft()\n        if r == n-1 and c == n-1: return d\n        for dr in [-1,0,1]:\n            for dc in [-1,0,1]:\n                nr, nc = r+dr, c+dc\n                if 0 <= nr < n and 0 <= nc < n and not grid[nr][nc]:\n                    grid[nr][nc] = 1\n                    q.append((nr, nc, d+1))\n    return -1` },
    302: { python: `def coinChange(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for i in range(1, amount + 1):\n        for c in coins:\n            if c <= i:\n                dp[i] = min(dp[i], dp[i - c] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1` },
};

async function run() {
    console.log('Fixing remaining solutions - Batch 2...\n');
    let updated = 0, failed = 0;
    for (const [id, langSolutions] of Object.entries(solutions)) {
        const { data: problem } = await supabaseAdmin.from('problems').select('solution_code').eq('id', parseInt(id)).single();
        if (!problem) { console.log(`  Problem #${id} not found`); continue; }
        const merged = { ...(problem.solution_code || {}), ...langSolutions };
        const { error } = await supabaseAdmin.from('problems').update({ solution_code: merged }).eq('id', parseInt(id));
        if (error) { console.error(`  #${id}: ${error.message}`); failed++; }
        else { console.log(`  #${id} done`); updated++; }
    }
    console.log(`\nDone: ${updated} updated, ${failed} failed`);
}
run();
