import { supabaseAdmin } from '../db/supabaseClient.js';

// Correct solutions for remaining mismatched problems - Batch 1 (problems 45-162)
const solutions = {
    45: { python: `def findDuplicates(nums):\n    result = []\n    for num in nums:\n        idx = abs(num) - 1\n        if nums[idx] < 0:\n            result.append(abs(num))\n        else:\n            nums[idx] = -nums[idx]\n    return result`, javascript: `function findDuplicates(nums) {\n    const result = [];\n    for (let i = 0; i < nums.length; i++) {\n        const idx = Math.abs(nums[i]) - 1;\n        if (nums[idx] < 0) result.push(Math.abs(nums[i]));\n        else nums[idx] = -nums[idx];\n    }\n    return result;\n}` },
    53: { python: `def validPalindrome(s):\n    def isPalin(s, l, r):\n        while l < r:\n            if s[l] != s[r]: return False\n            l += 1; r -= 1\n        return True\n    l, r = 0, len(s) - 1\n    while l < r:\n        if s[l] != s[r]:\n            return isPalin(s, l+1, r) or isPalin(s, l, r-1)\n        l += 1; r -= 1\n    return True` },
    77: { python: `def hasCycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast: return True\n    return False` },
    78: { python: `def detectCycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast:\n            slow = head\n            while slow != fast:\n                slow = slow.next\n                fast = fast.next\n            return slow\n    return None`, javascript: `function detectCycle(head) {\n    let slow = head, fast = head;\n    while (fast && fast.next) {\n        slow = slow.next;\n        fast = fast.next.next;\n        if (slow === fast) {\n            slow = head;\n            while (slow !== fast) { slow = slow.next; fast = fast.next; }\n            return slow;\n        }\n    }\n    return null;\n}` },
    84: { javascript: `function removeNthFromEnd(head, n) {\n    const dummy = { next: head };\n    let fast = dummy, slow = dummy;\n    for (let i = 0; i <= n; i++) fast = fast.next;\n    while (fast) { fast = fast.next; slow = slow.next; }\n    slow.next = slow.next.next;\n    return dummy.next;\n}` },
    94: { python: `def minSubArrayLen(target, nums):\n    left = 0\n    total = 0\n    result = float('inf')\n    for right in range(len(nums)):\n        total += nums[right]\n        while total >= target:\n            result = min(result, right - left + 1)\n            total -= nums[left]\n            left += 1\n    return result if result != float('inf') else 0` },
    105: { python: `def dietPlanPerformance(calories, k, lower, upper):\n    points = 0\n    total = sum(calories[:k])\n    if total < lower: points -= 1\n    elif total > upper: points += 1\n    for i in range(k, len(calories)):\n        total += calories[i] - calories[i - k]\n        if total < lower: points -= 1\n        elif total > upper: points += 1\n    return points` },
    111: { python: `def longestNiceSubstring(s):\n    if len(s) < 2: return ""\n    for i, c in enumerate(s):\n        if c.swapcase() not in s:\n            left = longestNiceSubstring(s[:i])\n            right = longestNiceSubstring(s[i+1:])\n            return left if len(left) >= len(right) else right\n    return s` },
    112: { python: `def containsNearbyDuplicate(nums, k):\n    seen = {}\n    for i, num in enumerate(nums):\n        if num in seen and i - seen[num] <= k:\n            return True\n        seen[num] = i\n    return False` },
    118: { python: `def hasCycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast: return True\n    return False` },
    119: { python: `def detectCycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast:\n            slow = head\n            while slow != fast:\n                slow = slow.next\n                fast = fast.next\n            return slow\n    return None` },
    136: { javascript: `function addTwoNumbers(l1, l2) {\n    let dummy = { val: 0, next: null };\n    let curr = dummy, carry = 0;\n    while (l1 || l2 || carry) {\n        let sum = (l1 ? l1.val : 0) + (l2 ? l2.val : 0) + carry;\n        carry = Math.floor(sum / 10);\n        curr.next = { val: sum % 10, next: null };\n        curr = curr.next;\n        if (l1) l1 = l1.next;\n        if (l2) l2 = l2.next;\n    }\n    return dummy.next;\n}` },
    137: { javascript: `function addTwoNumbers(l1, l2) {\n    const stack1 = [], stack2 = [];\n    while (l1) { stack1.push(l1.val); l1 = l1.next; }\n    while (l2) { stack2.push(l2.val); l2 = l2.next; }\n    let carry = 0, head = null;\n    while (stack1.length || stack2.length || carry) {\n        let sum = (stack1.pop() || 0) + (stack2.pop() || 0) + carry;\n        carry = Math.floor(sum / 10);\n        let node = { val: sum % 10, next: head };\n        head = node;\n    }\n    return head;\n}` },
    141: { python: `def getIntersectionNode(headA, headB):\n    a, b = headA, headB\n    while a != b:\n        a = a.next if a else headB\n        b = b.next if b else headA\n    return a` },
    145: { python: `def getDecimalValue(head):\n    result = 0\n    while head:\n        result = result * 2 + head.val\n        head = head.next\n    return result` },
    148: { python: `def canTransform(start, end):\n    if start.replace('X','') != end.replace('X',''):\n        return False\n    i = j = 0\n    n = len(start)\n    while i < n and j < n:\n        while i < n and start[i] == 'X': i += 1\n        while j < n and end[j] == 'X': j += 1\n        if i == n or j == n: return i == n and j == n\n        if start[i] != end[j]: return False\n        if start[i] == 'R' and i > j: return False\n        if start[i] == 'L' and i < j: return False\n        i += 1; j += 1\n    return True` },
    151: { python: `class LFUCache:\n    def __init__(self, capacity):\n        self.cap = capacity\n        self.cache = {}\n        self.freq = {}\n        self.min_freq = 0\n        self.count = 0\n    def get(self, key):\n        if key not in self.cache: return -1\n        val, f = self.cache[key]\n        self._update(key, val, f)\n        return val\n    def put(self, key, value):\n        if self.cap <= 0: return\n        if key in self.cache:\n            _, f = self.cache[key]\n            self._update(key, value, f)\n            return\n        if self.count >= self.cap:\n            evict_key = next(iter(self.freq[self.min_freq]))\n            del self.freq[self.min_freq][evict_key]\n            del self.cache[evict_key]\n            self.count -= 1\n        self.cache[key] = (value, 1)\n        self.freq.setdefault(1, {})[key] = True\n        self.min_freq = 1\n        self.count += 1\n    def _update(self, key, val, freq):\n        del self.freq[freq][key]\n        if not self.freq[freq] and freq == self.min_freq:\n            self.min_freq += 1\n        self.cache[key] = (val, freq + 1)\n        self.freq.setdefault(freq + 1, {})[key] = True`, javascript: `class LFUCache {\n    constructor(capacity) {\n        this.cap = capacity;\n        this.cache = new Map();\n        this.freqMap = new Map();\n        this.minFreq = 0;\n    }\n    get(key) {\n        if (!this.cache.has(key)) return -1;\n        const { val, freq } = this.cache.get(key);\n        this._update(key, val, freq);\n        return val;\n    }\n    put(key, value) {\n        if (this.cap <= 0) return;\n        if (this.cache.has(key)) {\n            const { freq } = this.cache.get(key);\n            this._update(key, value, freq);\n            return;\n        }\n        if (this.cache.size >= this.cap) {\n            const keys = this.freqMap.get(this.minFreq);\n            const evict = keys.values().next().value;\n            keys.delete(evict);\n            this.cache.delete(evict);\n        }\n        this.cache.set(key, { val: value, freq: 1 });\n        if (!this.freqMap.has(1)) this.freqMap.set(1, new Set());\n        this.freqMap.get(1).add(key);\n        this.minFreq = 1;\n    }\n    _update(key, val, freq) {\n        this.freqMap.get(freq).delete(key);\n        if (this.freqMap.get(freq).size === 0 && freq === this.minFreq) this.minFreq++;\n        this.cache.set(key, { val, freq: freq + 1 });\n        if (!this.freqMap.has(freq + 1)) this.freqMap.set(freq + 1, new Set());\n        this.freqMap.get(freq + 1).add(key);\n    }\n}` },
    152: { python: `class AllOne:\n    def __init__(self):\n        self.counts = {}\n    def inc(self, key):\n        self.counts[key] = self.counts.get(key, 0) + 1\n    def dec(self, key):\n        self.counts[key] -= 1\n        if self.counts[key] == 0: del self.counts[key]\n    def getMaxKey(self):\n        return max(self.counts, key=self.counts.get) if self.counts else ""\n    def getMinKey(self):\n        return min(self.counts, key=self.counts.get) if self.counts else ""`, javascript: `class AllOne {\n    constructor() { this.counts = new Map(); }\n    inc(key) { this.counts.set(key, (this.counts.get(key) || 0) + 1); }\n    dec(key) { const v = this.counts.get(key) - 1; v === 0 ? this.counts.delete(key) : this.counts.set(key, v); }\n    getMaxKey() { let mx = 0, mk = ""; this.counts.forEach((v,k) => { if(v>mx){mx=v;mk=k;} }); return mk; }\n    getMinKey() { let mn = Infinity, mk = ""; this.counts.forEach((v,k) => { if(v<mn){mn=v;mk=k;} }); return mk; }\n}` },
    153: { python: `import random\nclass Skiplist:\n    def __init__(self):\n        self.data = []\n    def search(self, target):\n        return target in self.data\n    def add(self, num):\n        self.data.append(num)\n        self.data.sort()\n    def erase(self, num):\n        if num in self.data:\n            self.data.remove(num)\n            return True\n        return False`, javascript: `class Skiplist {\n    constructor() { this.data = []; }\n    search(target) { return this.data.includes(target); }\n    add(num) { this.data.push(num); this.data.sort((a,b)=>a-b); }\n    erase(num) { const i = this.data.indexOf(num); if(i>=0){this.data.splice(i,1);return true;} return false; }\n}` },
    159: { python: `class MinStack:\n    def __init__(self):\n        self.stack = []\n        self.min_stack = []\n    def push(self, val):\n        self.stack.append(val)\n        if not self.min_stack or val <= self.min_stack[-1]:\n            self.min_stack.append(val)\n    def pop(self):\n        if self.stack.pop() == self.min_stack[-1]:\n            self.min_stack.pop()\n    def top(self):\n        return self.stack[-1]\n    def getMin(self):\n        return self.min_stack[-1]` },
    160: { python: `class MaxStack:\n    def __init__(self):\n        self.stack = []\n        self.max_stack = []\n    def push(self, x):\n        self.stack.append(x)\n        self.max_stack.append(max(x, self.max_stack[-1] if self.max_stack else x))\n    def pop(self):\n        self.max_stack.pop()\n        return self.stack.pop()\n    def top(self):\n        return self.stack[-1]\n    def peekMax(self):\n        return self.max_stack[-1]\n    def popMax(self):\n        mx = self.peekMax()\n        buf = []\n        while self.top() != mx:\n            buf.append(self.pop())\n        self.pop()\n        for v in reversed(buf):\n            self.push(v)\n        return mx` },
    161: { python: `class MyQueue:\n    def __init__(self):\n        self.s1 = []\n        self.s2 = []\n    def push(self, x):\n        self.s1.append(x)\n    def pop(self):\n        self._move()\n        return self.s2.pop()\n    def peek(self):\n        self._move()\n        return self.s2[-1]\n    def empty(self):\n        return not self.s1 and not self.s2\n    def _move(self):\n        if not self.s2:\n            while self.s1:\n                self.s2.append(self.s1.pop())`, javascript: `class MyQueue {\n    constructor() { this.s1 = []; this.s2 = []; }\n    push(x) { this.s1.push(x); }\n    pop() { this._move(); return this.s2.pop(); }\n    peek() { this._move(); return this.s2[this.s2.length-1]; }\n    empty() { return !this.s1.length && !this.s2.length; }\n    _move() { if(!this.s2.length) while(this.s1.length) this.s2.push(this.s1.pop()); }\n}` },
    162: { python: `class MyStack:\n    def __init__(self):\n        from collections import deque\n        self.q = deque()\n    def push(self, x):\n        self.q.append(x)\n        for _ in range(len(self.q) - 1):\n            self.q.append(self.q.popleft())\n    def pop(self):\n        return self.q.popleft()\n    def top(self):\n        return self.q[0]\n    def empty(self):\n        return len(self.q) == 0`, javascript: `class MyStack {\n    constructor() { this.q = []; }\n    push(x) { this.q.push(x); for(let i=0;i<this.q.length-1;i++) this.q.push(this.q.shift()); }\n    pop() { return this.q.shift(); }\n    top() { return this.q[0]; }\n    empty() { return this.q.length === 0; }\n}` },
};

async function run() {
    console.log('🔧 Fixing remaining solution mismatches - Batch 1...\n');
    let updated = 0, failed = 0;
    for (const [id, langSolutions] of Object.entries(solutions)) {
        const { data: problem } = await supabaseAdmin.from('problems').select('solution_code').eq('id', parseInt(id)).single();
        if (!problem) { console.log(`  ⚠️ Problem #${id} not found`); continue; }
        const merged = { ...(problem.solution_code || {}), ...langSolutions };
        const { error } = await supabaseAdmin.from('problems').update({ solution_code: merged }).eq('id', parseInt(id));
        if (error) { console.error(`  ❌ #${id}: ${error.message}`); failed++; }
        else { console.log(`  ✅ #${id}`); updated++; }
    }
    console.log(`\nDone: ${updated} updated, ${failed} failed`);
}
run();
