// Batch update: All remaining problems with real descriptions & constraints
// Covers: Fast & Slow Pointers, Linked List, Stack, Binary Search, Trees, Graphs, DP, etc.
import { supabaseAdmin } from '../db/supabaseClient.js';

const updates = [
    // ── Fast & Slow Pointers (117-131) ──
    { id: 117, description: 'Given the head of a singly linked list, return the middle node of the linked list. If there are two middle nodes, return the second middle node.', constraints: '1 <= number of nodes <= 100\n1 <= Node.val <= 100' },
    { id: 118, description: 'Given head, the head of a linked list, determine if the linked list has a cycle in it. Return true if there is a cycle, otherwise return false.', constraints: '0 <= number of nodes <= 10^4\n-10^5 <= Node.val <= 10^5' },
    { id: 119, description: 'Given the head of a linked list, return the node where the cycle begins. If there is no cycle, return null.', constraints: '0 <= number of nodes <= 10^4\n-10^5 <= Node.val <= 10^5' },
    { id: 120, description: 'Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive, there is only one repeated number. Return this repeated number without modifying the array and using only constant extra space.', constraints: '1 <= n <= 10^5\nnums.length == n + 1\n1 <= nums[i] <= n' },
    { id: 121, description: 'Write an algorithm to determine if a number n is happy. A happy number is defined by replacing the number by the sum of the squares of its digits, repeating until it equals 1 or loops endlessly. Return true if n is happy.', constraints: '1 <= n <= 2^31 - 1' },
    { id: 122, description: 'You are playing a game involving a circular array of non-zero integers nums. Each nums[i] denotes the number of indices forward/backward you must move. A cycle must be all positive or all negative and length > 1. Return true if there is a cycle.', constraints: '1 <= nums.length <= 5000\n-1000 <= nums[i] <= 1000\nnums[i] != 0' },
    { id: 123, description: 'Given the head of a singly linked list, return true if it is a palindrome or false otherwise.\n\nFollow up: Could you do it in O(n) time and O(1) space?', constraints: '1 <= number of nodes <= 10^5\n0 <= Node.val <= 9' },
    { id: 124, description: 'You are given the head of a singly linked-list. Reorder the list to be: L0 -> Ln -> L1 -> Ln-1 -> L2 -> Ln-2 -> ... You may not modify the values in the list nodes.', constraints: '1 <= number of nodes <= 5 * 10^4\n1 <= Node.val <= 1000' },
    { id: 125, description: 'Given the head of a linked list, rotate the list to the right by k places.', constraints: '0 <= number of nodes <= 500\n-100 <= Node.val <= 100\n0 <= k <= 2 * 10^9' },
    { id: 126, description: 'You are given the head of a linked list. Delete the middle node, and return the head of the modified linked list. The middle node is the ⌊n / 2⌋th node (0-indexed).', constraints: '1 <= number of nodes <= 10^5\n1 <= Node.val <= 10^5' },
    { id: 127, description: 'In a linked list of size n (even), the ith node (0-indexed) is the twin of the (n-1-i)th node. The twin sum is the sum of a node and its twin. Return the maximum twin sum.', constraints: '2 <= number of nodes <= 10^5\n1 <= Node.val <= 10^5' },
    { id: 128, description: 'You are given the head of a linked list containing unique integer values and an integer array G. Return the number of connected components in G, where two values are connected if they appear consecutively in the linked list.', constraints: '1 <= G.length <= 10000\n0 <= G[i] < N' },
    { id: 129, description: 'Given the head of a singly linked list, group all the nodes with odd indices together followed by the nodes with even indices, and return the reordered list. The first node is considered odd, the second even, and so on.', constraints: '0 <= number of nodes <= 10^4\n-10^6 <= Node.val <= 10^6' },
    { id: 130, description: 'You are given the head of a linked list. Remove every node which has a node with a greater value anywhere to the right side of it. Return the head of the modified linked list.', constraints: '1 <= number of nodes <= 10^5\n1 <= Node.val <= 10^5' },
    { id: 131, description: 'Given the head of a singly linked list and an integer k, split the linked list into k consecutive linked list parts. The length of each part should be as equal as possible.', constraints: '0 <= number of nodes <= 1000\n0 <= Node.val <= 1000\n1 <= k <= 50' },

    // ── Linked List (133-156) ──
    { id: 133, description: 'Given the head of a singly linked list and two integers left and right where left <= right, reverse the nodes of the list from position left to position right, and return the reversed list.', constraints: '1 <= number of nodes <= 500\n-500 <= Node.val <= 500\n1 <= left <= right <= n' },
    { id: 134, description: 'Given the head of a linked list, reverse the nodes of the list k at a time, and return the modified list. k is a positive integer and is less than or equal to the length of the linked list. If the number of nodes is not a multiple of k then left-out nodes, in the end, should remain as it is.', constraints: '1 <= number of nodes <= 5000\n0 <= Node.val <= 1000\n1 <= k <= n' },
    { id: 135, description: 'Given a linked list, swap every two adjacent nodes and return its head. You must solve the problem without modifying the values in the list nodes (i.e., only nodes themselves may be changed.)', constraints: '0 <= number of nodes <= 100\n0 <= Node.val <= 100' },
    { id: 136, description: 'You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.', constraints: '1 <= number of nodes <= 100\n0 <= Node.val <= 9\nThe number represented does not contain leading zeros except the number 0 itself.' },
    { id: 137, description: 'You are given two non-empty linked lists representing two non-negative integers. The most significant digit comes first and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.', constraints: '1 <= number of nodes <= 100\n0 <= Node.val <= 9\nThe numbers do not contain any leading zeros except the number 0 itself.' },
    { id: 139, description: 'You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.', constraints: 'k == lists.length\n0 <= k <= 10^4\n0 <= lists[i].length <= 500\n-10^4 <= lists[i][j] <= 10^4\nlists[i] is sorted in ascending order.\nThe sum of lists[i].length will not exceed 10^4.' },
    { id: 140, description: 'A linked list of length n is given such that each node contains an additional random pointer, which could point to any node in the list, or null. Construct a deep copy of the list.', constraints: '0 <= n <= 1000\n-10^4 <= Node.val <= 10^4\nNode.random is null or is pointing to some node in the linked list.' },
    { id: 141, description: 'Given the heads of two singly linked-lists headA and headB, return the node at which the two lists intersect. If the two linked lists have no intersection at all, return null.', constraints: 'The number of nodes of listA is in the m.\nThe number of nodes of listB is in the n.\n1 <= m, n <= 3 * 10^4\n1 <= Node.val <= 10^5' },
    { id: 142, description: 'Design your implementation of the linked list. You can choose to use a singly or doubly linked list. Implement the MyLinkedList class with get, addAtHead, addAtTail, addAtIndex, and deleteAtIndex operations.', constraints: '0 <= index, val <= 1000\nAt most 2000 calls will be made to get, addAtHead, addAtTail, addAtIndex, and deleteAtIndex.' },
    { id: 143, description: 'You are given a doubly linked list, which contains nodes that have a next pointer, a previous pointer, and an additional child pointer. This child pointer may or may not point to a separate doubly linked list. Flatten the list so that all the nodes appear in a single-level, doubly linked list.', constraints: '0 <= number of nodes <= 1000\n1 <= Node.val <= 10^5' },
    { id: 144, description: 'Given a Circular Linked List node, which is sorted in non-descending order, write a function to insert a value insertVal into the list such that it remains a sorted circular list.', constraints: '0 <= number of nodes <= 5 * 10^4\n-10^6 <= Node.val, insertVal <= 10^6' },
    { id: 145, description: 'Given head which is a reference node to a singly-linked list. The value of each node in the linked list is either 0 or 1. The linked list holds the binary representation of a number. Return the decimal value of the number in the linked list.', constraints: 'The linked list is not empty.\nNumber of nodes will not exceed 30.\nEach node value is either 0 or 1.' },
    { id: 146, description: 'You are given a linked list with head as the first node. For each node in the list, find the value of the next greater node. That is, for each node, find the value of the first node that is next to it and has a strictly larger value than it. Return an integer array answer where answer[i] is the value of the next greater node of the ith node.', constraints: '1 <= number of nodes <= 10^4\n1 <= Node.val <= 10^9' },
    { id: 147, description: 'Given a binary tree root and a linked list with head as the first node. Return True if all the elements in the linked list starting from the head correspond to some downward path connected in the binary tree, otherwise return False.', constraints: '1 <= number of nodes in tree <= 2500\n1 <= number of nodes in list <= 100\n1 <= Node.val <= 100' },
    { id: 148, description: 'In a string composed of L, R, and X characters, a move consists of either replacing one occurrence of XL with LX, or replacing one occurrence of RX with XR. Given the starting string start and the ending string end, return True if and only if there exists a sequence of moves to transform one string to the other.', constraints: '1 <= start.length <= 10^4\nstart.length == end.length\nBoth start and end will only consist of characters L, R, and X.' },
    { id: 149, description: 'You have a browser of one tab where you start on the homepage and you can visit another url, get back in the history number of steps or move forward in the history number of steps. Implement the BrowserHistory class.', constraints: '1 <= homepage.length <= 20\n1 <= url.length <= 20\n1 <= steps <= 100\nAt most 5000 calls will be made.' },
    { id: 150, description: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.\n\nImplement the LRUCache class:\n- LRUCache(int capacity) Initialize the LRU cache with positive size capacity.\n- int get(int key) Return the value of the key if it exists, otherwise return -1.\n- void put(int key, int value) Update the value of the key if it exists. Otherwise, add the key-value pair. If the number of keys exceeds the capacity, evict the least recently used key.\n\nThe functions get and put must each run in O(1) average time complexity.', constraints: '1 <= capacity <= 3000\n0 <= key <= 10^4\n0 <= value <= 10^5\nAt most 2 * 10^5 calls will be made to get and put.' },
    { id: 151, description: 'Design and implement a data structure for a Least Frequently Used (LFU) cache.\n\nImplement the LFUCache class:\n- LFUCache(int capacity) Initializes the object with the capacity of the data structure.\n- int get(int key) Gets the value of the key if it exists, otherwise returns -1.\n- void put(int key, int value) Update the value or insert. When the cache reaches its capacity, invalidate and remove the least frequently used key. When there is a tie, the least recently used key is evicted.\n\nThe functions get and put must each run in O(1) average time complexity.', constraints: '1 <= capacity <= 10^4\n0 <= key <= 10^5\n0 <= value <= 10^9\nAt most 2 * 10^5 calls will be made to get and put.' },
    { id: 152, description: 'Design a data structure to store the strings count with the ability to return the strings with minimum and maximum counts.\n\nImplement the AllOne class:\n- AllOne() Initializes the object of the data structure.\n- inc(String key) Increments the count of the string key by 1.\n- dec(String key) Decrements the count of the string key by 1. If the count reaches 0, remove it.\n- getMaxKey() Returns one of the keys with the maximal count. If no element exists, return "".\n- getMinKey() Returns one of the keys with the minimum count. If no element exists, return "".\n\nEach function must run in O(1) average time complexity.', constraints: '1 <= key.length <= 10\nkey consists of lowercase English letters.\nAt most 5 * 10^4 calls will be made.' },
    { id: 153, description: 'Design a Skiplist without using any built-in libraries.\n\nA Skiplist is a data structure that takes O(log(n)) time to add, erase and search. Implement the Skiplist class with search, add, and erase operations.', constraints: '0 <= num, target <= 2 * 10^4\nAt most 5 * 10^4 calls will be made to search, add, and erase.' },
    { id: 154, description: 'Given the root of a binary tree, flatten the tree into a "linked list":\n\n- The "linked list" should use the same TreeNode class where the right child pointer points to the next node in the list and the left child pointer is always null.\n- The "linked list" should be in the same order as a pre-order traversal of the binary tree.', constraints: '0 <= number of nodes <= 2000\n-100 <= Node.val <= 100' },
    { id: 155, description: 'Given the head of a singly linked list where elements are sorted in ascending order, convert it to a height-balanced binary search tree.', constraints: '-10^5 <= Node.val <= 10^5\nThe number of nodes in the list is in the range [0, 2 * 10^4].' },
    { id: 156, description: 'Given the head of a linked list, return the list after sorting it in ascending order.\n\nFollow up: Can you sort the linked list in O(n logn) time and O(1) memory?', constraints: '0 <= number of nodes <= 5 * 10^4\n-10^5 <= Node.val <= 10^5' },

    // ── Stack (158-180) ──
    { id: 158, description: 'Given a string containing just the characters ( and ), return the length of the longest valid (well-formed) parentheses substring.', constraints: '0 <= s.length <= 3 * 10^4\ns[i] is ( or ).' },
    { id: 159, description: 'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.\n\nImplement the MinStack class:\n- MinStack() initializes the stack object.\n- void push(int val) pushes the element val onto the stack.\n- void pop() removes the element on the top of the stack.\n- int top() gets the top element of the stack.\n- int getMin() retrieves the minimum element in the stack.\n\nYou must implement a solution with O(1) time complexity for each function.', constraints: '-2^31 <= val <= 2^31 - 1\nMethods pop, top and getMin operations will always be called on non-empty stacks.\nAt most 3 * 10^4 calls will be made to push, pop, top, and getMin.' },
    { id: 160, description: 'Design a max stack data structure that supports the stack operations and supports finding the stack maximum element.\n\nImplement the MaxStack class:\n- MaxStack() Initializes the stack object.\n- void push(int x) Pushes element x onto the stack.\n- int pop() Removes the element on top of the stack and returns it.\n- int top() Gets the element on the top of the stack without removing it.\n- int peekMax() Retrieves the maximum element in the stack without removing it.\n- int popMax() Retrieves the maximum element in the stack and removes it.', constraints: '-10^7 <= x <= 10^7\nAt most 10^4 calls will be made.\nMethods will not be called when the stack is empty.' },
    { id: 161, description: 'Implement a first in first out (FIFO) queue using only two stacks. The implemented queue should support all the functions of a normal queue (push, peek, pop, and empty).', constraints: '1 <= x <= 9\nAt most 100 calls will be made to push, pop, peek, and empty.\nAll the calls to pop and peek are valid.' },
    { id: 162, description: 'Implement a last-in-first-out (LIFO) stack using only two queues. The implemented stack should support all the functions of a normal stack (push, top, pop, and empty).', constraints: '1 <= x <= 9\nAt most 100 calls will be made to push, pop, top, and empty.\nAll the calls to pop and top are valid.' },
    { id: 163, description: 'You are given an array of string tokens that represents an arithmetic expression in Reverse Polish Notation.\n\nEvaluate the expression. Return an integer that represents the value of the expression.\n\nNote that the valid operators are +, -, *, and /. Each operand may be an integer or another expression. The division between two integers always truncates toward zero.', constraints: '1 <= tokens.length <= 10^4\ntokens[i] is either an operator: +, -, *, or /, or an integer in the range [-200, 200].' },
    { id: 164, description: 'Given a string s representing a valid expression, implement a basic calculator to evaluate it, and return the result of the evaluation.\n\nNote: You are not allowed to use any built-in function which evaluates strings as mathematical expressions, such as eval().', constraints: '1 <= s.length <= 3 * 10^5\ns consists of digits, +, -, (, ), and spaces.\ns represents a valid expression.\nEvery number and running calculation will fit in a signed 32-bit integer.' },
    { id: 165, description: 'Given a string s which represents an expression, evaluate this expression and return its value.\n\nThe integer division should truncate toward zero.\n\nYou may assume that the given expression is always valid. All intermediate results will be in the range of [-2^31, 2^31 - 1].', constraints: '1 <= s.length <= 3 * 10^5\ns consists of integers and operators (+, -, *, /) separated by some number of spaces.\ns represents a valid expression.\nAll the integers in the expression are non-negative and in the range [0, 2^31 - 1].' },
    { id: 166, description: 'Implement a basic calculator to evaluate a simple expression string. The expression string contains only non-negative integers, +, -, *, / operators, open ( and closing parentheses ), and empty spaces. The integer division should truncate toward zero.', constraints: '1 <= s.length <= 10^4\ns consists of digits, +, -, *, /, (, ) and spaces.\ns represents a valid expression.' },
    { id: 167, description: 'Given an absolute path for a Unix-style file system, which begins with a slash /, transform this path into its simplified canonical path.\n\nIn Unix-style file system context, a single period . refers to the current directory, a double period .. moves up a directory, and any multiple consecutive slashes are treated as a single slash /. The canonical path should have the following format: start with a single slash /, directories separated by a single slash /, not end with a trailing /, and only contain the directories on the path from the root directory to the target file or directory.', constraints: '1 <= path.length <= 3000\npath consists of English letters, digits, period, slash, or underscore.\npath is a valid absolute Unix path.' },
    { id: 168, description: 'You are given a string s consisting of lowercase English letters. A duplicate removal consists of choosing two adjacent and equal letters and removing them. We repeatedly make duplicate removals on s until we no longer can. Return the final string after all such duplicate removals have been made.', constraints: '1 <= s.length <= 10^5\ns consists of lowercase English letters.' },
    { id: 169, description: 'You are given a string s and an integer k, a k duplicate removal consists of choosing k adjacent and equal letters from s and removing them, causing the left and the right side of the deleted substring to concatenate together. We repeatedly make k duplicate removals on s until we no longer can. Return the final string after all such duplicate removals have been made.', constraints: '1 <= s.length <= 10^5\n2 <= k <= 10^4\ns only contains lowercase English letters.' },
    { id: 170, description: 'Given string num representing a non-negative integer num, and an integer k, return the smallest possible integer after removing k digits from num.', constraints: '1 <= k <= num.length <= 10^5\nnum consists of only digits.\nnum does not have any leading zeros except for the zero itself.' },
    { id: 171, description: 'You are given two integer arrays nums1 and nums2 of lengths m and n respectively, representing the digits of two numbers. You are also given an integer k. Create the maximum number of length k from digits of the two numbers. The relative order of the digits from the same array must be preserved. Return an array of the k digits representing the answer.', constraints: 'm == nums1.length\nn == nums2.length\n1 <= m, n <= 500\n0 <= nums1[i], nums2[i] <= 9\n1 <= k <= m + n' },
    { id: 172, description: 'Given an encoded string, return its decoded string.\n\nThe encoding rule is: k[encoded_string], where the encoded_string inside the square brackets is being repeated exactly k times. Note that k is guaranteed to be a positive integer.\n\nYou may assume that the input string is always valid; there are no extra white spaces, square brackets are well-formed, etc. Furthermore, you may assume that the original data does not contain any digits and that digits are only for those repeat numbers, k.', constraints: '1 <= s.length <= 30\ns consists of lowercase English letters, digits, and square brackets [].\ns is guaranteed to be a valid input.\nAll the integers in s are in the range [1, 300].' },
    { id: 173, description: 'Given a string formula representing a chemical formula, return the count of each atom.\n\nThe atomic element always starts with an uppercase character, then zero or more lowercase letters. 1 or more digits representing the count of that element may follow. Two formulas can be concatenated. A formula placed in parentheses, and a count (optionally added) is also a formula.', constraints: '1 <= formula.length <= 1000\nformula consists of English letters, digits, (, and ).\nformula is always valid.' },
    { id: 174, description: 'We are given an array asteroids of integers representing asteroids in a row. For each asteroid, the absolute value represents its size, and the sign represents its direction (positive meaning right, negative meaning left). Each asteroid moves at the same speed.\n\nFind out the state of the asteroids after all collisions. If two asteroids meet, the smaller one will explode. If both are the same size, both will explode. Two asteroids moving in the same direction will never meet.', constraints: '2 <= asteroids.length <= 10^4\n-1000 <= asteroids[i] <= 1000\nasteroids[i] != 0' },
    { id: 175, description: 'Given an array of integers temperatures represents the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the ith day to get a warmer temperature. If there is no future day for which this is possible, keep answer[i] == 0 instead.', constraints: '1 <= temperatures.length <= 10^5\n30 <= temperatures[i] <= 100' },
    { id: 176, description: 'The next greater element of some element x in an array is the first greater element that is to the right of x in the same array.\n\nYou are given two distinct 0-indexed integer arrays nums1 and nums2, where nums1 is a subset of nums2. For each 0 <= i < nums1.length, find the index j such that nums1[i] == nums2[j] and determine the next greater element of nums2[j] in nums2. If there is no next greater element, then the answer for this query is -1.', constraints: '1 <= nums1.length <= nums2.length <= 1000\n0 <= nums1[i], nums2[i] <= 10^4\nAll integers in nums1 and nums2 are unique.\nAll the integers of nums1 also appear in nums2.' },
    { id: 177, description: 'Given a circular integer array nums (the next element of nums[nums.length - 1] is nums[0]), return the next greater number for every element in nums. The next greater number of a number x is the first greater number to its traversing-order next in the array.', constraints: '1 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9' },
    { id: 178, description: 'Given a positive integer n, return the smallest integer which has exactly the same digits existing in the integer n and is greater in value than n. If no such positive integer exists, return -1. Note that the returned integer should fit in a 32-bit integer.', constraints: '1 <= n <= 2^31 - 1' },
    { id: 179, description: 'Given an array of integers heights representing the histogram bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.', constraints: '1 <= heights.length <= 10^5\n0 <= heights[i] <= 10^4' },
    { id: 180, description: 'Given a rows x cols binary matrix filled with 0s and 1s, find the largest rectangle containing only 1s and return its area.', constraints: 'rows == matrix.length\ncols == matrix[i].length\n1 <= rows, cols <= 200\nmatrix[i][j] is 0 or 1.' },
];

async function run() {
    console.log('Updating ' + updates.length + ' problems...');
    let ok = 0, fail = 0;
    for (const u of updates) {
        const { error } = await supabaseAdmin.from('problems').update({
            description: u.description,
            constraints: u.constraints
        }).eq('id', u.id);
        if (error) { console.error('FAIL [' + u.id + ']: ' + error.message); fail++; }
        else { ok++; }
    }
    console.log('Done: ' + ok + ' ok, ' + fail + ' fail');
}
run().catch(console.error);
