// Batch 3: Binary Search, Tree, BFS/DFS, Heap problems
import { supabaseAdmin } from '../db/supabaseClient.js';

const updates = [
    // ── Remaining Stack (no IDs here - covered in batch2 up to 180) ──
    // Stack has some extra IDs from the Trapping Rain Water Stack copy, etc.

    // ── Binary Search (181-215) ──
    { id: 181, description: 'Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.\n\nYou must write an algorithm with O(log n) runtime complexity.', constraints: '1 <= nums.length <= 10^4\n-10^4 < nums[i], target < 10^4\nAll the integers in nums are unique.\nnums is sorted in ascending order.' },
    { id: 182, description: 'Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.\n\nYou must write an algorithm with O(log n) runtime complexity.', constraints: '1 <= nums.length <= 10^4\n-10^4 <= nums[i] <= 10^4\nnums contains distinct values sorted in ascending order.\n-10^4 <= target <= 10^4' },
    { id: 183, description: 'You are a product manager and currently leading a team to develop a new product. Unfortunately, the latest version of your product fails the quality check. Since each version is developed based on the previous version, all the versions after a bad version are also bad.\n\nYou are given an API bool isBadVersion(version) which returns whether version is bad. Implement a function to find the first bad version. You should minimize the number of calls to the API.', constraints: '1 <= bad <= n <= 2^31 - 1' },
    { id: 184, description: 'Given a non-negative integer x, return the square root of x rounded down to the nearest integer. The returned integer should be non-negative as well.\n\nYou must not use any built-in exponent function or operator.', constraints: '0 <= x <= 2^31 - 1' },
    { id: 185, description: 'Given a positive integer num, return true if num is a perfect square or false otherwise.\n\nA perfect square is an integer that is the square of an integer; in other words, it is the product of some integer with itself.\n\nYou must not use any built-in library function, such as sqrt.', constraints: '1 <= num <= 2^31 - 1' },
    { id: 186, description: 'We are playing the Guess Game. I pick a number from 1 to n. You have to guess which number I picked.\n\nEvery time you guess wrong, I will tell you whether the number I picked is higher or lower than your guess.\n\nYou call a pre-defined API int guess(int num), which returns three possible results: -1 (my number is lower), 1 (my number is higher), or 0 (you got it!).', constraints: '1 <= n <= 2^31 - 1\n1 <= pick <= n' },
    { id: 187, description: 'You are given an array of characters letters that is sorted in non-decreasing order, and a character target. There are at least two different characters in letters.\n\nReturn the smallest character in letters that is lexicographically greater than target. If such a character does not exist, return the first character in letters.\n\nNote that the letters wrap around.', constraints: '2 <= letters.length <= 10^4\nletters[i] is a lowercase English letter.\nletters is sorted in non-decreasing order.\nletters contains at least two different characters.\ntarget is a lowercase English letter.' },
    { id: 188, description: 'An array arr is a mountain array if and only if arr.length >= 3 and there exists some i with 0 < i < arr.length - 1 such that arr[0] < arr[1] < ... < arr[i - 1] < arr[i] and arr[i] > arr[i + 1] > ... > arr[arr.length - 1].\n\nGiven a mountain array arr, return the index i such that arr[0] < arr[1] < ... < arr[i - 1] < arr[i] > arr[i + 1] > ... > arr[arr.length - 1].\n\nYou must solve it in O(log(arr.length)) time complexity.', constraints: '3 <= arr.length <= 10^5\n0 <= arr[i] <= 10^6\narr is guaranteed to be a mountain array.' },
    { id: 189, description: 'A peak element is an element that is strictly greater than its neighbors.\n\nGiven a 0-indexed integer array nums, find a peak element, and return its index. If the array contains multiple peaks, return the index to any of the peaks.\n\nYou may imagine that nums[-1] = nums[n] = -infinity. In other words, an element is always considered to be strictly greater than a neighbor that is outside the array.\n\nYou must write an algorithm that runs in O(log n) time.', constraints: '1 <= nums.length <= 1000\n-2^31 <= nums[i] <= 2^31 - 1\nnums[i] != nums[i + 1] for all valid i.' },
    { id: 190, description: 'There is an integer array nums sorted in ascending order (with distinct values). Prior to being passed to your function, nums is possibly rotated at an unknown pivot index k.\n\nGiven the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.\n\nYou must write an algorithm with O(log n) runtime complexity.', constraints: '1 <= nums.length <= 5000\n-10^4 <= nums[i] <= 10^4\nAll values of nums are unique.\nnums is an ascending array that is possibly rotated.\n-10^4 <= target <= 10^4' },
    { id: 191, description: 'There is an integer array nums sorted in non-decreasing order (not necessarily with distinct values). Before being passed to your function, nums is rotated at an unknown pivot index k.\n\nGiven the array nums after the rotation and an integer target, return true if target is in nums, or false if it is not in nums.', constraints: '1 <= nums.length <= 5000\n-10^4 <= nums[i] <= 10^4\nnums is guaranteed to be rotated at some pivot.\n-10^4 <= target <= 10^4' },
    { id: 192, description: 'Suppose an array of length n sorted in ascending order is rotated between 1 and n times. Given the sorted rotated array nums of unique elements, return the minimum element of this array.\n\nYou must write an algorithm that runs in O(log n) time.', constraints: 'n == nums.length\n1 <= n <= 5000\n-5000 <= nums[i] <= 5000\nAll the integers of nums are unique.\nnums is sorted and rotated between 1 and n times.' },
    { id: 193, description: 'Suppose an array of length n sorted in ascending order is rotated between 1 and n times. The array may contain duplicates. Given the sorted rotated array nums, return the minimum element of this array.\n\nYou must decrease the overall operation steps as much as possible.', constraints: 'n == nums.length\n1 <= n <= 5000\n-5000 <= nums[i] <= 5000\nnums is sorted and rotated between 1 and n times.' },
    { id: 194, description: 'You are given a sorted array consisting of only integers where every element appears exactly twice, except for one element which appears exactly once. Return the single element that appears only once.\n\nYour solution must run in O(log n) time and O(1) space.', constraints: '1 <= nums.length <= 10^5\n0 <= nums[i] <= 10^5' },
    { id: 195, description: 'Given a sorted integer array arr, two integers k and x, return the k closest integers to x in the array. The result should also be sorted in ascending order.\n\nAn integer a is closer to x than an integer b if |a - x| < |b - x|, or |a - x| == |b - x| and a < b.', constraints: '1 <= k <= arr.length\n1 <= arr.length <= 10^4\narr is sorted in ascending order.\n-10^4 <= arr[i], x <= 10^4' },
    { id: 197, description: 'Given the integer n, return the smallest pair distance among all pairs. The pair distance is defined as the absolute difference between two elements in nums. Given an array of integers nums and an integer k, return the kth smallest distance among all the pairs nums[i] and nums[j] where 0 <= i < j < nums.length.', constraints: 'n == nums.length\n2 <= n <= 10^4\n0 <= nums[i] <= 10^6\n1 <= k <= n * (n - 1) / 2' },
    { id: 198, description: 'Koko loves to eat bananas. There are n piles of bananas, the ith pile has piles[i] bananas. The guards have gone and will come back in h hours.\n\nKoko can decide her bananas-per-hour eating speed of k. Each hour, she chooses some pile of bananas and eats k bananas from that pile. If the pile has less than k bananas, she eats all of them instead and will not eat any more bananas during this hour.\n\nKoko likes to eat slowly but still wants to finish eating all the bananas before the guards return. Return the minimum integer k such that she can eat all the bananas within h hours.', constraints: '1 <= piles.length <= 10^4\npiles.length <= h <= 10^9\n1 <= piles[i] <= 10^9' },
    { id: 199, description: 'You are given n gas stations along a circular route. You need to add k more gas stations. Minimize the maximum distance between adjacent gas stations after adding the k new stations. Return the minimum possible value of the maximum distance.', constraints: '2 <= stations.length <= 10\n0 <= stations[i] <= 10^8\nstations is sorted in a strictly increasing order.\n1 <= k <= 10^6' },
    { id: 200, description: 'Given an integer array nums and an integer k, split nums into k non-empty subarrays such that the largest sum of any subarray is minimized. Return the minimized largest sum of the split.', constraints: '1 <= nums.length <= 1000\n0 <= nums[i] <= 10^6\n1 <= k <= min(50, nums.length)' },
    { id: 201, description: 'A conveyor belt has packages that must be shipped from one port to another within days days. The ith package on the conveyor belt has a weight of weights[i]. Each day, we load the ship with packages on the conveyor belt (in the order given by weights). We may not load more weight than the maximum weight capacity of the ship.\n\nReturn the least weight capacity of the ship that will result in all the packages on the conveyor belt being shipped within days days.', constraints: '1 <= days <= weights.length <= 5 * 10^4\n1 <= weights[i] <= 500' },
    { id: 202, description: 'You have one chocolate bar that consists of some chunks. Each chunk has its own sweetness given by the array sweetness.\n\nYou want to share the chocolate with your k friends so you need to cut the chocolate bar into k + 1 pieces using k cuts, each piece consists of some consecutive chunks.\n\nBeing generous, you will eat the piece with the minimum total sweetness and give the other pieces to your friends.\n\nFind the maximum total sweetness of the piece you can get by cutting the chocolate bar optimally.', constraints: '0 <= k <= sweetness.length - 1\n1 <= sweetness.length <= 10^4\n1 <= sweetness[i] <= 10^5' },
    { id: 203, description: 'You are given an integer array bloomDay, an integer m and an integer k. You want to make m bouquets. To make a bouquet, you need to use k adjacent flowers from the garden.\n\nThe garden consists of n flowers, the ith flower will bloom in the bloomDay[i] and then can be used in exactly one bouquet.\n\nReturn the minimum number of days you need to wait to be able to make m bouquets from the garden. If it is impossible to make m bouquets return -1.', constraints: 'bloomDay.length == n\n1 <= n <= 10^5\n1 <= bloomDay[i] <= 10^9\n1 <= m <= 10^6\n1 <= k <= n' },
    { id: 204, description: 'In the universe Earth C-137, Rick discovered a special form of magnetic force between two balls. Place m balls in n positions (given as an array position sorted in ascending order), and maximize the minimum magnetic force between any two balls.', constraints: 'n == position.length\n2 <= n <= 10^5\n1 <= position[i] <= 10^9\nAll integers in position are distinct.\n2 <= m <= position.length' },
    { id: 205, description: 'You are given n gas stations along a circular route. Minimize the maximum distance between adjacent stations after adding k new stations.', constraints: '2 <= stations.length <= 10\n0 <= stations[i] <= 10^8\n1 <= k <= 10^6' },
    { id: 206, description: 'You are given an array of intervals, where intervals[i] = [starti, endi] and each starti is unique. The right interval for an interval i is an interval j such that startj >= endi and startj is minimized. Note that i may equal j. Return an array of right interval indices for each interval. If no right interval exists for interval i, then put -1 at index i.', constraints: '1 <= intervals.length <= 2 * 10^4\nintervals[i].length == 2\n-10^6 <= starti <= endi <= 10^6\nThe start point of each interval is unique.' },
    { id: 207, description: 'You are given a 2D array of integers envelopes where envelopes[i] = [wi, hi] represents the width and the height of an envelope.\n\nOne envelope can fit into another if and only if both the width and height of one envelope are greater than the other envelope width and height.\n\nReturn the maximum number of envelopes you can Russian doll (i.e., put one inside the other).', constraints: '1 <= envelopes.length <= 10^5\nenvelopes[i].length == 2\n1 <= wi, hi <= 10^5' },
    { id: 208, description: 'Given an integer array nums, return the length of the longest strictly increasing subsequence.', constraints: '1 <= nums.length <= 2500\n-10^4 <= nums[i] <= 10^4' },
    { id: 209, description: 'Given an integer array nums, return an integer array counts where counts[i] is the number of smaller elements to the right of nums[i].', constraints: '1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4' },
    { id: 210, description: 'Given an integer array nums and two integers lower and upper, return the number of range sums that lie in [lower, upper] inclusive.\n\nRange sum S(i, j) is defined as the sum of the elements in nums between indices i and j inclusive, where i <= j.', constraints: '1 <= nums.length <= 10^5\n-2^31 <= nums[i] <= 2^31 - 1\n-10^5 <= lower <= upper <= 10^5' },
    { id: 211, description: 'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.\n\nThe overall run time complexity should be O(log (m+n)).', constraints: 'nums1.length == m\nnums2.length == n\n0 <= m <= 1000\n0 <= n <= 1000\n1 <= m + n <= 2000\n-10^6 <= nums1[i], nums2[i] <= 10^6' },
    { id: 212, description: 'The median is the middle value in an ordered integer list. If the size of the list is even, there is no middle value, and the median is the mean of the two middle values.\n\nImplement the MedianFinder class:\n- MedianFinder() initializes the MedianFinder object.\n- void addNum(int num) adds the integer number from the data stream to the data structure.\n- double findMedian() returns the median of all elements so far.', constraints: '-10^5 <= num <= 10^5\nThere will be at least one element in the data structure before calling findMedian.\nAt most 5 * 10^4 calls will be made to addNum and findMedian.' },
    { id: 213, description: 'Given the root of a complete binary tree, return the number of the nodes in the tree.\n\nDesign an algorithm that runs in less than O(n) time complexity.', constraints: '0 <= number of nodes <= 5 * 10^4\n0 <= Node.val <= 5 * 10^4\nThe tree is guaranteed to be complete.' },
    { id: 214, description: 'Implement pow(x, n), which calculates x raised to the power n (i.e., x^n).', constraints: '-100.0 < x < 100.0\n-2^31 <= n <= 2^31 - 1\nn is an integer.\nEither x is not zero or n > 0.\n-10^4 <= x^n <= 10^4' },
    { id: 215, description: 'Given two integers dividend and divisor, divide two integers without using multiplication, division, and mod operator.\n\nThe integer division should truncate toward zero. You may assume that the environment could only store integers within the 32-bit signed integer range: [-2^31, 2^31 - 1].', constraints: '-2^31 <= dividend, divisor <= 2^31 - 1\ndivisor != 0' },
];

async function run() {
    console.log('Batch 3: Updating ' + updates.length + ' problems...');
    let ok = 0, fail = 0;
    for (const u of updates) {
        const { error } = await supabaseAdmin.from('problems').update({
            description: u.description, constraints: u.constraints
        }).eq('id', u.id);
        if (error) { console.error('FAIL [' + u.id + ']: ' + error.message); fail++; }
        else { ok++; }
    }
    console.log('Batch 3 done: ' + ok + ' ok, ' + fail + ' fail');
}
run().catch(console.error);
