import { supabaseAdmin } from '../db/supabaseClient.js';

// Batch 1: Multi-language solutions for problems 25-116
const solutions = {
    25: { // Pascal's Triangle
        javascript: `function generate(numRows) {\n    const result = [];\n    for (let i = 0; i < numRows; i++) {\n        const row = new Array(i + 1).fill(1);\n        for (let j = 1; j < i; j++) row[j] = result[i-1][j-1] + result[i-1][j];\n        result.push(row);\n    }\n    return result;\n}`,
        java: `class Solution {\n    public List<List<Integer>> generate(int numRows) {\n        List<List<Integer>> result = new ArrayList<>();\n        for (int i = 0; i < numRows; i++) {\n            List<Integer> row = new ArrayList<>();\n            for (int j = 0; j <= i; j++) {\n                if (j == 0 || j == i) row.add(1);\n                else row.add(result.get(i-1).get(j-1) + result.get(i-1).get(j));\n            }\n            result.add(row);\n        }\n        return result;\n    }\n}`,
        cpp: `class Solution {\npublic:\n    vector<vector<int>> generate(int numRows) {\n        vector<vector<int>> result;\n        for (int i = 0; i < numRows; i++) {\n            vector<int> row(i + 1, 1);\n            for (int j = 1; j < i; j++) row[j] = result[i-1][j-1] + result[i-1][j];\n            result.push_back(row);\n        }\n        return result;\n    }\n};`
    },
    28: { // Majority Element II
        javascript: `function majorityElement(nums) {\n    let c1 = 0, c2 = 0, n1 = 0, n2 = 1;\n    for (const n of nums) {\n        if (n === n1) c1++;\n        else if (n === n2) c2++;\n        else if (c1 === 0) { n1 = n; c1 = 1; }\n        else if (c2 === 0) { n2 = n; c2 = 1; }\n        else { c1--; c2--; }\n    }\n    return [n1, n2].filter(x => nums.filter(n => n === x).length > nums.length / 3);\n}`,
        java: `class Solution {\n    public List<Integer> majorityElement(int[] nums) {\n        int c1 = 0, c2 = 0, n1 = 0, n2 = 1;\n        for (int n : nums) {\n            if (n == n1) c1++;\n            else if (n == n2) c2++;\n            else if (c1 == 0) { n1 = n; c1 = 1; }\n            else if (c2 == 0) { n2 = n; c2 = 1; }\n            else { c1--; c2--; }\n        }\n        c1 = c2 = 0;\n        for (int n : nums) { if (n == n1) c1++; else if (n == n2) c2++; }\n        List<Integer> res = new ArrayList<>();\n        if (c1 > nums.length / 3) res.add(n1);\n        if (c2 > nums.length / 3) res.add(n2);\n        return res;\n    }\n}`,
        cpp: `class Solution {\npublic:\n    vector<int> majorityElement(vector<int>& nums) {\n        int c1=0,c2=0,n1=0,n2=1;\n        for(int n:nums){if(n==n1)c1++;else if(n==n2)c2++;else if(c1==0){n1=n;c1=1;}else if(c2==0){n2=n;c2=1;}else{c1--;c2--;}}\n        c1=c2=0;\n        for(int n:nums){if(n==n1)c1++;else if(n==n2)c2++;}\n        vector<int> res;\n        if(c1>nums.size()/3)res.push_back(n1);\n        if(c2>nums.size()/3)res.push_back(n2);\n        return res;\n    }\n};`
    },
    34: { // Find First and Last Position
        javascript: `function searchRange(nums, target) {\n    const find = (t) => { let lo=0,hi=nums.length; while(lo<hi){const m=lo+((hi-lo)>>1);if(nums[m]<t)lo=m+1;else hi=m;} return lo; };\n    const lo = find(target);\n    if (lo === nums.length || nums[lo] !== target) return [-1,-1];\n    return [lo, find(target+1)-1];\n}`,
        java: `class Solution {\n    public int[] searchRange(int[] nums, int target) {\n        int lo = find(nums, target), hi = find(nums, target+1)-1;\n        if (lo == nums.length || nums[lo] != target) return new int[]{-1,-1};\n        return new int[]{lo, hi};\n    }\n    int find(int[] nums, int t) {\n        int lo=0,hi=nums.length;\n        while(lo<hi){int m=lo+(hi-lo)/2;if(nums[m]<t)lo=m+1;else hi=m;}\n        return lo;\n    }\n}`,
        cpp: `class Solution {\npublic:\n    vector<int> searchRange(vector<int>& nums, int target) {\n        int lo = lower_bound(nums.begin(),nums.end(),target)-nums.begin();\n        if(lo==nums.size()||nums[lo]!=target) return {-1,-1};\n        int hi = upper_bound(nums.begin(),nums.end(),target)-nums.begin()-1;\n        return {lo,hi};\n    }\n};`
    },
    44: { // Find All Numbers Disappeared
        javascript: `function findDisappearedNumbers(nums) {\n    for (const n of nums) { const i = Math.abs(n)-1; if(nums[i]>0) nums[i]=-nums[i]; }\n    const res = []; for(let i=0;i<nums.length;i++) if(nums[i]>0) res.push(i+1);\n    return res;\n}`,
        java: `class Solution {\n    public List<Integer> findDisappearedNumbers(int[] nums) {\n        for(int n:nums){int i=Math.abs(n)-1;if(nums[i]>0)nums[i]=-nums[i];}\n        List<Integer> res=new ArrayList<>();\n        for(int i=0;i<nums.length;i++) if(nums[i]>0) res.add(i+1);\n        return res;\n    }\n}`,
        cpp: `class Solution {\npublic:\n    vector<int> findDisappearedNumbers(vector<int>& nums) {\n        for(int n:nums){int i=abs(n)-1;if(nums[i]>0)nums[i]=-nums[i];}\n        vector<int> res;\n        for(int i=0;i<nums.size();i++) if(nums[i]>0) res.push_back(i+1);\n        return res;\n    }\n};`
    },
    53: { // Valid Palindrome II
        javascript: `function validPalindrome(s) {\n    const isPalin=(s,l,r)=>{while(l<r)if(s[l++]!==s[r--])return false;return true;};\n    let l=0,r=s.length-1;\n    while(l<r){if(s[l]!==s[r])return isPalin(s,l+1,r)||isPalin(s,l,r-1);l++;r--;}\n    return true;\n}`,
        java: `class Solution {\n    public boolean validPalindrome(String s) {\n        int l=0,r=s.length()-1;\n        while(l<r){if(s.charAt(l)!=s.charAt(r))return check(s,l+1,r)||check(s,l,r-1);l++;r--;}\n        return true;\n    }\n    boolean check(String s,int l,int r){while(l<r)if(s.charAt(l++)!=s.charAt(r--))return false;return true;}\n}`,
        cpp: `class Solution {\npublic:\n    bool validPalindrome(string s) {\n        int l=0,r=s.size()-1;\n        while(l<r){if(s[l]!=s[r])return check(s,l+1,r)||check(s,l,r-1);l++;r--;}\n        return true;\n    }\n    bool check(string&s,int l,int r){while(l<r)if(s[l++]!=s[r--])return false;return true;}\n};`
    },
    54: { // Two Sum II
        javascript: `function twoSum(numbers, target) {\n    let l=0,r=numbers.length-1;\n    while(l<r){const s=numbers[l]+numbers[r];if(s===target)return[l+1,r+1];if(s<target)l++;else r--;}\n}`,
        java: `class Solution {\n    public int[] twoSum(int[] numbers, int target) {\n        int l=0,r=numbers.length-1;\n        while(l<r){int s=numbers[l]+numbers[r];if(s==target)return new int[]{l+1,r+1};if(s<target)l++;else r--;}\n        return new int[]{};\n    }\n}`,
        cpp: `class Solution {\npublic:\n    vector<int> twoSum(vector<int>& numbers, int target) {\n        int l=0,r=numbers.size()-1;\n        while(l<r){int s=numbers[l]+numbers[r];if(s==target)return{l+1,r+1};if(s<target)l++;else r--;}\n        return{};\n    }\n};`
    },
    55: { // 3Sum Closest
        javascript: `function threeSumClosest(nums, target) {\n    nums.sort((a,b)=>a-b); let closest=Infinity;\n    for(let i=0;i<nums.length-2;i++){let l=i+1,r=nums.length-1;\n        while(l<r){const s=nums[i]+nums[l]+nums[r];if(Math.abs(s-target)<Math.abs(closest-target))closest=s;if(s<target)l++;else r--;}\n    } return closest;\n}`,
        java: `class Solution {\n    public int threeSumClosest(int[] nums, int target) {\n        Arrays.sort(nums); int closest=nums[0]+nums[1]+nums[2];\n        for(int i=0;i<nums.length-2;i++){int l=i+1,r=nums.length-1;\n            while(l<r){int s=nums[i]+nums[l]+nums[r];if(Math.abs(s-target)<Math.abs(closest-target))closest=s;if(s<target)l++;else r--;}}\n        return closest;\n    }\n}`,
        cpp: `class Solution {\npublic:\n    int threeSumClosest(vector<int>& nums, int target) {\n        sort(nums.begin(),nums.end()); int closest=nums[0]+nums[1]+nums[2];\n        for(int i=0;i<nums.size()-2;i++){int l=i+1,r=nums.size()-1;\n            while(l<r){int s=nums[i]+nums[l]+nums[r];if(abs(s-target)<abs(closest-target))closest=s;if(s<target)l++;else r--;}}\n        return closest;\n    }\n};`
    },
    56: { // Remove Duplicates from Sorted Array II
        javascript: `function removeDuplicates(nums) {\n    let k=0;\n    for(const n of nums) if(k<2||n!==nums[k-2]) nums[k++]=n;\n    return k;\n}`,
        java: `class Solution {\n    public int removeDuplicates(int[] nums) {\n        int k=0;\n        for(int n:nums) if(k<2||n!=nums[k-2]) nums[k++]=n;\n        return k;\n    }\n}`,
        cpp: `class Solution {\npublic:\n    int removeDuplicates(vector<int>& nums) {\n        int k=0;\n        for(int n:nums) if(k<2||n!=nums[k-2]) nums[k++]=n;\n        return k;\n    }\n};`
    },
    58: { // Remove Duplicates from Sorted List II
        javascript: `function deleteDuplicates(head) {\n    const dummy={val:0,next:head}; let prev=dummy;\n    while(prev.next){let curr=prev.next;\n        if(curr.next&&curr.val===curr.next.val){while(curr.next&&curr.val===curr.next.val)curr=curr.next;prev.next=curr.next;}else prev=prev.next;}\n    return dummy.next;\n}`,
        java: `class Solution {\n    public ListNode deleteDuplicates(ListNode head) {\n        ListNode dummy=new ListNode(0,head),prev=dummy;\n        while(prev.next!=null){ListNode curr=prev.next;\n            if(curr.next!=null&&curr.val==curr.next.val){while(curr.next!=null&&curr.val==curr.next.val)curr=curr.next;prev.next=curr.next;}else prev=prev.next;}\n        return dummy.next;\n    }\n}`,
        cpp: `class Solution {\npublic:\n    ListNode* deleteDuplicates(ListNode* head) {\n        ListNode dummy(0,head); auto prev=&dummy;\n        while(prev->next){auto curr=prev->next;\n            if(curr->next&&curr->val==curr->next->val){while(curr->next&&curr->val==curr->next->val)curr=curr->next;prev->next=curr->next;}else prev=prev->next;}\n        return dummy.next;\n    }\n};`
    },
    61: { javascript: `function reverseString(s) { let l=0,r=s.length-1; while(l<r){[s[l],s[r]]=[s[r],s[l]];l++;r--;} }`, java: `class Solution { public void reverseString(char[] s) { int l=0,r=s.length-1; while(l<r){char t=s[l];s[l]=s[r];s[r]=t;l++;r--;} } }`, cpp: `class Solution { public: void reverseString(vector<char>& s) { int l=0,r=s.size()-1; while(l<r) swap(s[l++],s[r--]); } };` },
    63: { javascript: `function reverseWords(s) { return s.trim().split(/\\s+/).reverse().join(' '); }`, java: `class Solution { public String reverseWords(String s) { String[] w=s.trim().split("\\\\s+"); Collections.reverse(Arrays.asList(w)); return String.join(" ",w); } }`, cpp: `class Solution { public: string reverseWords(string s) { istringstream iss(s); vector<string> w; string t; while(iss>>t) w.push_back(t); reverse(w.begin(),w.end()); string res; for(int i=0;i<w.size();i++){if(i)res+=" ";res+=w[i];} return res; } };` },
    65: { javascript: `function isSubsequence(s, t) { let i=0; for(const c of t) if(i<s.length&&c===s[i]) i++; return i===s.length; }`, java: `class Solution { public boolean isSubsequence(String s, String t) { int i=0; for(int j=0;j<t.length()&&i<s.length();j++) if(t.charAt(j)==s.charAt(i)) i++; return i==s.length(); } }`, cpp: `class Solution { public: bool isSubsequence(string s, string t) { int i=0; for(char c:t) if(i<s.size()&&c==s[i]) i++; return i==s.size(); } };` },
    66: { javascript: `function numSubseq(nums, target) { nums.sort((a,b)=>a-b); const MOD=1e9+7; let res=0,l=0,r=nums.length-1; const pow=[1]; for(let i=1;i<nums.length;i++) pow.push(pow[i-1]*2%MOD); while(l<=r){ if(nums[l]+nums[r]<=target){res=(res+pow[r-l])%MOD;l++;}else r--;} return res; }`, java: `class Solution { public int numSubseq(int[] nums, int target) { Arrays.sort(nums); int MOD=1000000007,n=nums.length; long[] pow=new long[n]; pow[0]=1; for(int i=1;i<n;i++) pow[i]=pow[i-1]*2%MOD; int res=0,l=0,r=n-1; while(l<=r){if(nums[l]+nums[r]<=target){res=(int)((res+pow[r-l])%MOD);l++;}else r--;} return res; } }`, cpp: `class Solution { public: int numSubseq(vector<int>& nums, int target) { sort(nums.begin(),nums.end()); int MOD=1e9+7,n=nums.size(); vector<long> pw(n,1); for(int i=1;i<n;i++) pw[i]=pw[i-1]*2%MOD; int res=0,l=0,r=n-1; while(l<=r){if(nums[l]+nums[r]<=target){res=(res+pw[r-l])%MOD;l++;}else r--;} return res; } };` },
    69: { javascript: `function sortTransformedArray(nums, a, b, c) { const f=x=>a*x*x+b*x+c; let l=0,r=nums.length-1; const res=[]; while(l<=r){ if(a>0){if(f(nums[l])>f(nums[r]))res.push(f(nums[l++]));else res.push(f(nums[r--]));}else{if(f(nums[l])<f(nums[r]))res.push(f(nums[l++]));else res.push(f(nums[r--]));}} return a>=0?res.reverse():res; }`, java: `class Solution { public int[] sortTransformedArray(int[] nums, int a, int b, int c) { int n=nums.length,l=0,r=n-1,idx=a>=0?n-1:0; int[] res=new int[n]; while(l<=r){int vl=f(nums[l],a,b,c),vr=f(nums[r],a,b,c); if(a>=0){if(vl>vr){res[idx--]=vl;l++;}else{res[idx--]=vr;r--;}}else{if(vl<vr){res[idx++]=vl;l++;}else{res[idx++]=vr;r--;}}} return res; } int f(int x,int a,int b,int c){return a*x*x+b*x+c;} }`, cpp: `class Solution { public: vector<int> sortTransformedArray(vector<int>& nums, int a, int b, int c) { auto f=[&](int x){return a*x*x+b*x+c;}; int n=nums.size(),l=0,r=n-1,idx=a>=0?n-1:0; vector<int> res(n); while(l<=r){int vl=f(nums[l]),vr=f(nums[r]); if(a>=0){if(vl>vr){res[idx--]=vl;l++;}else{res[idx--]=vr;r--;}}else{if(vl<vr){res[idx++]=vl;l++;}else{res[idx++]=vr;r--;}}} return res; } };` },
    70: { javascript: `function trap(height) { let l=0,r=height.length-1,lMax=0,rMax=0,res=0; while(l<r){if(height[l]<height[r]){lMax=Math.max(lMax,height[l]);res+=lMax-height[l];l++;}else{rMax=Math.max(rMax,height[r]);res+=rMax-height[r];r--;}} return res; }`, java: `class Solution { public int trap(int[] h) { int l=0,r=h.length-1,lm=0,rm=0,res=0; while(l<r){if(h[l]<h[r]){lm=Math.max(lm,h[l]);res+=lm-h[l];l++;}else{rm=Math.max(rm,h[r]);res+=rm-h[r];r--;}} return res; } }`, cpp: `class Solution { public: int trap(vector<int>& h) { int l=0,r=h.size()-1,lm=0,rm=0,res=0; while(l<r){if(h[l]<h[r]){lm=max(lm,h[l]);res+=lm-h[l++];}else{rm=max(rm,h[r]);res+=rm-h[r--];}} return res; } };` },
    72: { javascript: `function numRescueBoats(people, limit) { people.sort((a,b)=>a-b); let l=0,r=people.length-1,boats=0; while(l<=r){if(people[l]+people[r]<=limit)l++;r--;boats++;} return boats; }`, java: `class Solution { public int numRescueBoats(int[] p, int limit) { Arrays.sort(p); int l=0,r=p.length-1,b=0; while(l<=r){if(p[l]+p[r]<=limit)l++;r--;b++;} return b; } }`, cpp: `class Solution { public: int numRescueBoats(vector<int>& p, int limit) { sort(p.begin(),p.end()); int l=0,r=p.size()-1,b=0; while(l<=r){if(p[l]+p[r]<=limit)l++;r--;b++;} return b; } };` },
    73: { javascript: `function minPairSum(nums) { nums.sort((a,b)=>a-b); let max=0; for(let i=0;i<nums.length/2;i++) max=Math.max(max,nums[i]+nums[nums.length-1-i]); return max; }`, java: `class Solution { public int minPairSum(int[] nums) { Arrays.sort(nums); int max=0; for(int i=0;i<nums.length/2;i++) max=Math.max(max,nums[i]+nums[nums.length-1-i]); return max; } }`, cpp: `class Solution { public: int minPairSum(vector<int>& nums) { sort(nums.begin(),nums.end()); int mx=0; for(int i=0;i<nums.size()/2;i++) mx=max(mx,nums[i]+nums[nums.size()-1-i]); return mx; } };` },
    75: { javascript: `function intersection(nums1, nums2) { const s=new Set(nums1); return [...new Set(nums2.filter(n=>s.has(n)))]; }`, java: `class Solution { public int[] intersection(int[] n1, int[] n2) { Set<Integer> s=new HashSet<>(); for(int n:n1) s.add(n); Set<Integer> r=new HashSet<>(); for(int n:n2) if(s.contains(n)) r.add(n); return r.stream().mapToInt(Integer::intValue).toArray(); } }`, cpp: `class Solution { public: vector<int> intersection(vector<int>& n1, vector<int>& n2) { set<int> s(n1.begin(),n1.end()),r; for(int n:n2) if(s.count(n)) r.insert(n); return vector<int>(r.begin(),r.end()); } };` },
    76: { javascript: `function intersect(nums1, nums2) { const m={}; for(const n of nums1) m[n]=(m[n]||0)+1; const r=[]; for(const n of nums2) if(m[n]>0){r.push(n);m[n]--;} return r; }`, java: `class Solution { public int[] intersect(int[] n1, int[] n2) { Map<Integer,Integer> m=new HashMap<>(); for(int n:n1) m.merge(n,1,Integer::sum); List<Integer> r=new ArrayList<>(); for(int n:n2) if(m.getOrDefault(n,0)>0){r.add(n);m.merge(n,-1,Integer::sum);} return r.stream().mapToInt(Integer::intValue).toArray(); } }`, cpp: `class Solution { public: vector<int> intersect(vector<int>& n1, vector<int>& n2) { unordered_map<int,int> m; for(int n:n1) m[n]++; vector<int> r; for(int n:n2) if(m[n]>0){r.push_back(n);m[n]--;} return r; } };` },
    80: { javascript: `function middleNode(head) { let s=head,f=head; while(f&&f.next){s=s.next;f=f.next.next;} return s; }`, java: `class Solution { public ListNode middleNode(ListNode head) { ListNode s=head,f=head; while(f!=null&&f.next!=null){s=s.next;f=f.next.next;} return s; } }`, cpp: `class Solution { public: ListNode* middleNode(ListNode* head) { auto s=head,f=head; while(f&&f->next){s=s->next;f=f->next->next;} return s; } };` },
    81: { javascript: `function isPalindrome(head) { let s=head,f=head; while(f&&f.next){s=s.next;f=f.next.next;} let prev=null; while(s){const t=s.next;s.next=prev;prev=s;s=t;} while(prev){if(prev.val!==head.val)return false;prev=prev.next;head=head.next;} return true; }`, java: `class Solution { public boolean isPalindrome(ListNode head) { ListNode s=head,f=head; while(f!=null&&f.next!=null){s=s.next;f=f.next.next;} ListNode prev=null; while(s!=null){ListNode t=s.next;s.next=prev;prev=s;s=t;} while(prev!=null){if(prev.val!=head.val)return false;prev=prev.next;head=head.next;} return true; } }`, cpp: `class Solution { public: bool isPalindrome(ListNode* head) { auto s=head,f=head; while(f&&f->next){s=s->next;f=f->next->next;} ListNode* prev=nullptr; while(s){auto t=s->next;s->next=prev;prev=s;s=t;} while(prev){if(prev->val!=head->val)return false;prev=prev->next;head=head->next;} return true; } };` },
    86: { javascript: `function partitionLabels(s) { const last={}; for(let i=0;i<s.length;i++) last[s[i]]=i; const res=[]; let start=0,end=0; for(let i=0;i<s.length;i++){end=Math.max(end,last[s[i]]);if(i===end){res.push(end-start+1);start=end+1;}} return res; }`, java: `class Solution { public List<Integer> partitionLabels(String s) { int[] last=new int[26]; for(int i=0;i<s.length();i++) last[s.charAt(i)-'a']=i; List<Integer> res=new ArrayList<>(); int start=0,end=0; for(int i=0;i<s.length();i++){end=Math.max(end,last[s.charAt(i)-'a']);if(i==end){res.add(end-start+1);start=end+1;}} return res; } }`, cpp: `class Solution { public: vector<int> partitionLabels(string s) { int last[26]={}; for(int i=0;i<s.size();i++) last[s[i]-'a']=i; vector<int> res; int start=0,end=0; for(int i=0;i<s.size();i++){end=max(end,last[s[i]-'a']);if(i==end){res.push_back(end-start+1);start=end+1;}} return res; } };` },
    90: { javascript: `function maxSlidingWindow(nums, k) { const dq=[],res=[]; for(let i=0;i<nums.length;i++){while(dq.length&&dq[0]<=i-k)dq.shift();while(dq.length&&nums[dq[dq.length-1]]<=nums[i])dq.pop();dq.push(i);if(i>=k-1)res.push(nums[dq[0]]);} return res; }`, java: `class Solution { public int[] maxSlidingWindow(int[] nums, int k) { Deque<Integer> dq=new ArrayDeque<>(); int[] res=new int[nums.length-k+1]; for(int i=0;i<nums.length;i++){while(!dq.isEmpty()&&dq.peek()<=i-k)dq.poll();while(!dq.isEmpty()&&nums[dq.peekLast()]<=nums[i])dq.pollLast();dq.offer(i);if(i>=k-1)res[i-k+1]=nums[dq.peek();} return res; } }`, cpp: `class Solution { public: vector<int> maxSlidingWindow(vector<int>& nums, int k) { deque<int> dq; vector<int> res; for(int i=0;i<nums.size();i++){while(!dq.empty()&&dq.front()<=i-k)dq.pop_front();while(!dq.empty()&&nums[dq.back()]<=nums[i])dq.pop_back();dq.push_back(i);if(i>=k-1)res.push_back(nums[dq.front()]);} return res; } };` },
    91: { javascript: `function checkInclusion(s1, s2) { const c=new Array(26).fill(0); for(const ch of s1) c[ch.charCodeAt(0)-97]++; let l=0,cnt=s1.length; for(let r=0;r<s2.length;r++){if(c[s2.charCodeAt(r)-97]-->0)cnt--;while(cnt===0){if(r-l+1===s1.length)return true;if(c[s2.charCodeAt(l)-97]++>=0)cnt++;l++;}} return false; }`, java: `class Solution { public boolean checkInclusion(String s1, String s2) { int[] c=new int[26]; for(char ch:s1.toCharArray()) c[ch-'a']++; int l=0,cnt=s1.length(); for(int r=0;r<s2.length();r++){if(c[s2.charAt(r)-'a']-->0)cnt--;while(cnt==0){if(r-l+1==s1.length())return true;if(c[s2.charAt(l)-'a']++>=0)cnt++;l++;}} return false; } }`, cpp: `class Solution { public: bool checkInclusion(string s1, string s2) { int c[26]={},cnt=s1.size(),l=0; for(char ch:s1) c[ch-'a']++; for(int r=0;r<s2.size();r++){if(c[s2[r]-'a']-->0)cnt--;while(cnt==0){if(r-l+1==(int)s1.size())return true;if(c[s2[l]-'a']++>=0)cnt++;l++;}} return false; } };` },
    92: { javascript: `function findAnagrams(s, p) { const c=new Array(26).fill(0); for(const ch of p) c[ch.charCodeAt(0)-97]++; let l=0,cnt=p.length; const res=[]; for(let r=0;r<s.length;r++){if(c[s.charCodeAt(r)-97]-->0)cnt--;if(cnt===0)res.push(l);if(r-l+1>=p.length){if(c[s.charCodeAt(l)-97]++>=0)cnt++;l++;}} return res; }`, java: `class Solution { public List<Integer> findAnagrams(String s, String p) { int[] c=new int[26]; for(char ch:p.toCharArray()) c[ch-'a']++; int l=0,cnt=p.length(); List<Integer> res=new ArrayList<>(); for(int r=0;r<s.length();r++){if(c[s.charAt(r)-'a']-->0)cnt--;if(cnt==0)res.add(l);if(r-l+1>=p.length()){if(c[s.charAt(l)-'a']++>=0)cnt++;l++;}} return res; } }`, cpp: `class Solution { public: vector<int> findAnagrams(string s, string p) { int c[26]={},cnt=p.size(),l=0; for(char ch:p) c[ch-'a']++; vector<int> res; for(int r=0;r<s.size();r++){if(c[s[r]-'a']-->0)cnt--;if(cnt==0)res.push_back(l);if(r-l+1>=(int)p.size()){if(c[s[l]-'a']++>=0)cnt++;l++;}} return res; } };` },
    96: { javascript: `function totalFruit(fruits) { const m={}; let l=0,res=0; for(let r=0;r<fruits.length;r++){m[fruits[r]]=(m[fruits[r]]||0)+1;while(Object.keys(m).length>2){m[fruits[l]]--;if(m[fruits[l]]===0)delete m[fruits[l]];l++;}res=Math.max(res,r-l+1);} return res; }`, java: `class Solution { public int totalFruit(int[] f) { Map<Integer,Integer> m=new HashMap<>(); int l=0,res=0; for(int r=0;r<f.length;r++){m.merge(f[r],1,Integer::sum);while(m.size()>2){m.merge(f[l],-1,Integer::sum);if(m.get(f[l])==0)m.remove(f[l]);l++;}res=Math.max(res,r-l+1);} return res; } }`, cpp: `class Solution { public: int totalFruit(vector<int>& f) { unordered_map<int,int> m; int l=0,res=0; for(int r=0;r<f.size();r++){m[f[r]]++;while(m.size()>2){if(--m[f[l]]==0)m.erase(f[l]);l++;}res=max(res,r-l+1);} return res; } };` },
    97: { javascript: `function longestOnes(nums, k) { let l=0,res=0; for(let r=0;r<nums.length;r++){if(nums[r]===0)k--;while(k<0){if(nums[l]===0)k++;l++;}res=Math.max(res,r-l+1);} return res; }`, java: `class Solution { public int longestOnes(int[] nums, int k) { int l=0,res=0; for(int r=0;r<nums.length;r++){if(nums[r]==0)k--;while(k<0){if(nums[l]==0)k++;l++;}res=Math.max(res,r-l+1);} return res; } }`, cpp: `class Solution { public: int longestOnes(vector<int>& nums, int k) { int l=0,res=0; for(int r=0;r<nums.size();r++){if(nums[r]==0)k--;while(k<0){if(nums[l]==0)k++;l++;}res=max(res,r-l+1);} return res; } };` },
};

async function run() {
    console.log('Adding multi-language solutions - Batch 1...\n');
    let updated = 0, failed = 0;
    for (const [id, langSolutions] of Object.entries(solutions)) {
        const { data: problem } = await supabaseAdmin.from('problems').select('solution_code').eq('id', parseInt(id)).single();
        if (!problem) { console.log(`  Problem #${id} not found`); continue; }
        const merged = { ...(problem.solution_code || {}), ...langSolutions };
        const { error } = await supabaseAdmin.from('problems').update({ solution_code: merged }).eq('id', parseInt(id));
        if (error) { console.error(`  ❌ #${id}: ${error.message}`); failed++; }
        else { updated++; }
    }
    console.log(`Done: ${updated} updated, ${failed} failed`);
}
run();
