import { supabaseAdmin } from '../db/supabaseClient.js';
const S = {
    // Trees
    224: { javascript: `function invertTree(root) { if(!root)return null; [root.left,root.right]=[invertTree(root.right),invertTree(root.left)]; return root; }`, java: `class Solution { public TreeNode invertTree(TreeNode root) { if(root==null)return null; TreeNode t=root.left; root.left=invertTree(root.right); root.right=invertTree(t); return root; } }`, cpp: `class Solution { public: TreeNode* invertTree(TreeNode* root) { if(!root)return nullptr; swap(root->left,root->right); invertTree(root->left); invertTree(root->right); return root; } };` },
    225: { javascript: `function diameterOfBinaryTree(root) { let d=0; const h=(n)=>{if(!n)return 0;const l=h(n.left),r=h(n.right);d=Math.max(d,l+r);return 1+Math.max(l,r);}; h(root); return d; }`, java: `class Solution { int d=0; public int diameterOfBinaryTree(TreeNode root) { h(root); return d; } int h(TreeNode n){if(n==null)return 0;int l=h(n.left),r=h(n.right);d=Math.max(d,l+r);return 1+Math.max(l,r);} }`, cpp: `class Solution { int d=0; public: int diameterOfBinaryTree(TreeNode* root) { h(root); return d; } int h(TreeNode* n){if(!n)return 0;int l=h(n->left),r=h(n->right);d=max(d,l+r);return 1+max(l,r);} };` },
    227: { javascript: `function isSameTree(p,q) { if(!p&&!q)return true; if(!p||!q||p.val!==q.val)return false; return isSameTree(p.left,q.left)&&isSameTree(p.right,q.right); }`, java: `class Solution { public boolean isSameTree(TreeNode p, TreeNode q) { if(p==null&&q==null)return true; if(p==null||q==null||p.val!=q.val)return false; return isSameTree(p.left,q.left)&&isSameTree(p.right,q.right); } }`, cpp: `class Solution { public: bool isSameTree(TreeNode* p, TreeNode* q) { if(!p&&!q)return true; if(!p||!q||p->val!=q->val)return false; return isSameTree(p->left,q->left)&&isSameTree(p->right,q->right); } };` },
    229: { javascript: `function isSubtree(root,subRoot) { if(!root)return false; if(isSame(root,subRoot))return true; return isSubtree(root.left,subRoot)||isSubtree(root.right,subRoot); function isSame(a,b){if(!a&&!b)return true;if(!a||!b||a.val!==b.val)return false;return isSame(a.left,b.left)&&isSame(a.right,b.right);} }`, java: `class Solution { public boolean isSubtree(TreeNode r, TreeNode s) { if(r==null)return false; if(isSame(r,s))return true; return isSubtree(r.left,s)||isSubtree(r.right,s); } boolean isSame(TreeNode a,TreeNode b){if(a==null&&b==null)return true;if(a==null||b==null||a.val!=b.val)return false;return isSame(a.left,b.left)&&isSame(a.right,b.right);} }`, cpp: `class Solution { public: bool isSubtree(TreeNode* r, TreeNode* s) { if(!r)return false; if(isSame(r,s))return true; return isSubtree(r->left,s)||isSubtree(r->right,s); } bool isSame(TreeNode*a,TreeNode*b){if(!a&&!b)return true;if(!a||!b||a->val!=b->val)return false;return isSame(a->left,b->left)&&isSame(a->right,b->right);} };` },
    230: { javascript: `function mergeTrees(t1,t2) { if(!t1)return t2; if(!t2)return t1; t1.val+=t2.val; t1.left=mergeTrees(t1.left,t2.left); t1.right=mergeTrees(t1.right,t2.right); return t1; }`, java: `class Solution { public TreeNode mergeTrees(TreeNode t1, TreeNode t2) { if(t1==null)return t2; if(t2==null)return t1; t1.val+=t2.val; t1.left=mergeTrees(t1.left,t2.left); t1.right=mergeTrees(t1.right,t2.right); return t1; } }`, cpp: `class Solution { public: TreeNode* mergeTrees(TreeNode* t1, TreeNode* t2) { if(!t1)return t2; if(!t2)return t1; t1->val+=t2->val; t1->left=mergeTrees(t1->left,t2->left); t1->right=mergeTrees(t1->right,t2->right); return t1; } };` },
    232: { javascript: `function hasPathSum(root,targetSum) { if(!root)return false; if(!root.left&&!root.right)return root.val===targetSum; return hasPathSum(root.left,targetSum-root.val)||hasPathSum(root.right,targetSum-root.val); }`, java: `class Solution { public boolean hasPathSum(TreeNode root, int t) { if(root==null)return false; if(root.left==null&&root.right==null)return root.val==t; return hasPathSum(root.left,t-root.val)||hasPathSum(root.right,t-root.val); } }`, cpp: `class Solution { public: bool hasPathSum(TreeNode* root, int t) { if(!root)return false; if(!root->left&&!root->right)return root->val==t; return hasPathSum(root->left,t-root->val)||hasPathSum(root->right,t-root->val); } };` },
    235: { javascript: `function maxPathSum(root) { let res=-Infinity; const dfs=(n)=>{if(!n)return 0;const l=Math.max(0,dfs(n.left)),r=Math.max(0,dfs(n.right));res=Math.max(res,l+r+n.val);return Math.max(l,r)+n.val;}; dfs(root); return res; }`, java: `class Solution { int res=Integer.MIN_VALUE; public int maxPathSum(TreeNode root) { dfs(root); return res; } int dfs(TreeNode n){if(n==null)return 0;int l=Math.max(0,dfs(n.left)),r=Math.max(0,dfs(n.right));res=Math.max(res,l+r+n.val);return Math.max(l,r)+n.val;} }`, cpp: `class Solution { int res=INT_MIN; public: int maxPathSum(TreeNode* root) { dfs(root); return res; } int dfs(TreeNode* n){if(!n)return 0;int l=max(0,dfs(n->left)),r=max(0,dfs(n->right));res=max(res,l+r+n->val);return max(l,r)+n->val;} };` },
    244: { javascript: `function minDepth(root) { if(!root)return 0; if(!root.left)return 1+minDepth(root.right); if(!root.right)return 1+minDepth(root.left); return 1+Math.min(minDepth(root.left),minDepth(root.right)); }`, java: `class Solution { public int minDepth(TreeNode root) { if(root==null)return 0; if(root.left==null)return 1+minDepth(root.right); if(root.right==null)return 1+minDepth(root.left); return 1+Math.min(minDepth(root.left),minDepth(root.right)); } }`, cpp: `class Solution { public: int minDepth(TreeNode* root) { if(!root)return 0; if(!root->left)return 1+minDepth(root->right); if(!root->right)return 1+minDepth(root->left); return 1+min(minDepth(root->left),minDepth(root->right)); } };` },
    247: { javascript: `function isValidBST(root) { const check=(n,lo,hi)=>{if(!n)return true;if(n.val<=lo||n.val>=hi)return false;return check(n.left,lo,n.val)&&check(n.right,n.val,hi);}; return check(root,-Infinity,Infinity); }`, java: `class Solution { public boolean isValidBST(TreeNode root) { return check(root,Long.MIN_VALUE,Long.MAX_VALUE); } boolean check(TreeNode n,long lo,long hi){if(n==null)return true;if(n.val<=lo||n.val>=hi)return false;return check(n.left,lo,n.val)&&check(n.right,n.val,hi);} }`, cpp: `class Solution { public: bool isValidBST(TreeNode* root) { return check(root,LONG_MIN,LONG_MAX); } bool check(TreeNode*n,long lo,long hi){if(!n)return true;if(n->val<=lo||n->val>=hi)return false;return check(n->left,lo,n->val)&&check(n->right,n->val,hi);} };` },
    250: { javascript: `function sortedArrayToBST(nums) { const build=(l,r)=>{if(l>r)return null;const m=l+((r-l)>>1);return{val:nums[m],left:build(l,m-1),right:build(m+1,r)};}; return build(0,nums.length-1); }`, java: `class Solution { public TreeNode sortedArrayToBST(int[] nums) { return build(nums,0,nums.length-1); } TreeNode build(int[] nums,int l,int r){if(l>r)return null;int m=l+(r-l)/2;TreeNode n=new TreeNode(nums[m]);n.left=build(nums,l,m-1);n.right=build(nums,m+1,r);return n;} }`, cpp: `class Solution { public: TreeNode* sortedArrayToBST(vector<int>& nums) { return build(nums,0,nums.size()-1); } TreeNode* build(vector<int>& nums,int l,int r){if(l>r)return nullptr;int m=l+(r-l)/2;auto n=new TreeNode(nums[m]);n->left=build(nums,l,m-1);n->right=build(nums,m+1,r);return n;} };` },
    239: { javascript: `function levelOrder(root) { if(!root)return[]; const res=[],q=[root]; while(q.length){const sz=q.length,level=[]; for(let i=0;i<sz;i++){const n=q.shift();level.push(n.val);if(n.left)q.push(n.left);if(n.right)q.push(n.right);}res.push(level);} return res; }`, java: `class Solution { public List<List<Integer>> levelOrder(TreeNode root) { List<List<Integer>> res=new ArrayList<>(); if(root==null)return res; Queue<TreeNode> q=new LinkedList<>(); q.offer(root); while(!q.isEmpty()){int sz=q.size();List<Integer> level=new ArrayList<>(); for(int i=0;i<sz;i++){TreeNode n=q.poll();level.add(n.val);if(n.left!=null)q.offer(n.left);if(n.right!=null)q.offer(n.right);}res.add(level);} return res; } }`, cpp: `class Solution { public: vector<vector<int>> levelOrder(TreeNode* root) { vector<vector<int>> res; if(!root)return res; queue<TreeNode*> q; q.push(root); while(!q.empty()){int sz=q.size();vector<int> level; for(int i=0;i<sz;i++){auto n=q.front();q.pop();level.push_back(n->val);if(n->left)q.push(n->left);if(n->right)q.push(n->right);}res.push_back(level);} return res; } };` },
    257: { javascript: `function deleteNode(root, key) { if(!root)return null; if(key<root.val)root.left=deleteNode(root.left,key); else if(key>root.val)root.right=deleteNode(root.right,key); else{if(!root.left)return root.right;if(!root.right)return root.left;let min=root.right;while(min.left)min=min.left;root.val=min.val;root.right=deleteNode(root.right,min.val);} return root; }`, java: `class Solution { public TreeNode deleteNode(TreeNode root, int key) { if(root==null)return null; if(key<root.val)root.left=deleteNode(root.left,key); else if(key>root.val)root.right=deleteNode(root.right,key); else{if(root.left==null)return root.right;if(root.right==null)return root.left;TreeNode min=root.right;while(min.left!=null)min=min.left;root.val=min.val;root.right=deleteNode(root.right,min.val);} return root; } }`, cpp: `class Solution { public: TreeNode* deleteNode(TreeNode* root, int key) { if(!root)return nullptr; if(key<root->val)root->left=deleteNode(root->left,key); else if(key>root->val)root->right=deleteNode(root->right,key); else{if(!root->left)return root->right;if(!root->right)return root->left;auto min=root->right;while(min->left)min=min->left;root->val=min->val;root->right=deleteNode(root->right,min->val);} return root; } };` },
    // Graph
    263: { javascript: `function maxAreaOfIsland(grid) { const m=grid.length,n=grid[0].length; let max=0; const dfs=(i,j)=>{if(i<0||i>=m||j<0||j>=n||!grid[i][j])return 0;grid[i][j]=0;return 1+dfs(i+1,j)+dfs(i-1,j)+dfs(i,j+1)+dfs(i,j-1);}; for(let i=0;i<m;i++)for(let j=0;j<n;j++)if(grid[i][j])max=Math.max(max,dfs(i,j)); return max; }`, java: `class Solution { public int maxAreaOfIsland(int[][] grid) { int max=0; for(int i=0;i<grid.length;i++)for(int j=0;j<grid[0].length;j++)if(grid[i][j]==1)max=Math.max(max,dfs(grid,i,j)); return max; } int dfs(int[][] g,int i,int j){if(i<0||i>=g.length||j<0||j>=g[0].length||g[i][j]==0)return 0;g[i][j]=0;return 1+dfs(g,i+1,j)+dfs(g,i-1,j)+dfs(g,i,j+1)+dfs(g,i,j-1);} }`, cpp: `class Solution { public: int maxAreaOfIsland(vector<vector<int>>& grid) { int mx=0; for(int i=0;i<grid.size();i++)for(int j=0;j<grid[0].size();j++)if(grid[i][j])mx=max(mx,dfs(grid,i,j)); return mx; } int dfs(vector<vector<int>>& g,int i,int j){if(i<0||i>=g.size()||j<0||j>=g[0].size()||!g[i][j])return 0;g[i][j]=0;return 1+dfs(g,i+1,j)+dfs(g,i-1,j)+dfs(g,i,j+1)+dfs(g,i,j-1);} };` },
    269: { javascript: `function findCircleNum(isConnected) { const n=isConnected.length,visited=new Array(n).fill(false); let count=0; const dfs=(i)=>{visited[i]=true;for(let j=0;j<n;j++)if(isConnected[i][j]&&!visited[j])dfs(j);}; for(let i=0;i<n;i++)if(!visited[i]){dfs(i);count++;} return count; }`, java: `class Solution { public int findCircleNum(int[][] ic) { int n=ic.length,count=0; boolean[] v=new boolean[n]; for(int i=0;i<n;i++)if(!v[i]){dfs(ic,v,i);count++;} return count; } void dfs(int[][] ic,boolean[] v,int i){v[i]=true;for(int j=0;j<ic.length;j++)if(ic[i][j]==1&&!v[j])dfs(ic,v,j);} }`, cpp: `class Solution { public: int findCircleNum(vector<vector<int>>& ic) { int n=ic.size(),count=0; vector<bool> v(n,false); for(int i=0;i<n;i++)if(!v[i]){dfs(ic,v,i);count++;} return count; } void dfs(vector<vector<int>>& ic,vector<bool>& v,int i){v[i]=true;for(int j=0;j<n;j++)if(ic[i][j]&&!v[j])dfs(ic,v,j);} };` },
    270: { javascript: `function validTree(n, edges) { if(edges.length!==n-1)return false; const adj=Array.from({length:n},()=>[]); for(const[a,b]of edges){adj[a].push(b);adj[b].push(a);} const visited=new Set(); const q=[0]; visited.add(0); while(q.length){const node=q.shift();for(const nb of adj[node])if(!visited.has(nb)){visited.add(nb);q.push(nb);}} return visited.size===n; }`, java: `class Solution { public boolean validTree(int n, int[][] edges) { if(edges.length!=n-1)return false; List<List<Integer>> adj=new ArrayList<>(); for(int i=0;i<n;i++)adj.add(new ArrayList<>()); for(int[] e:edges){adj.get(e[0]).add(e[1]);adj.get(e[1]).add(e[0]);} Set<Integer> v=new HashSet<>(); Queue<Integer> q=new LinkedList<>(); v.add(0);q.offer(0); while(!q.isEmpty()){int node=q.poll();for(int nb:adj.get(node))if(!v.contains(nb)){v.add(nb);q.offer(nb);}} return v.size()==n; } }`, cpp: `class Solution { public: bool validTree(int n, vector<vector<int>>& edges) { if(edges.size()!=n-1)return false; vector<vector<int>> adj(n); for(auto& e:edges){adj[e[0]].push_back(e[1]);adj[e[1]].push_back(e[0]);} unordered_set<int> v; queue<int> q; v.insert(0);q.push(0); while(!q.empty()){int node=q.front();q.pop();for(int nb:adj[node])if(!v.count(nb)){v.insert(nb);q.push(nb);}} return v.size()==n; } };` },
    272: { javascript: `function findRedundantConnection(edges) { const parent=Array.from({length:edges.length+1},(_,i)=>i); const find=(x)=>{while(parent[x]!==x){parent[x]=parent[parent[x]];x=parent[x];}return x;}; for(const[a,b]of edges){const ra=find(a),rb=find(b);if(ra===rb)return[a,b];parent[ra]=rb;} return[]; }`, java: `class Solution { int[] parent; public int[] findRedundantConnection(int[][] edges) { parent=new int[edges.length+1]; for(int i=0;i<parent.length;i++)parent[i]=i; for(int[] e:edges){int a=find(e[0]),b=find(e[1]);if(a==b)return e;parent[a]=b;} return new int[]{}; } int find(int x){while(parent[x]!=x){parent[x]=parent[parent[x]];x=parent[x];}return x;} }`, cpp: `class Solution { vector<int> parent; public: vector<int> findRedundantConnection(vector<vector<int>>& edges) { parent.resize(edges.size()+1); iota(parent.begin(),parent.end(),0); for(auto& e:edges){int a=find(e[0]),b=find(e[1]);if(a==b)return e;parent[a]=b;} return{}; } int find(int x){while(parent[x]!=x){parent[x]=parent[parent[x]];x=parent[x];}return x;} };` },
    // DP
    298: { javascript: `function minCostClimbingStairs(cost) { for(let i=2;i<cost.length;i++) cost[i]+=Math.min(cost[i-1],cost[i-2]); return Math.min(cost[cost.length-1],cost[cost.length-2]); }`, java: `class Solution { public int minCostClimbingStairs(int[] cost) { for(int i=2;i<cost.length;i++) cost[i]+=Math.min(cost[i-1],cost[i-2]); return Math.min(cost[cost.length-1],cost[cost.length-2]); } }`, cpp: `class Solution { public: int minCostClimbingStairs(vector<int>& cost) { for(int i=2;i<cost.size();i++) cost[i]+=min(cost[i-1],cost[i-2]); return min(cost.back(),cost[cost.size()-2]); } };` },
    299: { javascript: `function rob(nums) { if(nums.length===1)return nums[0]; let prev2=0,prev1=0; for(const n of nums){const tmp=Math.max(prev1,prev2+n);prev2=prev1;prev1=tmp;} return prev1; }`, java: `class Solution { public int rob(int[] nums) { int prev2=0,prev1=0; for(int n:nums){int tmp=Math.max(prev1,prev2+n);prev2=prev1;prev1=tmp;} return prev1; } }`, cpp: `class Solution { public: int rob(vector<int>& nums) { int prev2=0,prev1=0; for(int n:nums){int tmp=max(prev1,prev2+n);prev2=prev1;prev1=tmp;} return prev1; } };` },
    306: { javascript: `function numDecodings(s) { if(s[0]==='0')return 0; const n=s.length; let prev2=1,prev1=1; for(let i=1;i<n;i++){let curr=0;if(s[i]!=='0')curr=prev1;const two=parseInt(s.substring(i-1,i+1));if(two>=10&&two<=26)curr+=prev2;prev2=prev1;prev1=curr;} return prev1; }`, java: `class Solution { public int numDecodings(String s) { if(s.charAt(0)=='0')return 0; int prev2=1,prev1=1; for(int i=1;i<s.length();i++){int curr=0;if(s.charAt(i)!='0')curr=prev1;int two=Integer.parseInt(s.substring(i-1,i+1));if(two>=10&&two<=26)curr+=prev2;prev2=prev1;prev1=curr;} return prev1; } }`, cpp: `class Solution { public: int numDecodings(string s) { if(s[0]=='0')return 0; int prev2=1,prev1=1; for(int i=1;i<s.size();i++){int curr=0;if(s[i]!='0')curr=prev1;int two=stoi(s.substr(i-1,2));if(two>=10&&two<=26)curr+=prev2;prev2=prev1;prev1=curr;} return prev1; } };` },
    317: { javascript: `function longestCommonSubsequence(t1,t2) { const m=t1.length,n=t2.length; const dp=Array.from({length:m+1},()=>new Array(n+1).fill(0)); for(let i=1;i<=m;i++)for(let j=1;j<=n;j++) dp[i][j]=t1[i-1]===t2[j-1]?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1]); return dp[m][n]; }`, java: `class Solution { public int longestCommonSubsequence(String t1, String t2) { int m=t1.length(),n=t2.length(); int[][] dp=new int[m+1][n+1]; for(int i=1;i<=m;i++)for(int j=1;j<=n;j++) dp[i][j]=t1.charAt(i-1)==t2.charAt(j-1)?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1]); return dp[m][n]; } }`, cpp: `class Solution { public: int longestCommonSubsequence(string t1, string t2) { int m=t1.size(),n=t2.size(); vector<vector<int>> dp(m+1,vector<int>(n+1,0)); for(int i=1;i<=m;i++)for(int j=1;j<=n;j++) dp[i][j]=t1[i-1]==t2[j-1]?dp[i-1][j-1]+1:max(dp[i-1][j],dp[i][j-1]); return dp[m][n]; } };` },
    321: { javascript: `function lengthOfLIS(nums) { const tails=[]; for(const n of nums){let lo=0,hi=tails.length;while(lo<hi){const m=lo+((hi-lo)>>1);if(tails[m]<n)lo=m+1;else hi=m;}if(lo===tails.length)tails.push(n);else tails[lo]=n;} return tails.length; }`, java: `class Solution { public int lengthOfLIS(int[] nums) { List<Integer> tails=new ArrayList<>(); for(int n:nums){int lo=0,hi=tails.size();while(lo<hi){int m=lo+(hi-lo)/2;if(tails.get(m)<n)lo=m+1;else hi=m;}if(lo==tails.size())tails.add(n);else tails.set(lo,n);} return tails.size(); } }`, cpp: `class Solution { public: int lengthOfLIS(vector<int>& nums) { vector<int> tails; for(int n:nums){auto it=lower_bound(tails.begin(),tails.end(),n);if(it==tails.end())tails.push_back(n);else *it=n;} return tails.size(); } };` },
    // Greedy
    412: { javascript: `function canJump(nums) { let maxReach=0; for(let i=0;i<nums.length;i++){if(i>maxReach)return false;maxReach=Math.max(maxReach,i+nums[i]);} return true; }`, java: `class Solution { public boolean canJump(int[] nums) { int maxReach=0; for(int i=0;i<nums.length;i++){if(i>maxReach)return false;maxReach=Math.max(maxReach,i+nums[i]);} return true; } }`, cpp: `class Solution { public: bool canJump(vector<int>& nums) { int maxReach=0; for(int i=0;i<nums.size();i++){if(i>maxReach)return false;maxReach=max(maxReach,i+nums[i]);} return true; } };` },
    413: { javascript: `function jump(nums) { let jumps=0,end=0,farthest=0; for(let i=0;i<nums.length-1;i++){farthest=Math.max(farthest,i+nums[i]);if(i===end){jumps++;end=farthest;}} return jumps; }`, java: `class Solution { public int jump(int[] nums) { int jumps=0,end=0,farthest=0; for(int i=0;i<nums.length-1;i++){farthest=Math.max(farthest,i+nums[i]);if(i==end){jumps++;end=farthest;}} return jumps; } }`, cpp: `class Solution { public: int jump(vector<int>& nums) { int jumps=0,end=0,farthest=0; for(int i=0;i<nums.size()-1;i++){farthest=max(farthest,i+nums[i]);if(i==end){jumps++;end=farthest;}} return jumps; } };` },
    416: { javascript: `function reconstructQueue(people) { people.sort((a,b)=>b[0]-a[0]||a[1]-b[1]); const res=[]; for(const p of people) res.splice(p[1],0,p); return res; }`, java: `class Solution { public int[][] reconstructQueue(int[][] people) { Arrays.sort(people,(a,b)->a[0]==b[0]?a[1]-b[1]:b[0]-a[0]); List<int[]> res=new ArrayList<>(); for(int[] p:people) res.add(p[1],p); return res.toArray(new int[0][]); } }`, cpp: `class Solution { public: vector<vector<int>> reconstructQueue(vector<vector<int>>& people) { sort(people.begin(),people.end(),[](auto&a,auto&b){return a[0]==b[0]?a[1]<b[1]:a[0]>b[0];}); vector<vector<int>> res; for(auto& p:people) res.insert(res.begin()+p[1],p); return res; } };` },
    417: { javascript: `function partitionLabels(s) { const last={}; for(let i=0;i<s.length;i++) last[s[i]]=i; const res=[]; let start=0,end=0; for(let i=0;i<s.length;i++){end=Math.max(end,last[s[i]]);if(i===end){res.push(end-start+1);start=end+1;}} return res; }`, java: `class Solution { public List<Integer> partitionLabels(String s) { int[] last=new int[26]; for(int i=0;i<s.length();i++) last[s.charAt(i)-'a']=i; List<Integer> res=new ArrayList<>(); int start=0,end=0; for(int i=0;i<s.length();i++){end=Math.max(end,last[s.charAt(i)-'a']);if(i==end){res.add(end-start+1);start=end+1;}} return res; } }`, cpp: `class Solution { public: vector<int> partitionLabels(string s) { int last[26]={}; for(int i=0;i<s.size();i++) last[s[i]-'a']=i; vector<int> res; int start=0,end=0; for(int i=0;i<s.size();i++){end=max(end,last[s[i]-'a']);if(i==end){res.push_back(end-start+1);start=end+1;}} return res; } };` },
    419: { javascript: `function findMinArrowShots(points) { points.sort((a,b)=>a[1]-b[1]); let arrows=1,end=points[0][1]; for(let i=1;i<points.length;i++){if(points[i][0]>end){arrows++;end=points[i][1];}} return arrows; }`, java: `class Solution { public int findMinArrowShots(int[][] p) { Arrays.sort(p,(a,b)->Integer.compare(a[1],b[1])); int arrows=1; long end=p[0][1]; for(int i=1;i<p.length;i++){if(p[i][0]>end){arrows++;end=p[i][1];}} return arrows; } }`, cpp: `class Solution { public: int findMinArrowShots(vector<vector<int>>& p) { sort(p.begin(),p.end(),[](auto&a,auto&b){return a[1]<b[1];}); int arrows=1; long end=p[0][1]; for(int i=1;i<p.size();i++){if(p[i][0]>end){arrows++;end=p[i][1];}} return arrows; } };` },
    425: { javascript: `function minDeletions(s) { const freq=new Array(26).fill(0); for(const c of s) freq[c.charCodeAt(0)-97]++; freq.sort((a,b)=>b-a); let del=0; for(let i=1;i<26;i++){while(freq[i]>0&&freq[i]>=freq[i-1]){freq[i]--;del++;}} return del; }`, java: `class Solution { public int minDeletions(String s) { int[] freq=new int[26]; for(char c:s.toCharArray()) freq[c-'a']++; Arrays.sort(freq); int del=0; for(int i=24;i>=0;i--){while(freq[i]>0&&freq[i]>=freq[i+1]){freq[i]--;del++;}} return del; } }`, cpp: `class Solution { public: int minDeletions(string s) { int freq[26]={}; for(char c:s) freq[c-'a']++; sort(freq,freq+26,greater<int>()); int del=0; for(int i=1;i<26;i++){while(freq[i]>0&&freq[i]>=freq[i-1]){freq[i]--;del++;}} return del; } };` },
    427: { javascript: `function maximumUnits(boxTypes, truckSize) { boxTypes.sort((a,b)=>b[1]-a[1]); let units=0; for(const[b,u]of boxTypes){const take=Math.min(b,truckSize);units+=take*u;truckSize-=take;if(!truckSize)break;} return units; }`, java: `class Solution { public int maximumUnits(int[][] bt, int ts) { Arrays.sort(bt,(a,b)->b[1]-a[1]); int units=0; for(int[] b:bt){int take=Math.min(b[0],ts);units+=take*b[1];ts-=take;if(ts==0)break;} return units; } }`, cpp: `class Solution { public: int maximumUnits(vector<vector<int>>& bt, int ts) { sort(bt.begin(),bt.end(),[](auto&a,auto&b){return a[1]>b[1];}); int units=0; for(auto& b:bt){int take=min(b[0],ts);units+=take*b[1];ts-=take;if(!ts)break;} return units; } };` },
};

async function run() {
    console.log('Adding multi-language solutions - Batch 4...\n');
    let updated = 0, failed = 0;
    for (const [id, langSolutions] of Object.entries(S)) {
        const { data: problem } = await supabaseAdmin.from('problems').select('solution_code').eq('id', parseInt(id)).single();
        if (!problem) { console.log(`  Problem #${id} not found`); continue; }
        const merged = { ...(problem.solution_code || {}), ...langSolutions };
        const { error } = await supabaseAdmin.from('problems').update({ solution_code: merged }).eq('id', parseInt(id));
        if (error) { console.error(`  ❌ #${id}: ${error.message}`); failed++; }
        else { updated++; }
    }
    console.log(`Done: ${updated} updated, ${failed} failed`);
}
run();
