import { supabaseAdmin } from '../db/supabaseClient.js';
const S = {
    // Advanced linked list / misc
    143: { javascript: `function flatten(head) { let curr=head; while(curr){if(curr.child){let next=curr.next,child=curr.child;curr.next=child;child.prev=curr;curr.child=null;let tail=child;while(tail.next)tail=tail.next;tail.next=next;if(next)next.prev=tail;}curr=curr.next;} return head; }`, java: `class Solution { public Node flatten(Node head) { Node curr=head; while(curr!=null){if(curr.child!=null){Node next=curr.next,child=curr.child;curr.next=child;child.prev=curr;curr.child=null;Node tail=child;while(tail.next!=null)tail=tail.next;tail.next=next;if(next!=null)next.prev=tail;}curr=curr.next;} return head; } }`, cpp: `class Solution { public: Node* flatten(Node* head) { auto curr=head; while(curr){if(curr->child){auto next=curr->next,child=curr->child;curr->next=child;child->prev=curr;curr->child=nullptr;auto tail=child;while(tail->next)tail=tail->next;tail->next=next;if(next)next->prev=tail;}curr=curr->next;} return head; } };` },
    144: { javascript: `function insert(head, val) { const node={val,next:null}; if(!head){node.next=node;return node;} let prev=head,curr=head.next; while(true){if((prev.val<=val&&val<=curr.val)||(prev.val>curr.val&&(val>=prev.val||val<=curr.val))||prev.next===head)break;prev=curr;curr=curr.next;} prev.next=node;node.next=curr; return head; }`, java: `class Solution { public Node insert(Node head, int val) { Node node=new Node(val); if(head==null){node.next=node;return node;} Node prev=head,curr=head.next; while(true){if((prev.val<=val&&val<=curr.val)||(prev.val>curr.val&&(val>=prev.val||val<=curr.val))||curr==head)break;prev=curr;curr=curr.next;} prev.next=node;node.next=curr; return head; } }`, cpp: `class Solution { public: Node* insert(Node* head, int val) { auto node=new Node(val); if(!head){node->next=node;return node;} auto prev=head,curr=head->next; while(true){if((prev->val<=val&&val<=curr->val)||(prev->val>curr->val&&(val>=prev->val||val<=curr->val))||curr==head)break;prev=curr;curr=curr->next;} prev->next=node;node->next=curr; return head; } };` },
    146: { javascript: `function nextLargerNodes(head) { const vals=[]; let curr=head; while(curr){vals.push(curr.val);curr=curr.next;} const res=new Array(vals.length).fill(0),stack=[]; for(let i=0;i<vals.length;i++){while(stack.length&&vals[stack[stack.length-1]]<vals[i])res[stack.pop()]=vals[i];stack.push(i);} return res; }`, java: `class Solution { public int[] nextLargerNodes(ListNode head) { List<Integer> vals=new ArrayList<>(); while(head!=null){vals.add(head.val);head=head.next;} int[] res=new int[vals.size()]; Deque<Integer> stack=new ArrayDeque<>(); for(int i=0;i<vals.size();i++){while(!stack.isEmpty()&&vals.get(stack.peek())<vals.get(i))res[stack.pop()]=vals.get(i);stack.push(i);} return res; } }`, cpp: `class Solution { public: vector<int> nextLargerNodes(ListNode* head) { vector<int> vals; while(head){vals.push_back(head->val);head=head->next;} vector<int> res(vals.size(),0); stack<int> st; for(int i=0;i<vals.size();i++){while(!st.empty()&&vals[st.top()]<vals[i]){res[st.top()]=vals[i];st.pop();}st.push(i);} return res; } };` },
    // Advanced binary search
    201: { javascript: `function findClosestElements(arr, k, x) { let lo=0,hi=arr.length-k; while(lo<hi){const m=lo+((hi-lo)>>1);if(x-arr[m]>arr[m+k]-x)lo=m+1;else hi=m;} return arr.slice(lo,lo+k); }`, java: `class Solution { public List<Integer> findClosestElements(int[] arr, int k, int x) { int lo=0,hi=arr.length-k; while(lo<hi){int m=lo+(hi-lo)/2;if(x-arr[m]>arr[m+k]-x)lo=m+1;else hi=m;} List<Integer> res=new ArrayList<>(); for(int i=lo;i<lo+k;i++)res.add(arr[i]); return res; } }`, cpp: `class Solution { public: vector<int> findClosestElements(vector<int>& arr, int k, int x) { int lo=0,hi=arr.size()-k; while(lo<hi){int m=lo+(hi-lo)/2;if(x-arr[m]>arr[m+k]-x)lo=m+1;else hi=m;} return vector<int>(arr.begin()+lo,arr.begin()+lo+k); } };` },
    207: { javascript: `function shipWithinDays(weights, days) { let lo=Math.max(...weights),hi=weights.reduce((a,b)=>a+b); while(lo<hi){const m=lo+((hi-lo)>>1);let d=1,sum=0;for(const w of weights){if(sum+w>m){d++;sum=0;}sum+=w;}if(d<=days)hi=m;else lo=m+1;} return lo; }`, java: `class Solution { public int shipWithinDays(int[] weights, int days) { int lo=0,hi=0;for(int w:weights){lo=Math.max(lo,w);hi+=w;} while(lo<hi){int m=lo+(hi-lo)/2,d=1,sum=0;for(int w:weights){if(sum+w>m){d++;sum=0;}sum+=w;}if(d<=days)hi=m;else lo=m+1;} return lo; } }`, cpp: `class Solution { public: int shipWithinDays(vector<int>& weights, int days) { int lo=*max_element(weights.begin(),weights.end()),hi=accumulate(weights.begin(),weights.end(),0); while(lo<hi){int m=lo+(hi-lo)/2,d=1,sum=0;for(int w:weights){if(sum+w>m){d++;sum=0;}sum+=w;}if(d<=days)hi=m;else lo=m+1;} return lo; } };` },
    // More DP
    315: { javascript: `function longestPalindromeSubseq(s) { const n=s.length; const dp=Array.from({length:n},()=>new Array(n).fill(0)); for(let i=n-1;i>=0;i--){dp[i][i]=1;for(let j=i+1;j<n;j++)dp[i][j]=s[i]===s[j]?dp[i+1][j-1]+2:Math.max(dp[i+1][j],dp[i][j-1]);} return dp[0][n-1]; }`, java: `class Solution { public int longestPalindromeSubseq(String s) { int n=s.length();int[][] dp=new int[n][n]; for(int i=n-1;i>=0;i--){dp[i][i]=1;for(int j=i+1;j<n;j++)dp[i][j]=s.charAt(i)==s.charAt(j)?dp[i+1][j-1]+2:Math.max(dp[i+1][j],dp[i][j-1]);} return dp[0][n-1]; } }`, cpp: `class Solution { public: int longestPalindromeSubseq(string s) { int n=s.size();vector<vector<int>> dp(n,vector<int>(n,0)); for(int i=n-1;i>=0;i--){dp[i][i]=1;for(int j=i+1;j<n;j++)dp[i][j]=s[i]==s[j]?dp[i+1][j-1]+2:max(dp[i+1][j],dp[i][j-1]);} return dp[0][n-1]; } };` },
    319: { javascript: `function numDistinct(s, t) { const m=s.length,n=t.length; const dp=new Array(n+1).fill(0);dp[0]=1; for(let i=1;i<=m;i++)for(let j=n;j>=1;j--)if(s[i-1]===t[j-1])dp[j]+=dp[j-1]; return dp[n]; }`, java: `class Solution { public int numDistinct(String s, String t) { int m=s.length(),n=t.length();long[] dp=new long[n+1];dp[0]=1; for(int i=1;i<=m;i++)for(int j=n;j>=1;j--)if(s.charAt(i-1)==t.charAt(j-1))dp[j]+=dp[j-1]; return (int)dp[n]; } }`, cpp: `class Solution { public: int numDistinct(string s, string t) { int m=s.size(),n=t.size();vector<unsigned long> dp(n+1,0);dp[0]=1; for(int i=1;i<=m;i++)for(int j=n;j>=1;j--)if(s[i-1]==t[j-1])dp[j]+=dp[j-1]; return dp[n]; } };` },
    322: { javascript: `function longestIncreasingPath(matrix) { const m=matrix.length,n=matrix[0].length; const memo=Array.from({length:m},()=>new Array(n).fill(0)); const dfs=(i,j)=>{if(memo[i][j])return memo[i][j];let max=1;for(const[di,dj]of[[0,1],[0,-1],[1,0],[-1,0]]){const ni=i+di,nj=j+dj;if(ni>=0&&ni<m&&nj>=0&&nj<n&&matrix[ni][nj]>matrix[i][j])max=Math.max(max,1+dfs(ni,nj));}return memo[i][j]=max;}; let res=0;for(let i=0;i<m;i++)for(let j=0;j<n;j++)res=Math.max(res,dfs(i,j)); return res; }`, java: `class Solution { int[][] memo; public int longestIncreasingPath(int[][] matrix) { int m=matrix.length,n=matrix[0].length;memo=new int[m][n]; int res=0;for(int i=0;i<m;i++)for(int j=0;j<n;j++)res=Math.max(res,dfs(matrix,i,j)); return res; } int dfs(int[][] mat,int i,int j){if(memo[i][j]>0)return memo[i][j];int mx=1;int[][] dirs={{0,1},{0,-1},{1,0},{-1,0}};for(int[] d:dirs){int ni=i+d[0],nj=j+d[1];if(ni>=0&&ni<mat.length&&nj>=0&&nj<mat[0].length&&mat[ni][nj]>mat[i][j])mx=Math.max(mx,1+dfs(mat,ni,nj));}return memo[i][j]=mx;} }`, cpp: `class Solution { public: int longestIncreasingPath(vector<vector<int>>& matrix) { int m=matrix.size(),n=matrix[0].size(); vector<vector<int>> memo(m,vector<int>(n,0)); int res=0;for(int i=0;i<m;i++)for(int j=0;j<n;j++)res=max(res,dfs(matrix,memo,i,j)); return res; } int dfs(vector<vector<int>>&mat,vector<vector<int>>&memo,int i,int j){if(memo[i][j])return memo[i][j];int mx=1;int dirs[][2]={{0,1},{0,-1},{1,0},{-1,0}};for(auto&d:dirs){int ni=i+d[0],nj=j+d[1];if(ni>=0&&ni<mat.size()&&nj>=0&&nj<mat[0].size()&&mat[ni][nj]>mat[i][j])mx=max(mx,1+dfs(mat,memo,ni,nj));}return memo[i][j]=mx;} };` },
    339: { javascript: `function isMatch(s, p) { const m=s.length,n=p.length; const dp=Array.from({length:m+1},()=>new Array(n+1).fill(false));dp[0][0]=true; for(let j=1;j<=n;j++)if(p[j-1]==='*')dp[0][j]=dp[0][j-2]; for(let i=1;i<=m;i++)for(let j=1;j<=n;j++){if(p[j-1]==='.'||p[j-1]===s[i-1])dp[i][j]=dp[i-1][j-1];else if(p[j-1]==='*'){dp[i][j]=dp[i][j-2];if(p[j-2]==='.'||p[j-2]===s[i-1])dp[i][j]=dp[i][j]||dp[i-1][j];}} return dp[m][n]; }`, java: `class Solution { public boolean isMatch(String s, String p) { int m=s.length(),n=p.length();boolean[][] dp=new boolean[m+1][n+1];dp[0][0]=true; for(int j=1;j<=n;j++)if(p.charAt(j-1)=='*')dp[0][j]=dp[0][j-2]; for(int i=1;i<=m;i++)for(int j=1;j<=n;j++){if(p.charAt(j-1)=='.'||p.charAt(j-1)==s.charAt(i-1))dp[i][j]=dp[i-1][j-1];else if(p.charAt(j-1)=='*'){dp[i][j]=dp[i][j-2];if(p.charAt(j-2)=='.'||p.charAt(j-2)==s.charAt(i-1))dp[i][j]=dp[i][j]||dp[i-1][j];}} return dp[m][n]; } }`, cpp: `class Solution { public: bool isMatch(string s, string p) { int m=s.size(),n=p.size();vector<vector<bool>> dp(m+1,vector<bool>(n+1,false));dp[0][0]=true; for(int j=1;j<=n;j++)if(p[j-1]=='*')dp[0][j]=dp[0][j-2]; for(int i=1;i<=m;i++)for(int j=1;j<=n;j++){if(p[j-1]=='.'||p[j-1]==s[i-1])dp[i][j]=dp[i-1][j-1];else if(p[j-1]=='*'){dp[i][j]=dp[i][j-2];if(p[j-2]=='.'||p[j-2]==s[i-1])dp[i][j]=dp[i][j]||dp[i-1][j];}} return dp[m][n]; } };` },
    344: { javascript: `function numTrees(n) { const dp=new Array(n+1).fill(0);dp[0]=dp[1]=1; for(let i=2;i<=n;i++)for(let j=0;j<i;j++)dp[i]+=dp[j]*dp[i-1-j]; return dp[n]; }`, java: `class Solution { public int numTrees(int n) { int[] dp=new int[n+1];dp[0]=dp[1]=1; for(int i=2;i<=n;i++)for(int j=0;j<i;j++)dp[i]+=dp[j]*dp[i-1-j]; return dp[n]; } }`, cpp: `class Solution { public: int numTrees(int n) { vector<int> dp(n+1,0);dp[0]=dp[1]=1; for(int i=2;i<=n;i++)for(int j=0;j<i;j++)dp[i]+=dp[j]*dp[i-1-j]; return dp[n]; } };` },
    // Heap
    381: { javascript: `function kClosest(points, k) { points.sort((a,b)=>(a[0]**2+a[1]**2)-(b[0]**2+b[1]**2)); return points.slice(0,k); }`, java: `class Solution { public int[][] kClosest(int[][] points, int k) { Arrays.sort(points,(a,b)->(a[0]*a[0]+a[1]*a[1])-(b[0]*b[0]+b[1]*b[1])); return Arrays.copyOf(points,k); } }`, cpp: `class Solution { public: vector<vector<int>> kClosest(vector<vector<int>>& points, int k) { sort(points.begin(),points.end(),[](auto&a,auto&b){return a[0]*a[0]+a[1]*a[1]<b[0]*b[0]+b[1]*b[1];}); return vector<vector<int>>(points.begin(),points.begin()+k); } };` },
    380: { javascript: `function topKFrequent(words, k) { const freq={}; for(const w of words) freq[w]=(freq[w]||0)+1; return Object.keys(freq).sort((a,b)=>freq[b]-freq[a]||(a<b?-1:1)).slice(0,k); }`, java: `class Solution { public List<String> topKFrequent(String[] words, int k) { Map<String,Integer> freq=new HashMap<>(); for(String w:words) freq.merge(w,1,Integer::sum); List<String> res=new ArrayList<>(freq.keySet()); res.sort((a,b)->freq.get(b).equals(freq.get(a))?a.compareTo(b):freq.get(b)-freq.get(a)); return res.subList(0,k); } }`, cpp: `class Solution { public: vector<string> topKFrequent(vector<string>& words, int k) { unordered_map<string,int> freq; for(auto&w:words) freq[w]++; vector<string> res; for(auto&[w,c]:freq) res.push_back(w); sort(res.begin(),res.end(),[&](auto&a,auto&b){return freq[a]==freq[b]?a<b:freq[a]>freq[b];}); res.resize(k); return res; } };` },
    384: { javascript: `function reorganizeString(s) { const freq=new Array(26).fill(0); for(const c of s) freq[c.charCodeAt(0)-97]++; const maxF=Math.max(...freq); if(maxF>(s.length+1)/2)return""; const idx=freq.map((f,i)=>[f,i]).sort((a,b)=>b[0]-a[0]); const res=new Array(s.length);let pos=0; for(const[f,i]of idx){for(let j=0;j<f;j++){if(pos>=s.length)pos=1;res[pos]=String.fromCharCode(i+97);pos+=2;}} return res.join(''); }`, java: `class Solution { public String reorganizeString(String s) { int[] freq=new int[26]; for(char c:s.toCharArray()) freq[c-'a']++; int maxF=0;for(int f:freq) maxF=Math.max(maxF,f); if(maxF>(s.length()+1)/2) return ""; char[] res=new char[s.length()]; Integer[] idx=new Integer[26]; for(int i=0;i<26;i++)idx[i]=i; Arrays.sort(idx,(a,b)->freq[b]-freq[a]); int pos=0; for(int i:idx){for(int j=0;j<freq[i];j++){if(pos>=s.length())pos=1;res[pos]=(char)('a'+i);pos+=2;}} return new String(res); } }`, cpp: `class Solution { public: string reorganizeString(string s) { int freq[26]={};for(char c:s)freq[c-'a']++; int maxF=*max_element(freq,freq+26); if(maxF>(s.size()+1)/2)return""; vector<pair<int,int>> v;for(int i=0;i<26;i++)if(freq[i])v.push_back({freq[i],i}); sort(v.rbegin(),v.rend()); string res(s.size(),' ');int pos=0; for(auto[f,i]:v){for(int j=0;j<f;j++){if(pos>=s.size())pos=1;res[pos]=(char)('a'+i);pos+=2;}} return res; } };` },
    393: { javascript: `function minMeetingRooms(intervals) { const starts=intervals.map(i=>i[0]).sort((a,b)=>a-b); const ends=intervals.map(i=>i[1]).sort((a,b)=>a-b); let rooms=0,end=0; for(let i=0;i<starts.length;i++){if(starts[i]<ends[end])rooms++;else end++;} return rooms; }`, java: `class Solution { public int minMeetingRooms(int[][] intervals) { int[] starts=new int[intervals.length],ends=new int[intervals.length]; for(int i=0;i<intervals.length;i++){starts[i]=intervals[i][0];ends[i]=intervals[i][1];} Arrays.sort(starts);Arrays.sort(ends); int rooms=0,end=0; for(int i=0;i<starts.length;i++){if(starts[i]<ends[end])rooms++;else end++;} return rooms; } }`, cpp: `class Solution { public: int minMeetingRooms(vector<vector<int>>& intervals) { vector<int> starts,ends; for(auto&i:intervals){starts.push_back(i[0]);ends.push_back(i[1]);} sort(starts.begin(),starts.end());sort(ends.begin(),ends.end()); int rooms=0,e=0; for(int i=0;i<starts.size();i++){if(starts[i]<ends[e])rooms++;else e++;} return rooms; } };` },
    // Trie
    399: { javascript: `function suggestedProducts(products, searchWord) { products.sort(); const res=[]; for(let i=1;i<=searchWord.length;i++){const prefix=searchWord.substring(0,i); const matches=products.filter(p=>p.startsWith(prefix)).slice(0,3); res.push(matches);} return res; }`, java: `class Solution { public List<List<String>> suggestedProducts(String[] products, String searchWord) { Arrays.sort(products); List<List<String>> res=new ArrayList<>(); for(int i=1;i<=searchWord.length();i++){String prefix=searchWord.substring(0,i); List<String> matches=new ArrayList<>(); for(String p:products)if(p.startsWith(prefix)&&matches.size()<3)matches.add(p); res.add(matches);} return res; } }`, cpp: `class Solution { public: vector<vector<string>> suggestedProducts(vector<string>& products, string searchWord) { sort(products.begin(),products.end()); vector<vector<string>> res; for(int i=1;i<=searchWord.size();i++){string prefix=searchWord.substr(0,i); vector<string> matches; for(auto&p:products)if(p.substr(0,i)==prefix&&matches.size()<3)matches.push_back(p); res.push_back(matches);} return res; } };` },
    411: { javascript: `function longestWord(words) { const set=new Set(words);let res=""; for(const w of words){let valid=true;for(let i=1;i<w.length;i++)if(!set.has(w.substring(0,i))){valid=false;break;} if(valid&&(w.length>res.length||(w.length===res.length&&w<res)))res=w;} return res; }`, java: `class Solution { public String longestWord(String[] words) { Set<String> set=new HashSet<>(Arrays.asList(words));String res=""; for(String w:words){boolean valid=true;for(int i=1;i<w.length();i++)if(!set.contains(w.substring(0,i))){valid=false;break;} if(valid&&(w.length()>res.length()||(w.length()==res.length()&&w.compareTo(res)<0)))res=w;} return res; } }`, cpp: `class Solution { public: string longestWord(vector<string>& words) { set<string> s(words.begin(),words.end());string res; for(auto&w:words){bool valid=true;for(int i=1;i<w.size();i++)if(!s.count(w.substr(0,i))){valid=false;break;} if(valid&&(w.size()>res.size()||(w.size()==res.size()&&w<res)))res=w;} return res; } };` },
};

async function run() {
    console.log('Adding multi-language solutions - Batch 8...\n');
    let updated = 0, failed = 0;
    for (const [id, langs] of Object.entries(S)) {
        const { data: p } = await supabaseAdmin.from('problems').select('solution_code').eq('id', parseInt(id)).single();
        if (!p) continue;
        const merged = { ...(p.solution_code || {}), ...langs };
        const { error } = await supabaseAdmin.from('problems').update({ solution_code: merged }).eq('id', parseInt(id));
        if (error) { failed++; } else { updated++; }
    }
    console.log(`Done: ${updated} updated, ${failed} failed`);
}
run();
