// Batch 5: DP, Greedy, Trie, Backtracking, Bit Manipulation, and remaining problems (321-431)
import { supabaseAdmin } from '../db/supabaseClient.js';

const updates = [
    // ── DP continued (321-360) ──
    { id: 321, description: 'Given an m x n binary matrix filled with 0s and 1s, find the largest square containing only 1s and return its area.', constraints: 'm == matrix.length\nn == matrix[i].length\n1 <= m, n <= 300\nmatrix[i][j] is 0 or 1.' },
    { id: 322, description: 'Given an m x n integers matrix, return the length of the longest increasing path in matrix. From each cell, you can either move in four directions: left, right, up, or down. You may not move diagonally or move outside the boundary.', constraints: 'm == matrix.length\nn == matrix[i].length\n1 <= m, n <= 200\n0 <= matrix[i][j] <= 2^31 - 1' },
    { id: 323, description: 'Given a rows x cols grid, you start at the top-left corner of the grid, and you want to reach the bottom-right corner. You can only move either down or right at any point in time. How many possible unique paths are there?', constraints: '1 <= m, n <= 100' },
    { id: 324, description: 'You are given an m x n integer array grid. There is a robot initially located at the top-left corner. The robot tries to move to the bottom-right corner. The robot can only move either down or right at any point in time. An obstacle and space are marked as 1 or 0 respectively in grid. Return the number of possible unique paths that the robot can take to reach the bottom-right corner.', constraints: 'm == obstacleGrid.length\nn == obstacleGrid[i].length\n1 <= m, n <= 100\nobstacleGrid[i][j] is 0 or 1.' },
    { id: 325, description: 'Given an n x n array of non-negative integers representing the cost of moving through a grid, return the minimum sum path from the top-left to the bottom-right corner, where you can only move right or down at each step.', constraints: 'n == grid.length\nn == grid[i].length\n1 <= n <= 200\n0 <= grid[i][j] <= 200' },
    { id: 327, description: 'Given a 2D matrix matrix, handle multiple queries of the following type: Calculate the sum of the elements of matrix inside the rectangle defined by its upper left corner (row1, col1) and lower right corner (row2, col2).\n\nImplement the NumMatrix class.', constraints: 'm == matrix.length\nn == matrix[i].length\n1 <= m, n <= 200\n-10^4 <= matrix[i][j] <= 10^4\n0 <= row1 <= row2 < m\n0 <= col1 <= col2 < n\nAt most 10^4 calls will be made to sumRegion.' },
    { id: 328, description: 'Given n balloons, indexed from 0 to n - 1. Each balloon is painted with a number on it represented by an array nums. You are asked to burst all the balloons. If you burst the ith balloon, you will get nums[i - 1] * nums[i] * nums[i + 1] coins. If i - 1 or i + 1 goes out of bounds of the array, then treat it as if there is a balloon with a 1 painted on it. Return the maximum coins you can collect by bursting the balloons wisely.', constraints: 'n == nums.length\n1 <= n <= 300\n0 <= nums[i] <= 100' },
    { id: 329, description: 'You are given an array of words where each word consists of lowercase English letters. wordA is a predecessor of wordB if and only if we can insert exactly one letter anywhere in wordA without changing the order of the other characters to make it equal to wordB. A word chain is a sequence of words where each word is a predecessor of the next one. Return the length of the longest possible word chain.', constraints: '1 <= words.length <= 1000\n1 <= words[i].length <= 16\nwords[i] only consists of lowercase English letters.' },
    { id: 330, description: 'Given a set of distinct positive integers nums, return the largest subset answer such that every pair (answer[i], answer[j]) of elements in this subset satisfies: answer[i] % answer[j] == 0 or answer[j] % answer[i] == 0. If there are multiple solutions, return any of them.', constraints: '1 <= nums.length <= 1000\n1 <= nums[i] <= 2 * 10^9\nAll the integers in nums are unique.' },
    { id: 331, description: 'Given a m x n grid filled with non-negative numbers, find a path from top left to bottom right, which minimizes the sum of all numbers along its path.\n\nNote: You can only move either down or right at any point in time.', constraints: 'm == grid.length\nn == grid[i].length\n1 <= m, n <= 200\n0 <= grid[i][j] <= 200' },
    { id: 332, description: 'An ugly number is a positive integer whose prime factors are limited to 2, 3, and 5. Given an integer n, return the nth ugly number.', constraints: '1 <= n <= 1690' },
    { id: 333, description: 'A super ugly number is a positive integer whose prime factors are in the array primes. Given an integer n and an array of integers primes, return the nth super ugly number. The nth super ugly number is guaranteed to fit in a 32-bit signed integer.', constraints: '1 <= n <= 10^5\n1 <= primes.length <= 100\n2 <= primes[i] <= 1000\nprimes[i] is guaranteed to be a prime number.\nAll the values of primes are unique and sorted in ascending order.' },
    { id: 334, description: 'Given an integer n, return the number of ways you can write n as the sum of consecutive positive integers. For example, 5 can be written as 2+3 or 5.', constraints: '1 <= n <= 10^9' },
    { id: 335, description: 'Given a non-empty array nums containing only positive integers, find if the array can be partitioned into two subsets such that the sum of elements in both subsets is equal.', constraints: '1 <= nums.length <= 200\n1 <= nums[i] <= 100' },
    { id: 336, description: 'You are given an integer array nums and an integer target. You want to build an expression out of nums by adding one of the symbols + and - before each integer in nums and then concatenate all the integers. Return the number of different expressions that you can build, which evaluates to target.', constraints: '1 <= nums.length <= 20\n0 <= nums[i] <= 1000\n0 <= sum(nums[i]) <= 1000\n-1000 <= target <= 1000' },
    { id: 337, description: 'Given two strings s and t, return the number of distinct subsequences of s which equals t.\n\nThe answer is guaranteed to fit on a 32-bit signed integer.', constraints: '1 <= s.length, t.length <= 1000\ns and t consist of English letters.' },
    { id: 338, description: 'Given strings s1, s2, and s3, find whether s3 is formed by an interleaving of s1 and s2.\n\nAn interleaving of two strings s and t is a configuration where s and t are divided into n and m substrings respectively, such that the interleaving is s1 + t1 + s2 + t2 + s3 + t3 + ... or t1 + s1 + t2 + s2 + t3 + s3 + ...', constraints: '0 <= s1.length, s2.length <= 100\n0 <= s3.length <= 200\ns1, s2, and s3 consist of lowercase English letters.' },
    { id: 339, description: 'Given a string s, partition s such that every substring of the partition is a palindrome.\n\nReturn the minimum cuts needed for a palindrome partitioning of s.', constraints: '1 <= s.length <= 2000\ns consists of lowercase English letters only.' },
    { id: 340, description: 'Given an input string s and a pattern p, implement regular expression matching with support for . and *.\n\n. Matches any single character.\n* Matches zero or more of the preceding element.\n\nThe matching should cover the entire input string (not partial).', constraints: '1 <= s.length <= 20\n1 <= p.length <= 20\ns contains only lowercase English letters.\np contains only lowercase English letters, ., and *.' },
    { id: 341, description: 'Given an input string s and a pattern p, implement wildcard pattern matching with support for ? and *.\n\n? Matches any single character.\n* Matches any sequence of characters (including the empty sequence).\n\nThe matching should cover the entire input string (not partial).', constraints: '0 <= s.length, p.length <= 2000\ns contains only lowercase English letters.\np contains only lowercase English letters, ? or *.' },
    { id: 342, description: 'You are given an integer array cost where cost[i] is the cost of ith step on a staircase. Once you pay the cost, you can either climb one or two steps.\n\nYou can either start from the step with index 0, or the step with index 1.\n\nReturn the minimum cost to reach the top of the floor.', constraints: '2 <= cost.length <= 1000\n0 <= cost[i] <= 999' },
    { id: 343, description: 'Given an integer n, break it into the sum of k positive integers, where k >= 2, and maximize the product of those integers. Return the maximum product you can get.', constraints: '2 <= n <= 58' },
    { id: 344, description: 'Given an integer n, return the least number of perfect square numbers that sum to n. A perfect square is an integer that is the square of an integer.', constraints: '1 <= n <= 10^4' },
    { id: 345, description: 'The Fibonacci numbers, commonly denoted F(n) form a sequence, called the Fibonacci sequence, such that each number is the sum of the two preceding ones, starting from 0 and 1.\n\nGiven n, calculate F(n).', constraints: '0 <= n <= 30' },
    { id: 346, description: 'The Tribonacci sequence Tn is defined as follows: T0 = 0, T1 = 1, T2 = 1, and Tn+3 = Tn + Tn+1 + Tn+2 for n >= 0.\n\nGiven n, return the value of Tn.', constraints: '0 <= n <= 37\nThe answer is guaranteed to fit within a 32-bit integer.' },

    // ── Greedy (347-380) ──
    { id: 347, description: 'Given an array of non-negative integers nums, you are initially positioned at the first index of the array. Each element in the array represents your maximum jump length at that position. Your goal is to reach the last index in the minimum number of jumps.', constraints: '1 <= nums.length <= 10^4\n0 <= nums[i] <= 1000\nIt is guaranteed that you can reach nums[n - 1].' },
    { id: 348, description: 'There are n children standing in a line. Each child is assigned a rating value given in the integer array ratings. You are giving candies to these children subjected to the following requirements: Each child must have at least one candy. Children with a higher rating get more candies than their neighbors. Return the minimum number of candies you need to have to distribute the candies to the children.', constraints: 'n == ratings.length\n1 <= n <= 2 * 10^4\n0 <= ratings[i] <= 2 * 10^4' },
    { id: 349, description: 'There are n gas stations along a circular route, where the amount of gas at the ith station is gas[i]. You have a car with an unlimited gas tank and it costs cost[i] of gas to travel from the ith station to its next (i + 1)th station.\n\nReturn the starting gas station index if you can travel around the circuit once in the clockwise direction, otherwise return -1.', constraints: 'n == gas.length == cost.length\n1 <= n <= 10^5\n0 <= gas[i], cost[i] <= 10^4' },
    { id: 350, description: 'Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.', constraints: '1 <= intervals.length <= 10^4\nintervals[i].length == 2\n0 <= starti <= endi <= 10^4' },
    { id: 351, description: 'Given an array of meeting time intervals intervals where intervals[i] = [starti, endi], determine if a person could attend all meetings.', constraints: '0 <= intervals.length <= 10^4\nintervals[i].length == 2\n0 <= starti < endi <= 10^6' },
    { id: 352, description: 'Given a string s, rearrange the characters of s so that any two adjacent characters are not the same. Return any possible rearrangement of s or return "" if not possible.', constraints: '1 <= s.length <= 500\ns consists of lowercase English letters.' },
    { id: 353, description: 'Given a char array representing tasks CPU needs to do with a cooldown period n between two same tasks, return the minimum intervals the CPU will take to finish all tasks.', constraints: '1 <= tasks.length <= 10^4\ntasks[i] is an upper-case English letter.\n0 <= n <= 100' },
    { id: 354, description: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.', constraints: 'n == height.length\n1 <= n <= 2 * 10^4\n0 <= height[i] <= 10^5' },
    { id: 355, description: 'Given a string s which represents an expression, evaluate this expression and return its value. The expression can contain +, -, non-negative integers and empty spaces.', constraints: '1 <= s.length <= 3 * 10^5\ns consists of digits, +, -, and spaces.\ns represents a valid expression.' },
    { id: 356, description: 'Given two integers representing the numerator and denominator of a fraction, return the fraction in string format. If the fractional part is repeating, enclose the repeating part in parentheses.', constraints: '-2^31 <= numerator, denominator <= 2^31 - 1\ndenominator != 0' },
    { id: 357, description: 'Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string. Note: You must not use any built-in BigInteger library or convert the inputs to integer directly.', constraints: '1 <= num1.length, num2.length <= 200\nnum1 and num2 consist of digits only.\nBoth num1 and num2 do not contain any leading zero, except the number 0 itself.' },
    { id: 358, description: 'You are given a string num representing a large integer. Return the largest-valued odd number (as a string) that is a non-empty substring of num, or an empty string "" if no odd number exists.', constraints: '1 <= num.length <= 10^5\nnum only consists of digits and does not contain any leading zeros.' },
    { id: 359, description: 'Given a non-negative integer num, repeatedly add all its digits until the result has only one digit. Could you do it without any loop/recursion in O(1) runtime?', constraints: '0 <= num <= 2^31 - 1' },
    { id: 360, description: 'Convert a non-negative integer num to its English words representation.', constraints: '0 <= num <= 2^31 - 1' },
    { id: 361, description: 'Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules: Each row must contain the digits 1-9 without repetition. Each column must contain the digits 1-9 without repetition. Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.', constraints: 'board.length == 9\nboard[i].length == 9\nboard[i][j] is a digit 1-9 or .' },
    { id: 362, description: 'Given an m x n matrix, return true if the matrix is Toeplitz. A matrix is Toeplitz if every diagonal from top-left to bottom-right has the same elements.', constraints: 'm == matrix.length\nn == matrix[i].length\n1 <= m, n <= 20\n0 <= matrix[i][j] <= 99' },
    { id: 363, description: 'Given an integer columnNumber, return its corresponding column title as it appears in an Excel sheet. For example, A -> 1, B -> 2, ..., Z -> 26, AA -> 27, AB -> 28, ...', constraints: '1 <= columnNumber <= 2^31 - 1' },
    { id: 364, description: 'Given a string columnTitle that represents the column title as appears in an Excel sheet, return its corresponding column number.', constraints: '1 <= columnTitle.length <= 7\ncolumnTitle consists only of uppercase English letters.' },
    { id: 365, description: 'Given an integer n, return the number of trailing zeroes in n!.\n\nNote that n! = n * (n - 1) * (n - 2) * ... * 3 * 2 * 1.', constraints: '0 <= n <= 10^4' },
    { id: 366, description: 'Given an integer array nums, in which exactly two elements appear only once and all the other elements appear exactly twice. Find the two elements that appear only once. You can return the answer in any order.', constraints: '2 <= nums.length <= 3 * 10^4\n-2^31 <= nums[i] <= 2^31 - 1\nEach integer in nums will appear exactly twice, except for two integers which will appear exactly once.' },

    // ── Trie (367-376) ──
    { id: 367, description: 'A trie (pronounced as "try") or prefix tree is a tree data structure used to efficiently store and retrieve keys in a dataset of strings.\n\nImplement the Trie class:\n- Trie() Initializes the trie object.\n- void insert(String word) Inserts the string word into the trie.\n- boolean search(String word) Returns true if the string word is in the trie.\n- boolean startsWith(String prefix) Returns true if there is a previously inserted string word that has the prefix prefix.', constraints: '1 <= word.length, prefix.length <= 2000\nword and prefix consist only of lowercase English letters.\nAt most 3 * 10^4 calls in total will be made to insert, search, and startsWith.' },
    { id: 368, description: 'Design a data structure that supports adding new words and finding if a string matches any previously added string. Implement the WordDictionary class with addWord and search methods. The search method can search a literal word or a regular expression string containing only letters a-z or dots. A . means it can represent any one letter.', constraints: '1 <= word.length <= 25\nword in addWord consists of lowercase English letters.\nword in search consist of . or lowercase English letters.\nAt most 10^4 calls will be made to addWord and search.' },
    { id: 369, description: 'Given an integer array nums, return the maximum result of nums[i] XOR nums[j], where 0 <= i <= j < n.', constraints: '1 <= nums.length <= 2 * 10^5\n0 <= nums[i] <= 2^31 - 1' },
    { id: 370, description: 'Given a list of unique words, return all the pairs of the distinct indices (i, j) in the given list, so that the concatenation of the two words words[i] + words[j] is a palindrome.', constraints: '1 <= words.length <= 5000\n0 <= words[i].length <= 300\nwords[i] consists of lowercase English letters.' },
    { id: 371, description: 'Design a special dictionary that searches the words in it by a prefix and a suffix. Implement the WordFilter class with WordFilter(string[] words) constructor and f(string pref, string suff) method that returns the index of the word in the dictionary which has the prefix pref and suffix suff. If there is more than one valid index, return the largest.', constraints: '1 <= words.length <= 10^4\n1 <= words[i].length <= 7\n1 <= pref.length, suff.length <= 7\nwords[i], pref and suff consist of lowercase English letters only.\nAt most 10^4 calls will be made to the function f.' },
    { id: 372, description: 'Given an array of strings words, return all words in words that is a substring of some other word. String words[i] is a substring of words[j] if words[i] can be obtained by deleting some characters (possibly zero) from the left and/or right side of words[j].', constraints: '1 <= words.length <= 100\n1 <= words[i].length <= 30\nwords[i] contains only lowercase English letters.\nAll the strings of words are unique.' },
    { id: 373, description: 'In English, we have a concept called root, which can be followed by some other word to form another longer word - lets call this word successor. For example, when the root "an" is followed by the successor word "other", we can form a new word "another". Given a dictionary consisting of many roots and a sentence consisting of words separated by spaces, replace all the successors in the sentence with the root forming it. If a successor can be replaced by more than one root, replace it with the root that has the shortest length. Return the sentence after the replacement.', constraints: '1 <= dictionary.length <= 1000\n1 <= dictionary[i].length <= 100\ndictionary[i] consists of only lower-case letters.\n1 <= sentence.length <= 10^6\nsentence consists of only lower-case letters and spaces.\nThe number of words in sentence is in the range [1, 1000].\nThe length of each word in sentence is in the range [1, 1000].\nEvery two consecutive words in sentence will be separated by exactly one space.' },
    { id: 374, description: 'A concatenated word is defined as a string that is comprised entirely of at least two shorter words (not necessarily distinct) in the given array of words. Given an array of strings words (without duplicates), return all the concatenated words in the given list of words.', constraints: '1 <= words.length <= 10^4\n1 <= words[i].length <= 30\nwords[i] consists of only lowercase English letters.\nAll the strings of words are unique.' },
    { id: 375, description: 'Given a string s, return the number of distinct non-empty subsequences of s. Since the answer may be very large, return it modulo 10^9 + 7.', constraints: '1 <= s.length <= 2000\ns consists of lowercase English letters.' },
    { id: 376, description: 'Design a map that allows you to do the following: Maps a string key to a given value, Returns the sum of the values that have a key with a prefix equal to a given string. Implement the MapSum class.', constraints: '1 <= key.length, prefix.length <= 50\nkey and prefix consist of only lowercase English letters.\n1 <= val <= 1000\nAt most 50 calls will be made to insert and sum.' },

    // ── Bit Manipulation (377-390) ──
    { id: 377, description: 'Given an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1s in the binary representation of i.', constraints: '0 <= n <= 10^5' },
    { id: 378, description: 'Reverse bits of a given 32 bits unsigned integer.', constraints: 'The input must be a binary string of length 32.' },
    { id: 379, description: 'Write a function that takes the binary representation of a positive integer and returns the number of set bits it has (also known as the Hamming weight).', constraints: '1 <= n <= 2^31 - 1' },
    { id: 380, description: 'Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.\n\nYou must implement a solution with a linear runtime complexity and use only constant extra space.', constraints: '1 <= nums.length <= 3 * 10^4\n-3 * 10^4 <= nums[i] <= 3 * 10^4\nEach element in the array appears twice except for one element which appears only once.' },
    { id: 381, description: 'Given an integer array nums where every element appears three times except for one, which appears exactly once. Find the single element and return it.\n\nYou must implement a solution with a linear runtime complexity and use only constant extra space.', constraints: '1 <= nums.length <= 3 * 10^4\n-2^31 <= nums[i] <= 2^31 - 1\nEach element in nums appears exactly three times except for one element which appears exactly once.' },
    { id: 382, description: 'Given two integers a and b, return the sum of the two integers without using the operators + and -.', constraints: '-1000 <= a, b <= 1000' },
    { id: 383, description: 'The Hamming distance between two integers is the number of positions at which the corresponding bits are different. Given two integers x and y, return the Hamming distance between them.', constraints: '0 <= x, y <= 2^31 - 1' },
    { id: 384, description: 'Given an integer n, return true if it is a power of two. Otherwise, return false.\n\nAn integer n is a power of two if there exists an integer x such that n == 2^x.', constraints: '-2^31 <= n <= 2^31 - 1' },
    { id: 385, description: 'Given an integer n, return true if it is a power of four. Otherwise, return false.\n\nAn integer n is a power of four if there exists an integer x such that n == 4^x.', constraints: '-2^31 <= n <= 2^31 - 1' },
    { id: 386, description: 'Given an array nums of size n, return the majority element. The majority element is the element that appears more than n / 2 times. You may assume that the majority element always exists in the array.', constraints: 'n == nums.length\n1 <= n <= 5 * 10^4\n-10^9 <= nums[i] <= 10^9' },
    { id: 387, description: 'Write a function that takes an unsigned integer and returns the number of 1 bits it has (also known as the Hamming weight or popcount).', constraints: '1 <= n <= 2^31 - 1' },
    { id: 388, description: 'Given a non-negative integer num, for every number i in the range 0 <= i <= num, calculate the number of 1s in their binary representation and return them as an array.', constraints: '0 <= num <= 10^5' },
    { id: 389, description: 'Given two strings s and t which consist of only lowercase letters. String t is generated by random shuffling string s and then adding one more letter at a random position. Return the letter that was added to t.', constraints: '0 <= s.length <= 1000\nt.length == s.length + 1\ns and t consist of lowercase English letters.' },
    { id: 390, description: 'Given an integer array nums, find the subarray with the largest sum, and return its sum. The subarray must contain at least one element.', constraints: '1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4' },

    // ── Hash Map / String / Math (391-431) ──
    { id: 391, description: 'Given two strings s and t, determine if they are isomorphic. Two strings s and t are isomorphic if the characters in s can be replaced to get t.\n\nAll occurrences of a character must be replaced with another character while preserving the order of characters. No two characters may map to the same character, but a character may map to itself.', constraints: '1 <= s.length <= 5 * 10^4\nt.length == s.length\ns and t consist of any valid ascii character.' },
    { id: 392, description: 'Given an array of strings strs, group the anagrams together. You can return the answer in any order.\n\nAn Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.', constraints: '1 <= strs.length <= 10^4\n0 <= strs[i].length <= 100\nstrs[i] consists of lowercase English letters.' },
    { id: 393, description: 'Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1.', constraints: '1 <= s.length <= 10^5\ns consists of only lowercase English letters.' },
    { id: 394, description: 'Given two strings ransomNote and magazine, return true if ransomNote can be constructed by using the letters from magazine and false otherwise.\n\nEach letter in magazine can only be used once in ransomNote.', constraints: '1 <= ransomNote.length, magazine.length <= 10^5\nransomNote and magazine consist of lowercase English letters.' },
    { id: 395, description: 'Design a data structure that supports insert, delete, and getRandom in average O(1) time.\n\ngetRandom should return a random element from the current set of elements (each element must have the same probability of being returned).', constraints: '-2^31 <= val <= 2^31 - 1\nAt most 2 * 10^5 calls will be made to insert, remove, and getRandom.\nThere will be at least one element in the data structure when getRandom is called.' },
    { id: 396, description: 'Implement a trie with insert, search, and startsWith methods.\n\nA trie (prefix tree) is a tree data structure used to efficiently store and retrieve keys in a dataset of strings.', constraints: '1 <= word.length, prefix.length <= 2000\nword and prefix consist only of lowercase English letters.\nAt most 3 * 10^4 total calls will be made to insert, search, and startsWith.' },
    { id: 397, description: 'Given a pattern and a string s, find if s follows the same pattern. Here follow means a full match, such that there is a bijection between a letter in pattern and a non-empty word in s.', constraints: '1 <= pattern.length <= 300\n1 <= s.length <= 3000\npattern contains only lower-case English letters.\ns contains only lowercase English letters and spaces.\ns does not contain any leading or trailing spaces.\nAll the words in s are separated by a single space.' },
    { id: 398, description: 'Given an integer array nums, return the maximum result of nums[i] XOR nums[j], where 0 <= i <= j < n.', constraints: '1 <= nums.length <= 2 * 10^5\n0 <= nums[i] <= 2^31 - 1' },
    { id: 399, description: 'Given a string s, find the length of the longest substring without repeating characters.', constraints: '0 <= s.length <= 5 * 10^4\ns consists of English letters, digits, symbols and spaces.' },
    { id: 400, description: 'Given a string s, return the longest palindromic substring in s.', constraints: '1 <= s.length <= 1000\ns consist of only digits and English letters.' },
    { id: 401, description: 'Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-2^31, 2^31 - 1], then return 0.', constraints: '-2^31 <= x <= 2^31 - 1' },
    { id: 402, description: 'Given a string s, return true if s is a palindrome, or false otherwise. For palindrome checking, only consider alphanumeric characters and ignore cases.', constraints: '1 <= s.length <= 2 * 10^5\ns consists only of printable ASCII characters.' },
    { id: 403, description: 'Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M. Given a roman numeral, convert it to an integer.', constraints: '1 <= s.length <= 15\ns contains only the characters (I, V, X, L, C, D, M).\nIt is guaranteed that s is a valid roman numeral in the range [1, 3999].' },
    { id: 404, description: 'Given an integer, convert it to a roman numeral.', constraints: '1 <= num <= 3999' },
    { id: 405, description: 'Find all valid combinations of k numbers that sum up to n such that only numbers 1 through 9 are used, and each number is used at most once. Return a list of all possible valid combinations.', constraints: '2 <= k <= 9\n1 <= n <= 60' },
    { id: 406, description: 'Given a string s, check if it can be constructed by taking a substring of it and appending multiple copies of the substring together.', constraints: '1 <= s.length <= 10^4\ns consists of lowercase English letters.' },
    { id: 407, description: 'Given a 0-indexed n x n integer matrix grid, return the number of pairs (ri, cj) such that row ri and column cj are equal. A row and column pair is considered equal if they contain the same elements in the same order (i.e., an equal array).', constraints: 'n == grid.length == grid[i].length\n1 <= n <= 200\n1 <= grid[i][j] <= 10^5' },
    { id: 408, description: 'Given a string s, sort it in decreasing order based on the frequency of the characters. The frequency of a character is the number of times it appears in the string. Return the sorted string.', constraints: '1 <= s.length <= 5 * 10^5\ns consists of uppercase and lowercase English letters and digits.' },
    { id: 409, description: 'Given an integer array nums sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once. The relative order of the elements should be kept the same.', constraints: '1 <= nums.length <= 3 * 10^4\n-100 <= nums[i] <= 100\nnums is sorted in non-decreasing order.' },
    { id: 410, description: 'Given a string s and an integer k, return the length of the longest substring of s such that the frequency of each character in this substring is greater than or equal to k.', constraints: '1 <= s.length <= 10^4\ns consists of only lowercase English letters.\n1 <= k <= 10^5' },
    { id: 411, description: 'Given an m x n 2D binary grid grid which represents a map of 1s (land) and 0s (water), return the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.', constraints: 'm == grid.length\nn == grid[i].length\n1 <= m, n <= 300\ngrid[i][j] is 0 or 1.' },
    { id: 412, description: 'Given the root of a binary tree, return the level order traversal of its nodes values. (i.e., from left to right, level by level).', constraints: '0 <= number of nodes <= 2000\n-1000 <= Node.val <= 1000' },
    { id: 413, description: 'You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.', constraints: '0 <= number of nodes <= 100\n0 <= Node.val <= 9\nIt is guaranteed that the list represents a number that does not have leading zeros.' },
    { id: 414, description: 'Given the head of a singly linked list, reverse the list, and return the reversed list.', constraints: '0 <= number of nodes <= 5000\n-5000 <= Node.val <= 5000' },
    { id: 415, description: 'Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target. You may return the combinations in any order. The same number may be chosen unlimited number of times.', constraints: '1 <= candidates.length <= 30\n2 <= candidates[i] <= 40\nAll elements of candidates are distinct.\n1 <= target <= 40' },
    { id: 416, description: 'Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.', constraints: '0 <= digits.length <= 4\ndigits[i] is a digit in the range [2, 9].' },
    { id: 417, description: 'Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.', constraints: '1 <= k <= number of nodes <= 10^4\n0 <= Node.val <= 10^4' },
    { id: 418, description: 'Given an encoded string, return its decoded string. The encoding rule is: k[encoded_string], where the encoded_string inside the square brackets is being repeated exactly k times.', constraints: '1 <= s.length <= 30\ns consists of lowercase English letters, digits, and square brackets [].\nAll the integers in s are in the range [1, 300].' },
    { id: 419, description: 'We are given an array asteroids of integers representing asteroids in a row. For each asteroid, the absolute value represents its size, and the sign represents its direction. Find out the state of the asteroids after all collisions.', constraints: '2 <= asteroids.length <= 10^4\n-1000 <= asteroids[i] <= 1000\nasteroids[i] != 0' },
    { id: 420, description: 'Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.', constraints: '1 <= nums.length <= 10^5\n-10^9 <= nums[i] <= 10^9' },
    { id: 421, description: 'Given a binary tree, determine if it is a valid binary search tree (BST).', constraints: '1 <= number of nodes <= 10^4\n-2^31 <= Node.val <= 2^31 - 1' },
    { id: 422, description: 'Given a string s containing just the characters (, ), {, }, [ and ], determine if the input string is valid. An input string is valid if open brackets are closed by the same type of brackets and in the correct order.', constraints: '1 <= s.length <= 10^4\ns consists of parentheses only ()[]{}.' },
    { id: 423, description: 'Given an integer array nums, move all 0s to the end of it while maintaining the relative order of the non-zero elements. Note that you must do this in-place without making a copy of the array.', constraints: '1 <= nums.length <= 10^4\n-2^31 <= nums[i] <= 2^31 - 1' },
    { id: 424, description: 'Given a string s, find the length of the longest substring without repeating characters.', constraints: '0 <= s.length <= 5 * 10^4\ns consists of English letters, digits, symbols and spaces.' },
    { id: 425, description: 'Given a string s, return the minimum number of characters you need to delete to make s good. A string is good if there are no two different characters in s that have the same frequency.', constraints: '1 <= s.length <= 10^5\ns contains only lowercase English letters.' },
    { id: 426, description: 'Given an m x n matrix, return all elements of the matrix in spiral order.', constraints: 'm == matrix.length\nn == matrix[i].length\n1 <= m, n <= 10\n-100 <= matrix[i][j] <= 100' },
    { id: 427, description: 'Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.', constraints: '1 <= intervals.length <= 10^4\nintervals[i].length == 2\n0 <= starti <= endi <= 10^4' },
    { id: 428, description: 'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays. The overall run time complexity should be O(log (m+n)).', constraints: 'nums1.length == m\nnums2.length == n\n0 <= m <= 1000\n0 <= n <= 1000\n1 <= m + n <= 2000\n-10^6 <= nums1[i], nums2[i] <= 10^6' },
    { id: 429, description: 'Given a string s, return the longest palindromic substring in s.', constraints: '1 <= s.length <= 1000\ns consist of only digits and English letters.' },
    { id: 430, description: 'Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer (similar to C/Cs atoi function). Read in and ignore any leading whitespace. Check if the next character is - or + and read it. Read integer and stop at non-digit. Clamp the integer to the 32-bit signed integer range.', constraints: '0 <= s.length <= 200\ns consists of English letters (lower-case and upper-case), digits (0-9), space, +, -, and .' },
    { id: 431, description: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.', constraints: 'n == height.length\n1 <= n <= 2 * 10^4\n0 <= height[i] <= 10^5' },
];

async function run() {
    console.log('Batch 5: Updating ' + updates.length + ' problems...');
    let ok = 0, fail = 0;
    for (const u of updates) {
        const { error } = await supabaseAdmin.from('problems').update({
            description: u.description, constraints: u.constraints
        }).eq('id', u.id);
        if (error) { console.error('FAIL [' + u.id + ']: ' + error.message); fail++; }
        else { ok++; }
    }
    console.log('Batch 5 done: ' + ok + ' ok, ' + fail + ' fail');
}
run().catch(console.error);
