import { supabaseAdmin } from '../db/supabaseClient.js';

const solutions = {
    // Linked List problems
    82: { javascript: `function reorderList(head) { let s=head,f=head; while(f.next&&f.next.next){s=s.next;f=f.next.next;} let prev=null,curr=s.next; s.next=null; while(curr){const t=curr.next;curr.next=prev;prev=curr;curr=t;} let p1=head,p2=prev; while(p2){const t1=p1.next,t2=p2.next;p1.next=p2;p2.next=t1;p1=t1;p2=t2;} }`, java: `class Solution { public void reorderList(ListNode head) { ListNode s=head,f=head; while(f.next!=null&&f.next.next!=null){s=s.next;f=f.next.next;} ListNode prev=null,curr=s.next; s.next=null; while(curr!=null){ListNode t=curr.next;curr.next=prev;prev=curr;curr=t;} ListNode p1=head,p2=prev; while(p2!=null){ListNode t1=p1.next,t2=p2.next;p1.next=p2;p2.next=t1;p1=t1;p2=t2;} } }`, cpp: `class Solution { public: void reorderList(ListNode* head) { auto s=head,f=head; while(f->next&&f->next->next){s=s->next;f=f->next->next;} ListNode*prev=nullptr,*curr=s->next; s->next=nullptr; while(curr){auto t=curr->next;curr->next=prev;prev=curr;curr=t;} auto p1=head,p2=prev; while(p2){auto t1=p1->next,t2=p2->next;p1->next=p2;p2->next=t1;p1=t1;p2=t2;} } };` },
    85: { javascript: `function rotateRight(head, k) { if(!head||!head.next||k===0) return head; let len=1,tail=head; while(tail.next){tail=tail.next;len++;} k%=len; if(k===0) return head; tail.next=head; let curr=head; for(let i=0;i<len-k-1;i++) curr=curr.next; const newHead=curr.next; curr.next=null; return newHead; }`, java: `class Solution { public ListNode rotateRight(ListNode head, int k) { if(head==null||head.next==null||k==0) return head; int len=1; ListNode tail=head; while(tail.next!=null){tail=tail.next;len++;} k%=len; if(k==0) return head; tail.next=head; ListNode curr=head; for(int i=0;i<len-k-1;i++) curr=curr.next; ListNode nh=curr.next; curr.next=null; return nh; } }`, cpp: `class Solution { public: ListNode* rotateRight(ListNode* head, int k) { if(!head||!head->next||!k) return head; int len=1; auto tail=head; while(tail->next){tail=tail->next;len++;} k%=len; if(!k) return head; tail->next=head; auto curr=head; for(int i=0;i<len-k-1;i++) curr=curr->next; auto nh=curr->next; curr->next=nullptr; return nh; } };` },
    121: { javascript: `function isHappy(n) { const seen=new Set(); while(n!==1&&!seen.has(n)){seen.add(n);let s=0;while(n){s+=(n%10)**2;n=Math.floor(n/10);}n=s;} return n===1; }`, java: `class Solution { public boolean isHappy(int n) { Set<Integer> seen=new HashSet<>(); while(n!=1&&!seen.contains(n)){seen.add(n);int s=0;while(n>0){s+=(n%10)*(n%10);n/=10;}n=s;} return n==1; } }`, cpp: `class Solution { public: bool isHappy(int n) { unordered_set<int> seen; while(n!=1&&!seen.count(n)){seen.insert(n);int s=0;while(n){s+=(n%10)*(n%10);n/=10;}n=s;} return n==1; } };` },
    122: { javascript: `function circularArrayLoop(nums) { const n=nums.length; for(let i=0;i<n;i++){let s=i,f=i; const dir=nums[i]>0; do{s=((s+nums[s])%n+n)%n;f=((f+nums[f])%n+n)%n;if((nums[f]>0)!==dir)break;f=((f+nums[f])%n+n)%n;if((nums[f]>0)!==dir)break;}while(s!==f); if(s===f&&s!==((s+nums[s])%n+n)%n) return true;} return false; }`, java: `class Solution { public boolean circularArrayLoop(int[] nums) { int n=nums.length; for(int i=0;i<n;i++){int s=i,f=i;boolean dir=nums[i]>0; do{s=next(nums,s);f=next(nums,f);if((nums[f]>0)!=dir)break;f=next(nums,f);if((nums[f]>0)!=dir)break;}while(s!=f); if(s==f&&s!=next(nums,s))return true;} return false; } int next(int[] nums,int i){int n=nums.length;return((i+nums[i])%n+n)%n;} }`, cpp: `class Solution { public: bool circularArrayLoop(vector<int>& nums) { int n=nums.size(); auto nxt=[&](int i){return((i+nums[i])%n+n)%n;}; for(int i=0;i<n;i++){int s=i,f=i;bool dir=nums[i]>0; do{s=nxt(s);f=nxt(f);if((nums[f]>0)!=dir)break;f=nxt(f);if((nums[f]>0)!=dir)break;}while(s!=f); if(s==f&&s!=nxt(s))return true;} return false; } };` },
    123: { javascript: `function isPalindrome(head) { let s=head,f=head; while(f&&f.next){s=s.next;f=f.next.next;} let prev=null; while(s){const t=s.next;s.next=prev;prev=s;s=t;} while(prev){if(prev.val!==head.val)return false;prev=prev.next;head=head.next;} return true; }`, java: `class Solution { public boolean isPalindrome(ListNode head) { ListNode s=head,f=head; while(f!=null&&f.next!=null){s=s.next;f=f.next.next;} ListNode prev=null; while(s!=null){ListNode t=s.next;s.next=prev;prev=s;s=t;} while(prev!=null){if(prev.val!=head.val)return false;prev=prev.next;head=head.next;} return true; } }`, cpp: `class Solution { public: bool isPalindrome(ListNode* head) { auto s=head,f=head; while(f&&f->next){s=s->next;f=f->next->next;} ListNode*prev=nullptr; while(s){auto t=s->next;s->next=prev;prev=s;s=t;} while(prev){if(prev->val!=head->val)return false;prev=prev->next;head=head->next;} return true; } };` },
    124: { javascript: `function reorderList(head) { let s=head,f=head; while(f.next&&f.next.next){s=s.next;f=f.next.next;} let prev=null,curr=s.next;s.next=null; while(curr){const t=curr.next;curr.next=prev;prev=curr;curr=t;} let p1=head,p2=prev; while(p2){const t1=p1.next,t2=p2.next;p1.next=p2;p2.next=t1;p1=t1;p2=t2;} }`, java: `class Solution { public void reorderList(ListNode head) { ListNode s=head,f=head; while(f.next!=null&&f.next.next!=null){s=s.next;f=f.next.next;} ListNode prev=null,curr=s.next;s.next=null; while(curr!=null){ListNode t=curr.next;curr.next=prev;prev=curr;curr=t;} ListNode p1=head,p2=prev; while(p2!=null){ListNode t1=p1.next,t2=p2.next;p1.next=p2;p2.next=t1;p1=t1;p2=t2;} } }`, cpp: `class Solution { public: void reorderList(ListNode* head) { auto s=head,f=head; while(f->next&&f->next->next){s=s->next;f=f->next->next;} ListNode*prev=nullptr;auto curr=s->next;s->next=nullptr; while(curr){auto t=curr->next;curr->next=prev;prev=curr;curr=t;} auto p1=head,p2=prev; while(p2){auto t1=p1->next,t2=p2->next;p1->next=p2;p2->next=t1;p1=t1;p2=t2;} } };` },
    125: { javascript: `function rotateRight(head, k) { if(!head||!head.next) return head; let len=1,tail=head; while(tail.next){tail=tail.next;len++;} k%=len; if(!k) return head; tail.next=head; let curr=head; for(let i=0;i<len-k-1;i++) curr=curr.next; const nh=curr.next; curr.next=null; return nh; }`, java: `class Solution { public ListNode rotateRight(ListNode head, int k) { if(head==null||head.next==null) return head; int len=1; ListNode tail=head; while(tail.next!=null){tail=tail.next;len++;} k%=len; if(k==0) return head; tail.next=head; ListNode curr=head; for(int i=0;i<len-k-1;i++) curr=curr.next; ListNode nh=curr.next; curr.next=null; return nh; } }`, cpp: `class Solution { public: ListNode* rotateRight(ListNode* head, int k) { if(!head||!head->next) return head; int len=1; auto tail=head; while(tail->next){tail=tail->next;len++;} k%=len; if(!k) return head; tail->next=head; auto curr=head; for(int i=0;i<len-k-1;i++) curr=curr->next; auto nh=curr->next; curr->next=nullptr; return nh; } };` },
    126: { javascript: `function deleteMiddle(head) { if(!head.next) return null; let s=head,f=head,prev=null; while(f&&f.next){prev=s;s=s.next;f=f.next.next;} prev.next=s.next; return head; }`, java: `class Solution { public ListNode deleteMiddle(ListNode head) { if(head.next==null) return null; ListNode s=head,f=head,prev=null; while(f!=null&&f.next!=null){prev=s;s=s.next;f=f.next.next;} prev.next=s.next; return head; } }`, cpp: `class Solution { public: ListNode* deleteMiddle(ListNode* head) { if(!head->next) return nullptr; auto s=head,f=head; ListNode*prev=nullptr; while(f&&f->next){prev=s;s=s->next;f=f->next->next;} prev->next=s->next; return head; } };` },
    127: { javascript: `function pairSum(head) { let s=head,f=head; while(f&&f.next){s=s.next;f=f.next.next;} let prev=null; while(s){const t=s.next;s.next=prev;prev=s;s=t;} let max=0; while(prev){max=Math.max(max,head.val+prev.val);head=head.next;prev=prev.next;} return max; }`, java: `class Solution { public int pairSum(ListNode head) { ListNode s=head,f=head; while(f!=null&&f.next!=null){s=s.next;f=f.next.next;} ListNode prev=null; while(s!=null){ListNode t=s.next;s.next=prev;prev=s;s=t;} int max=0; while(prev!=null){max=Math.max(max,head.val+prev.val);head=head.next;prev=prev.next;} return max; } }`, cpp: `class Solution { public: int pairSum(ListNode* head) { auto s=head,f=head; while(f&&f->next){s=s->next;f=f->next->next;} ListNode*prev=nullptr; while(s){auto t=s->next;s->next=prev;prev=s;s=t;} int mx=0; while(prev){mx=max(mx,head->val+prev->val);head=head->next;prev=prev->next;} return mx; } };` },
    129: { javascript: `function oddEvenList(head) { if(!head||!head.next) return head; let odd=head,even=head.next,evenHead=even; while(even&&even.next){odd.next=even.next;odd=odd.next;even.next=odd.next;even=even.next;} odd.next=evenHead; return head; }`, java: `class Solution { public ListNode oddEvenList(ListNode head) { if(head==null||head.next==null) return head; ListNode odd=head,even=head.next,eh=even; while(even!=null&&even.next!=null){odd.next=even.next;odd=odd.next;even.next=odd.next;even=even.next;} odd.next=eh; return head; } }`, cpp: `class Solution { public: ListNode* oddEvenList(ListNode* head) { if(!head||!head->next) return head; auto odd=head,even=head->next,eh=even; while(even&&even->next){odd->next=even->next;odd=odd->next;even->next=odd->next;even=even->next;} odd->next=eh; return head; } };` },
    131: { javascript: `function splitListToParts(head, k) { let len=0,curr=head; while(curr){len++;curr=curr.next;} const size=Math.floor(len/k),extra=len%k; const res=[]; curr=head; for(let i=0;i<k;i++){res.push(curr);const partSize=size+(i<extra?1:0);for(let j=1;j<partSize;j++)curr=curr.next;if(curr){const next=curr.next;curr.next=null;curr=next;}} return res; }`, java: `class Solution { public ListNode[] splitListToParts(ListNode head, int k) { int len=0; ListNode curr=head; while(curr!=null){len++;curr=curr.next;} int size=len/k,extra=len%k; ListNode[] res=new ListNode[k]; curr=head; for(int i=0;i<k;i++){res[i]=curr;int ps=size+(i<extra?1:0);for(int j=1;j<ps;j++)curr=curr.next;if(curr!=null){ListNode next=curr.next;curr.next=null;curr=next;}} return res; } }`, cpp: `class Solution { public: vector<ListNode*> splitListToParts(ListNode* head, int k) { int len=0; auto curr=head; while(curr){len++;curr=curr->next;} int size=len/k,extra=len%k; vector<ListNode*> res(k,nullptr); curr=head; for(int i=0;i<k;i++){res[i]=curr;int ps=size+(i<extra?1:0);for(int j=1;j<ps;j++)curr=curr->next;if(curr){auto next=curr->next;curr->next=nullptr;curr=next;}} return res; } };` },
    135: { javascript: `function swapPairs(head) { if(!head||!head.next) return head; const newHead=head.next; head.next=swapPairs(newHead.next); newHead.next=head; return newHead; }`, java: `class Solution { public ListNode swapPairs(ListNode head) { if(head==null||head.next==null) return head; ListNode nh=head.next; head.next=swapPairs(nh.next); nh.next=head; return nh; } }`, cpp: `class Solution { public: ListNode* swapPairs(ListNode* head) { if(!head||!head->next) return head; auto nh=head->next; head->next=swapPairs(nh->next); nh->next=head; return nh; } };` },
    139: { javascript: `function mergeKLists(lists) { if(!lists.length) return null; while(lists.length>1){const merged=[]; for(let i=0;i<lists.length;i+=2){const l1=lists[i],l2=i+1<lists.length?lists[i+1]:null;merged.push(merge2(l1,l2));}lists=merged;} return lists[0]; function merge2(l1,l2){const d={next:null};let c=d;while(l1&&l2){if(l1.val<=l2.val){c.next=l1;l1=l1.next;}else{c.next=l2;l2=l2.next;}c=c.next;}c.next=l1||l2;return d.next;} }`, java: `class Solution { public ListNode mergeKLists(ListNode[] lists) { if(lists.length==0) return null; PriorityQueue<ListNode> pq=new PriorityQueue<>((a,b)->a.val-b.val); for(ListNode l:lists) if(l!=null) pq.offer(l); ListNode dummy=new ListNode(0),curr=dummy; while(!pq.isEmpty()){ListNode n=pq.poll();curr.next=n;curr=curr.next;if(n.next!=null)pq.offer(n.next);} return dummy.next; } }`, cpp: `class Solution { public: ListNode* mergeKLists(vector<ListNode*>& lists) { auto cmp=[](ListNode*a,ListNode*b){return a->val>b->val;}; priority_queue<ListNode*,vector<ListNode*>,decltype(cmp)> pq(cmp); for(auto l:lists) if(l) pq.push(l); ListNode dummy(0); auto curr=&dummy; while(!pq.empty()){auto n=pq.top();pq.pop();curr->next=n;curr=curr->next;if(n->next)pq.push(n->next);} return dummy.next; } };` },
    140: { javascript: `function copyRandomList(head) { if(!head) return null; let curr=head; while(curr){const copy={val:curr.val,next:curr.next,random:null};curr.next=copy;curr=copy.next;} curr=head; while(curr){if(curr.random) curr.next.random=curr.random.next;curr=curr.next.next;} const dummy={next:null};let tail=dummy;curr=head; while(curr){tail.next=curr.next;tail=tail.next;curr.next=curr.next.next;curr=curr.next;} return dummy.next; }`, java: `class Solution { public Node copyRandomList(Node head) { if(head==null) return null; Node curr=head; while(curr!=null){Node copy=new Node(curr.val);copy.next=curr.next;curr.next=copy;curr=copy.next;} curr=head; while(curr!=null){if(curr.random!=null) curr.next.random=curr.random.next;curr=curr.next.next;} Node dummy=new Node(0);Node tail=dummy;curr=head; while(curr!=null){tail.next=curr.next;tail=tail.next;curr.next=curr.next.next;curr=curr.next;} return dummy.next; } }`, cpp: `class Solution { public: Node* copyRandomList(Node* head) { if(!head) return nullptr; auto curr=head; while(curr){auto copy=new Node(curr->val);copy->next=curr->next;curr->next=copy;curr=copy->next;} curr=head; while(curr){if(curr->random) curr->next->random=curr->random->next;curr=curr->next->next;} Node dummy(0);auto tail=&dummy;curr=head; while(curr){tail->next=curr->next;tail=tail->next;curr->next=curr->next->next;curr=curr->next;} return dummy.next; } };` },
    // Binary Search
    187: { javascript: `function search(nums, target) { let lo=0,hi=nums.length-1; while(lo<=hi){const m=lo+((hi-lo)>>1);if(nums[m]===target)return m;if(nums[m]<target)lo=m+1;else hi=m-1;} return -1; }`, java: `class Solution { public int search(int[] nums, int target) { int lo=0,hi=nums.length-1; while(lo<=hi){int m=lo+(hi-lo)/2;if(nums[m]==target)return m;if(nums[m]<target)lo=m+1;else hi=m-1;} return -1; } }`, cpp: `class Solution { public: int search(vector<int>& nums, int target) { int lo=0,hi=nums.size()-1; while(lo<=hi){int m=lo+(hi-lo)/2;if(nums[m]==target)return m;if(nums[m]<target)lo=m+1;else hi=m-1;} return -1; } };` },
    188: { javascript: `function searchInsert(nums, target) { let lo=0,hi=nums.length; while(lo<hi){const m=lo+((hi-lo)>>1);if(nums[m]<target)lo=m+1;else hi=m;} return lo; }`, java: `class Solution { public int searchInsert(int[] nums, int target) { int lo=0,hi=nums.length; while(lo<hi){int m=lo+(hi-lo)/2;if(nums[m]<target)lo=m+1;else hi=m;} return lo; } }`, cpp: `class Solution { public: int searchInsert(vector<int>& nums, int target) { return lower_bound(nums.begin(),nums.end(),target)-nums.begin(); } };` },
    189: { javascript: `function firstBadVersion(n) { let lo=1,hi=n; while(lo<hi){const m=lo+((hi-lo)>>1);if(isBadVersion(m))hi=m;else lo=m+1;} return lo; }`, java: `public class Solution extends VersionControl { public int firstBadVersion(int n) { int lo=1,hi=n; while(lo<hi){int m=lo+(hi-lo)/2;if(isBadVersion(m))hi=m;else lo=m+1;} return lo; } }`, cpp: `class Solution { public: int firstBadVersion(int n) { int lo=1,hi=n; while(lo<hi){int m=lo+(hi-lo)/2;if(isBadVersion(m))hi=m;else lo=m+1;} return lo; } };` },
    191: { javascript: `function isPerfectSquare(num) { let lo=1,hi=num; while(lo<=hi){const m=lo+Math.floor((hi-lo)/2);if(m===num/m&&num%m===0)return true;if(m<num/m)lo=m+1;else hi=m-1;} return false; }`, java: `class Solution { public boolean isPerfectSquare(int num) { long lo=1,hi=num; while(lo<=hi){long m=lo+(hi-lo)/2;if(m*m==num)return true;if(m*m<num)lo=m+1;else hi=m-1;} return false; } }`, cpp: `class Solution { public: bool isPerfectSquare(int num) { long lo=1,hi=num; while(lo<=hi){long m=lo+(hi-lo)/2;if(m*m==num)return true;if(m*m<num)lo=m+1;else hi=m-1;} return false; } };` },
    192: { javascript: `function guessNumber(n) { let lo=1,hi=n; while(lo<=hi){const m=lo+Math.floor((hi-lo)/2);const r=guess(m);if(r===0)return m;if(r===-1)hi=m-1;else lo=m+1;} return lo; }`, java: `public class Solution extends GuessGame { public int guessNumber(int n) { int lo=1,hi=n; while(lo<=hi){int m=lo+(hi-lo)/2;int r=guess(m);if(r==0)return m;if(r==-1)hi=m-1;else lo=m+1;} return lo; } }`, cpp: `class Solution { public: int guessNumber(int n) { int lo=1,hi=n; while(lo<=hi){int m=lo+(hi-lo)/2;int r=guess(m);if(r==0)return m;if(r==-1)hi=m-1;else lo=m+1;} return lo; } };` },
    195: { javascript: `function findPeakElement(nums) { let lo=0,hi=nums.length-1; while(lo<hi){const m=lo+((hi-lo)>>1);if(nums[m]>nums[m+1])hi=m;else lo=m+1;} return lo; }`, java: `class Solution { public int findPeakElement(int[] nums) { int lo=0,hi=nums.length-1; while(lo<hi){int m=lo+(hi-lo)/2;if(nums[m]>nums[m+1])hi=m;else lo=m+1;} return lo; } }`, cpp: `class Solution { public: int findPeakElement(vector<int>& nums) { int lo=0,hi=nums.size()-1; while(lo<hi){int m=lo+(hi-lo)/2;if(nums[m]>nums[m+1])hi=m;else lo=m+1;} return lo; } };` },
    196: { javascript: `function search(nums, target) { let lo=0,hi=nums.length-1; while(lo<=hi){const m=lo+((hi-lo)>>1);if(nums[m]===target)return m;if(nums[lo]<=nums[m]){if(target>=nums[lo]&&target<nums[m])hi=m-1;else lo=m+1;}else{if(target>nums[m]&&target<=nums[hi])lo=m+1;else hi=m-1;}} return -1; }`, java: `class Solution { public int search(int[] nums, int target) { int lo=0,hi=nums.length-1; while(lo<=hi){int m=lo+(hi-lo)/2;if(nums[m]==target)return m;if(nums[lo]<=nums[m]){if(target>=nums[lo]&&target<nums[m])hi=m-1;else lo=m+1;}else{if(target>nums[m]&&target<=nums[hi])lo=m+1;else hi=m-1;}} return -1; } }`, cpp: `class Solution { public: int search(vector<int>& nums, int target) { int lo=0,hi=nums.size()-1; while(lo<=hi){int m=lo+(hi-lo)/2;if(nums[m]==target)return m;if(nums[lo]<=nums[m]){if(target>=nums[lo]&&target<nums[m])hi=m-1;else lo=m+1;}else{if(target>nums[m]&&target<=nums[hi])lo=m+1;else hi=m-1;}} return -1; } };` },
    197: { javascript: `function search(nums, target) { let lo=0,hi=nums.length-1; while(lo<=hi){const m=lo+((hi-lo)>>1);if(nums[m]===target)return true;if(nums[lo]===nums[m]&&nums[m]===nums[hi]){lo++;hi--;}else if(nums[lo]<=nums[m]){if(target>=nums[lo]&&target<nums[m])hi=m-1;else lo=m+1;}else{if(target>nums[m]&&target<=nums[hi])lo=m+1;else hi=m-1;}} return false; }`, java: `class Solution { public boolean search(int[] nums, int target) { int lo=0,hi=nums.length-1; while(lo<=hi){int m=lo+(hi-lo)/2;if(nums[m]==target)return true;if(nums[lo]==nums[m]&&nums[m]==nums[hi]){lo++;hi--;}else if(nums[lo]<=nums[m]){if(target>=nums[lo]&&target<nums[m])hi=m-1;else lo=m+1;}else{if(target>nums[m]&&target<=nums[hi])lo=m+1;else hi=m-1;}} return false; } }`, cpp: `class Solution { public: bool search(vector<int>& nums, int target) { int lo=0,hi=nums.size()-1; while(lo<=hi){int m=lo+(hi-lo)/2;if(nums[m]==target)return true;if(nums[lo]==nums[m]&&nums[m]==nums[hi]){lo++;hi--;}else if(nums[lo]<=nums[m]){if(target>=nums[lo]&&target<nums[m])hi=m-1;else lo=m+1;}else{if(target>nums[m]&&target<=nums[hi])lo=m+1;else hi=m-1;}} return false; } };` },
    220: { javascript: `function myPow(x, n) { if(n<0){x=1/x;n=-n;} let res=1; while(n>0){if(n%2===1)res*=x;x*=x;n=Math.floor(n/2);} return res; }`, java: `class Solution { public double myPow(double x, int n) { long N=n; if(N<0){x=1/x;N=-N;} double res=1; while(N>0){if(N%2==1)res*=x;x*=x;N/=2;} return res; } }`, cpp: `class Solution { public: double myPow(double x, int n) { long N=n; if(N<0){x=1/x;N=-N;} double res=1; while(N>0){if(N%2==1)res*=x;x*=x;N/=2;} return res; } };` },
};

async function run() {
    console.log('Adding multi-language solutions - Batch 3...\n');
    let updated = 0, failed = 0;
    for (const [id, langSolutions] of Object.entries(solutions)) {
        const { data: problem } = await supabaseAdmin.from('problems').select('solution_code').eq('id', parseInt(id)).single();
        if (!problem) { console.log(`  Problem #${id} not found`); continue; }
        const merged = { ...(problem.solution_code || {}), ...langSolutions };
        const { error } = await supabaseAdmin.from('problems').update({ solution_code: merged }).eq('id', parseInt(id));
        if (error) { console.error(`  ❌ #${id}: ${error.message}`); failed++; }
        else { updated++; }
    }
    console.log(`Done: ${updated} updated, ${failed} failed`);
}
run();
