// Batch 4: Tree, BFS/DFS, Graph, Heap problems (IDs 216-320)
import { supabaseAdmin } from '../db/supabaseClient.js';

const updates = [
    // ── Trees / BFS / DFS (216-260) ──
    { id: 216, description: 'Given the root of a binary tree, return its maximum depth. A binary tree maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.', constraints: '0 <= number of nodes <= 10^4\n-100 <= Node.val <= 100' },
    { id: 217, description: 'Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).', constraints: '1 <= number of nodes <= 1000\n-100 <= Node.val <= 100' },
    { id: 218, description: 'Given the root of a binary tree, invert the tree, and return its root. Inverting a binary tree means swapping the left and right children of every node.', constraints: '0 <= number of nodes <= 100\n-100 <= Node.val <= 100' },
    { id: 219, description: 'Given the roots of two binary trees p and q, write a function to check if they are the same or not. Two binary trees are considered the same if they are structurally identical, and the nodes have the same value.', constraints: '0 <= number of nodes <= 100\n-10^4 <= Node.val <= 10^4' },
    { id: 220, description: 'Given the root of a binary tree, determine if it is a valid binary search tree (BST). A valid BST has the property that for every node, all values in its left subtree are strictly less and all values in its right subtree are strictly greater.', constraints: '1 <= number of nodes <= 10^4\n-2^31 <= Node.val <= 2^31 - 1' },
    { id: 221, description: 'Given the root of a binary tree, return the level order traversal of its nodes values (i.e., from left to right, level by level).', constraints: '0 <= number of nodes <= 2000\n-1000 <= Node.val <= 1000' },
    { id: 223, description: 'Given the root of a binary tree and an integer targetSum, return true if the tree has a root-to-leaf path such that adding up all the values along the path equals targetSum.', constraints: '0 <= number of nodes <= 5000\n-1000 <= Node.val <= 1000\n-1000 <= targetSum <= 1000' },
    { id: 224, description: 'Given the root of a binary tree and an integer targetSum, return all root-to-leaf paths where the sum of the node values in the path equals targetSum. Each path should be returned as a list of the node values.', constraints: '0 <= number of nodes <= 5000\n-1000 <= Node.val <= 1000\n-1000 <= targetSum <= 1000' },
    { id: 225, description: 'Given a binary tree, find the lowest common ancestor (LCA) of two given nodes in the tree. The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself).', constraints: '2 <= number of nodes <= 10^5\n-10^9 <= Node.val <= 10^9\nAll Node.val are unique.\np != q\np and q will exist in the tree.' },
    { id: 226, description: 'Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.\n\nThe lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants.', constraints: '2 <= number of nodes <= 10^5\n-10^9 <= Node.val <= 10^9\nAll Node.val are unique.\np != q\np and q will exist in the BST.' },
    { id: 227, description: 'Serialization is the process of converting a data structure or object into a sequence of bits so that it can be stored or transmitted. Design an algorithm to serialize and deserialize a binary tree. There is no restriction on how your serialization/deserialization algorithm should work.', constraints: '0 <= number of nodes <= 10^4\n-1000 <= Node.val <= 1000' },
    { id: 228, description: 'Given the root of a binary tree, return the zigzag level order traversal of its nodes values (i.e., from left to right, then right to left for the next level and alternate between).', constraints: '0 <= number of nodes <= 2000\n-100 <= Node.val <= 100' },
    { id: 229, description: 'Given the root of a binary tree, return the bottom-up level order traversal of its nodes values (i.e., from left to right, level by level from leaf to root).', constraints: '0 <= number of nodes <= 2000\n-1000 <= Node.val <= 1000' },
    { id: 230, description: 'Given the root of a binary tree, return the right side view of it. The right side view is the set of nodes visible when the tree is viewed from the right side.', constraints: '0 <= number of nodes <= 100\n-100 <= Node.val <= 100' },
    { id: 231, description: 'Given the root of a binary tree, return the average value of the nodes on each level in the form of an array.', constraints: '1 <= number of nodes <= 10^4\n-2^31 <= Node.val <= 2^31 - 1' },
    { id: 232, description: 'Given a binary tree, find its minimum depth. The minimum depth is the number of nodes along the shortest path from the root node down to the nearest leaf node.\n\nNote: A leaf is a node with no children.', constraints: '0 <= number of nodes <= 10^5\n-1000 <= Node.val <= 1000' },
    { id: 233, description: 'Given a perfect binary tree where all leaves are on the same level, and every parent has two children, populate each next pointer to point to its next right node. If there is no next right node, the next pointer should be set to NULL.', constraints: '0 <= number of nodes <= 2^12 - 1\n-1000 <= Node.val <= 1000' },
    { id: 234, description: 'Given a binary tree, populate each next pointer to point to its next right node. If there is no next right node, the next pointer should be set to NULL. The initial next pointers are all set to NULL.', constraints: '0 <= number of nodes <= 6000\n-100 <= Node.val <= 100' },
    { id: 235, description: 'Given the root of a binary search tree and a node value, return the in-order successor of that node in the BST. If that node has no in-order successor, return null.', constraints: '1 <= number of nodes <= 10^4\n-10^5 <= Node.val <= 10^5\nAll Nodes will have unique values.' },
    { id: 236, description: 'Given the root of a binary tree, return the preorder traversal of its nodes values.', constraints: '0 <= number of nodes <= 100\n-100 <= Node.val <= 100' },
    { id: 237, description: 'Given the root of a binary tree, return the inorder traversal of its nodes values.', constraints: '0 <= number of nodes <= 100\n-100 <= Node.val <= 100' },
    { id: 238, description: 'Given the root of a binary tree, return the postorder traversal of its nodes values.', constraints: '0 <= number of nodes <= 100\n-100 <= Node.val <= 100' },
    { id: 239, description: 'Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.', constraints: '1 <= k <= number of nodes <= 10^4\n0 <= Node.val <= 10^4' },
    { id: 240, description: 'Given the root of a Binary Search Tree (BST), return the minimum absolute difference between the values of any two different nodes in the tree.', constraints: '2 <= number of nodes <= 10^4\n0 <= Node.val <= 10^5' },
    { id: 241, description: 'Given the root of a binary tree, imagine yourself standing on the right side of it, return the values of the nodes you can see ordered from top to bottom.', constraints: '0 <= number of nodes <= 100\n-100 <= Node.val <= 100' },
    { id: 242, description: 'You are given the root of a binary search tree (BST) and an integer val. Find the node in the BST that the node value equals val and return the subtree rooted with that node. If such a node does not exist, return null.', constraints: '1 <= number of nodes <= 5000\n1 <= Node.val <= 10^7\nroot is a valid binary search tree.\n1 <= val <= 10^7' },
    { id: 243, description: 'You are given the root node of a binary search tree (BST) and a value to insert into the tree. Return the root node of the BST after the insertion. It is guaranteed that the new value does not exist in the original BST.', constraints: '0 <= number of nodes <= 10^4\n-10^8 <= Node.val <= 10^8\nAll the values Node.val are unique.\n-10^8 <= val <= 10^8' },
    { id: 244, description: 'Given a root node reference of a BST and a key, delete the node with the given key in the BST. Return the root node reference (possibly updated) of the BST.\n\nThe deletion can be divided into two stages: Search for the node to remove, then if found, delete the node.', constraints: '0 <= number of nodes <= 10^4\n-10^5 <= Node.val <= 10^5\nEach node has a unique value.\nroot is a valid binary search tree.\n-10^5 <= key <= 10^5' },
    { id: 245, description: 'Given an integer array nums where the elements are sorted in ascending order, convert it to a height-balanced binary search tree.\n\nA height-balanced binary tree is a binary tree in which the depth of the two subtrees of every node never differs by more than one.', constraints: '1 <= nums.length <= 10^4\n-10^4 <= nums[i] <= 10^4\nnums is sorted in a strictly increasing order.' },
    { id: 246, description: 'Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.', constraints: '1 <= preorder.length <= 3000\ninorder.length == preorder.length\n-3000 <= preorder[i], inorder[i] <= 3000\npreorder and inorder consist of unique values.' },
    { id: 247, description: 'Given two integer arrays inorder and postorder where inorder is the inorder traversal of a binary tree and postorder is the postorder traversal of the same tree, construct and return the binary tree.', constraints: '1 <= inorder.length <= 3000\npostorder.length == inorder.length\n-3000 <= inorder[i], postorder[i] <= 3000\ninorder and postorder consist of unique values.' },
    { id: 248, description: 'Given the root of a binary tree, return the length of the diameter of the tree. The diameter of a binary tree is the length of the longest path between any two nodes in a tree. This path may or may not pass through the root.', constraints: '1 <= number of nodes <= 10^4\n-100 <= Node.val <= 100' },
    { id: 249, description: 'Given a binary tree, determine if it is height-balanced. A height-balanced binary tree is a binary tree in which the depth of the two subtrees of every node never differs by more than one.', constraints: '0 <= number of nodes <= 5000\n-10^4 <= Node.val <= 10^4' },
    { id: 250, description: 'Given the root of a binary tree, return the sum of values of its deepest leaves.', constraints: '1 <= number of nodes <= 10^4\n1 <= Node.val <= 100' },
    { id: 251, description: 'Given a binary tree where node values are digits from 1 to 9. A path in the binary tree is said to be pseudo-palindromic if at least one permutation of the node values in the path is a palindrome. Return the number of pseudo-palindromic paths going from the root node to leaf nodes.', constraints: '1 <= number of nodes <= 10^5\n1 <= Node.val <= 9' },
    { id: 252, description: 'Given the root of a binary tree, calculate the vertical order traversal of the binary tree. For each node at position (row, col), its left and right children will be at positions (row + 1, col - 1) and (row + 1, col + 1) respectively.', constraints: '1 <= number of nodes <= 1000\n0 <= Node.val <= 1000' },
    { id: 253, description: 'Given a binary tree, return the vertical order traversal of its nodes values. If two nodes are in the same row and column, the order should be from left to right.', constraints: '0 <= number of nodes <= 100\n-100 <= Node.val <= 100' },
    { id: 254, description: 'Given the root of a binary tree, return the length of the longest consecutive sequence path. A consecutive sequence path is a path where the values increase by one along the path. Note that the path can start at any node and go from parent to child.', constraints: '1 <= number of nodes <= 3 * 10^4\n-3 * 10^4 <= Node.val <= 3 * 10^4' },
    { id: 255, description: 'Given the root of a binary tree, return the sum of every tree node value whose value is even and whose grandparent value is also even. If there is no such node, return 0.', constraints: '1 <= number of nodes <= 10^4\n1 <= Node.val <= 100' },
    { id: 256, description: 'Given a binary tree, find the maximum path sum. A path is defined as any node sequence from some starting node to any node in the tree along the parent-child connections. The path must contain at least one node and does not need to go through the root.', constraints: '1 <= number of nodes <= 3 * 10^4\n-1000 <= Node.val <= 1000' },
    { id: 257, description: 'Given the root of a binary tree, return all root-to-leaf paths in any order. A leaf is a node with no children.', constraints: '1 <= number of nodes <= 100\n-100 <= Node.val <= 100' },
    { id: 258, description: 'Given a binary tree, count the number of uni-value subtrees. A uni-value subtree means all nodes of the subtree have the same value.', constraints: '0 <= number of nodes <= 1000\n-1000 <= Node.val <= 1000' },
    { id: 259, description: 'Given the root of a complete binary tree, return the number of the nodes in the tree. Design a solution that runs in less than O(n) time complexity.', constraints: '0 <= number of nodes <= 5 * 10^4\n0 <= Node.val <= 5 * 10^4' },
    { id: 260, description: 'Given a root of an N-ary tree, return a deep copy (clone) of the tree. Each node in the N-ary tree contains a val (int) and a list (List[Node]) of its children.', constraints: '0 <= number of nodes <= 10^4\n0 <= Node.val <= 10^4\nThe depth of the N-ary tree is less than or equal to 1000.' },

    // ── Graph (261-295) ──
    { id: 261, description: 'There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai. Return true if you can finish all courses. Otherwise, return false.', constraints: '1 <= numCourses <= 2000\n0 <= prerequisites.length <= 5000\nprerequisites[i].length == 2\n0 <= ai, bi < numCourses\nAll the pairs prerequisites[i] are unique.' },
    { id: 263, description: 'There are a total of numCourses courses you have to take. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai. Return the ordering of courses you should take to finish all courses. If there are many valid answers, return any of them. If it is impossible to finish all courses, return an empty array.', constraints: '1 <= numCourses <= 2000\n0 <= prerequisites.length <= numCourses * (numCourses - 1)\nprerequisites[i].length == 2\n0 <= ai, bi < numCourses\nai != bi\nAll the pairs [ai, bi] are distinct.' },
    { id: 264, description: 'Given an m x n 2D binary grid grid which represents a map of 1s (land) and 0s (water), return the number of islands.\n\nAn island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.', constraints: 'm == grid.length\nn == grid[i].length\n1 <= m, n <= 300\ngrid[i][j] is 0 or 1.' },
    { id: 265, description: 'Given an m x n matrix board containing X and O, capture all regions that are 4-directionally surrounded by X. A region is captured by flipping all Os into Xs in that surrounded region.', constraints: 'm == board.length\nn == board[i].length\n1 <= m, n <= 200\nboard[i][j] is X or O.' },
    { id: 266, description: 'There is a bi-directional graph with n vertices, where each vertex is labeled from 0 to n - 1. The edges in the graph are represented as a 2D integer array edges, where each edges[i] = [ui, vi] denotes a bi-directional edge between vertex ui and vertex vi.\n\nDetermine if there is a valid path that exists from source vertex to destination vertex.', constraints: '1 <= n <= 2 * 10^5\n0 <= edges.length <= 2 * 10^5\nedges[i].length == 2\n0 <= ui, vi <= n - 1\nui != vi\n0 <= source, destination <= n - 1' },
    { id: 267, description: 'You have a graph of n nodes. You are given an integer n and an array edges where edges[i] = [ai, bi] indicates that there is an edge between ai and bi in the graph. Return the number of connected components in the graph.', constraints: '1 <= n <= 2000\n1 <= edges.length <= 5000\nedges[i].length == 2\n0 <= ai <= bi < n\nai != bi\nThere are no repeated edges.' },
    { id: 268, description: 'In this problem, a tree is an undirected graph that is connected and has no cycles. You are given a graph that started as a tree with n nodes labeled from 1 to n, with one additional edge added. The added edge has two different vertices chosen from 1 to n, and was not an edge that already existed. Return an edge that can be removed so that the resulting graph is a tree of n nodes.', constraints: 'n == edges.length\n3 <= n <= 1000\nedges[i].length == 2\n1 <= ai < bi <= edges.length\nai != bi\nThere are no repeated edges.\nThe given graph is connected.' },
    { id: 269, description: 'Given a reference of a node in a connected undirected graph, return a deep copy (clone) of the graph. Each node in the graph contains a value (int) and a list (List[Node]) of its neighbors.', constraints: '1 <= number of nodes <= 100\n1 <= Node.val <= 100\nNode.val is unique for each node.\nThere are no repeated edges and no self-loops.\nThe Graph is connected and all nodes can be visited starting from the given node.' },
    { id: 270, description: 'You are given an m x n grid where each cell can have one of three values: 0 representing an empty cell, 1 representing a fresh orange, or 2 representing a rotten orange. Every minute, any fresh orange that is 4-directionally adjacent to a rotten orange becomes rotten. Return the minimum number of minutes that must elapse until no cell has a fresh orange. If this is impossible, return -1.', constraints: 'm == grid.length\nn == grid[i].length\n1 <= m, n <= 10\ngrid[i][j] is only 0, 1, or 2.' },
    { id: 271, description: 'There are n cities. Some of them are connected, while some are not. If city a is connected directly with city b, and city b is connected directly with city c, then city a is connected indirectly with city c. A province is a group of directly or indirectly connected cities and no other cities outside of the group. Return the total number of provinces.', constraints: '1 <= n <= 200\nn == isConnected.length\nn == isConnected[i].length\nisConnected[i][j] is 1 or 0.\nisConnected[i][i] == 1\nisConnected[i][j] == isConnected[j][i]' },
    { id: 272, description: 'You are given an n x n binary matrix grid where 1 represents land and 0 represents water. An island is a 4-directionally connected group of 1s not connected to any other 1s. There are exactly two islands in grid. Return the smallest number of 0s you must flip to connect the two islands.', constraints: 'n == grid.length == grid[i].length\n2 <= n <= 100\ngrid[i][j] is either 0 or 1.\nThere are exactly two islands in grid.' },
    { id: 273, description: 'You want to build some obstacle courses. You are given a 0-indexed integer array obstacles of length n, where obstacles[i] describes the height of the ith obstacle. For every index i between 0 and n - 1 (inclusive), find the length of the longest obstacle course in obstacles such that the last obstacle course is at index i, and all obstacles in the course are in non-decreasing order.', constraints: 'n == obstacles.length\n1 <= n <= 10^5\n1 <= obstacles[i] <= 10^7' },
    { id: 274, description: 'There is an m x n rectangular island that borders both the Pacific Ocean and Atlantic Ocean. The Pacific Ocean touches the islands left and top edges, and the Atlantic Ocean touches the islands right and bottom edges. Water can only flow in four directions (up, down, left, or right) from a cell to an adjacent cell with an equal or lower height. Find and return a list of coordinates of all cells where water can flow to both the Pacific and Atlantic oceans.', constraints: 'm == heights.length\nn == heights[r].length\n1 <= m, n <= 200\n0 <= heights[r][c] <= 10^5' },
    { id: 275, description: 'Given an m x n grid of characters board and a string word, return true if word exists in the grid. The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.', constraints: 'm == board.length\nn == board[i].length\n1 <= m, n <= 6\n1 <= word.length <= 15\nboard and word consists of only lowercase and uppercase English letters.' },
    { id: 276, description: 'Given a set of distinct positive integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target. The same number may be chosen from candidates an unlimited number of times. You may return the combinations in any order.', constraints: '1 <= candidates.length <= 30\n2 <= candidates[i] <= 40\nAll elements of candidates are distinct.\n1 <= target <= 40' },
    { id: 277, description: 'Given a collection of candidate numbers (candidates) and a target number (target), find all unique combinations in candidates where the candidate numbers sum to target. Each number in candidates may only be used once in the combination.', constraints: '1 <= candidates.length <= 100\n1 <= candidates[i] <= 50\n1 <= target <= 30' },
    { id: 278, description: 'Given an integer array nums of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets. Return the solution in any order.', constraints: '1 <= nums.length <= 10\n-10 <= nums[i] <= 10\nAll the numbers of nums are unique.' },
    { id: 279, description: 'Given an integer array nums that may contain duplicates, return all possible subsets (the power set). The solution set must not contain duplicate subsets. Return the solution in any order.', constraints: '1 <= nums.length <= 10\n-10 <= nums[i] <= 10' },
    { id: 280, description: 'Given a collection of numbers, nums, that might contain duplicates, return all possible unique permutations in any order.', constraints: '1 <= nums.length <= 8\n-10 <= nums[i] <= 10' },
    { id: 281, description: 'Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.', constraints: '1 <= n <= 8' },
    { id: 282, description: 'Given a string s, partition s such that every substring of the partition is a palindrome. Return all possible palindrome partitioning of s.', constraints: '1 <= s.length <= 16\ns contains only lowercase English letters.' },
    { id: 283, description: 'Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. A mapping of digits to letters (just like on the telephone buttons) is given. Note that 1 does not map to any letters.', constraints: '0 <= digits.length <= 4\ndigits[i] is a digit in the range [2, 9].' },
    { id: 284, description: 'The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other. Given an integer n, return all distinct solutions to the n-queens puzzle.', constraints: '1 <= n <= 9' },
    { id: 285, description: 'Write a program to solve a Sudoku puzzle by filling the empty cells. A sudoku solution must satisfy all of the following rules: Each of the digits 1-9 must occur exactly once in each row, each column, and each of the 9 3x3 sub-boxes of the grid. The . character indicates empty cells.', constraints: 'board.length == 9\nboard[i].length == 9\nboard[i][j] is a digit or .\nIt is guaranteed that the input board has only one solution.' },
    { id: 286, description: 'An m x n board of characters is given. Find all words on the board. Each word must be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once in a word.', constraints: 'm == board.length\nn == board[i].length\n1 <= m, n <= 12\nboard[i][j] is a lowercase English letter.\n1 <= words.length <= 3 * 10^4\n1 <= words[i].length <= 10\nwords[i] consists of lowercase English letters.\nAll the strings of words are unique.' },

    // ── Heap / Priority Queue (287-295) ──
    { id: 287, description: 'You are given an array of integers stones where stones[i] is the weight of the ith stone. On each turn, we choose the heaviest two stones and smash them together. If x == y, both stones are destroyed. If x != y, a stone of weight y - x remains. Return the weight of the last remaining stone. If there are no stones left, return 0.', constraints: '1 <= stones.length <= 30\n1 <= stones[i] <= 1000' },
    { id: 288, description: 'Given an integer array nums and an integer k, return the kth largest element in the array. Note that it is the kth largest element in the sorted order, not the kth distinct element.', constraints: '1 <= k <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4' },
    { id: 289, description: 'Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.', constraints: '1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4\nk is in the range [1, number of unique elements].\nThe answer is guaranteed to be unique.' },
    { id: 290, description: 'Given a characters array tasks, representing the tasks a CPU needs to do, where each letter represents a different task. Tasks could be done in any order. Each task is done in one unit of time. For each unit of time, the CPU could complete either one task or just be idle. However, there is a non-negative integer n that represents the cooldown period between two same tasks. Return the least number of units of times that the CPU will take to finish all the given tasks.', constraints: '1 <= tasks.length <= 10^4\ntasks[i] is an uppercase English letter.\nThe integer n is in the range [0, 100].' },
    { id: 291, description: 'Design a class to find the kth largest element in a stream. Note that it is the kth largest element in the sorted order, not the kth distinct element.\n\nImplement KthLargest class: KthLargest(int k, int[] nums) Initializes the object with the integer k and the stream of integers nums. int add(int val) Appends the integer val to the stream and returns the element representing the kth largest element in the stream.', constraints: '1 <= k <= 10^4\n0 <= nums.length <= 10^4\n-10^4 <= nums[i] <= 10^4\n-10^4 <= val <= 10^4\nAt most 10^4 calls will be made to add.' },
    { id: 292, description: 'You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.', constraints: 'k == lists.length\n0 <= k <= 10^4\n0 <= lists[i].length <= 500\n-10^4 <= lists[i][j] <= 10^4' },
    { id: 293, description: 'Given an n x n matrix where each of the rows and columns is sorted in ascending order, return the kth smallest element in the matrix. Note that it is the kth smallest element in the sorted order, not the kth distinct element.', constraints: 'n == matrix.length == matrix[i].length\n1 <= n <= 300\n-10^9 <= matrix[i][j] <= 10^9\nAll the rows and columns of matrix are guaranteed to be sorted in non-decreasing order.\n1 <= k <= n^2' },
    { id: 294, description: 'Design a simplified version of Twitter where users can post tweets, follow/unfollow another user, and is able to see the 10 most recent tweets in the user news feed.', constraints: '1 <= userId, followerId, followeeId <= 500\n0 <= tweetId <= 10^4\nAt most 3 * 10^4 calls will be made.' },
    { id: 295, description: 'Given an array of meeting time intervals where intervals[i] = [starti, endi], determine the minimum number of conference rooms required.', constraints: '1 <= intervals.length <= 10^4\n0 <= starti < endi <= 10^6' },

    // ── More Graph problems (296-320) ──
    { id: 296, description: 'You are given a network of n nodes, labeled from 1 to n. You are also given times, a list of travel times as directed edges times[i] = (ui, vi, wi), where ui is the source node, vi is the target node, and wi is the time it takes for a signal to travel from source to target. Send a signal from a given node k. Return the minimum time for all the n nodes to receive the signal. If it is impossible, return -1.', constraints: '1 <= k <= n <= 100\n1 <= times.length <= 6000\ntimes[i].length == 3\n1 <= ui, vi <= n\nui != vi\n0 <= wi <= 100\nAll the pairs (ui, vi) are unique.' },
    { id: 298, description: 'Given n nodes labeled from 0 to n-1 and a list of undirected edges, write a function to check whether these edges make up a valid tree. An undirected graph is a tree if it is connected and has no cycles.', constraints: '1 <= n <= 2000\n0 <= edges.length <= 5000\nedges[i].length == 2\n0 <= ai, bi < n\nai != bi\nThere are no self-loops or repeated edges.' },
    { id: 299, description: 'There is a new alien language that uses the English alphabet. However, the order of the letters is unknown to you. You are given a list of strings words from the alien language dictionary. Return a string of the unique letters in the new alien language sorted in lexicographically increasing order by the new language rules.', constraints: '1 <= words.length <= 100\n1 <= words[i].length <= 100\nwords[i] consists of only lowercase English letters.' },
    { id: 300, description: 'You are a professional robber planning to rob houses along a street arranged in a circle. That means the first house is the neighbor of the last one. Each house has a certain amount of money stashed. You cannot rob two adjacent houses. Given an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.', constraints: '1 <= nums.length <= 100\n0 <= nums[i] <= 1000' },
    { id: 301, description: 'You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money. Return the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1. You may assume that you have an infinite number of each kind of coin.', constraints: '1 <= coins.length <= 12\n1 <= coins[i] <= 2^31 - 1\n0 <= amount <= 10^4' },
    { id: 302, description: 'Given an integer n, return the number of structurally unique BSTs which has exactly n nodes of unique values from 1 to n.', constraints: '1 <= n <= 19' },
    { id: 303, description: 'Given an integer n, return all the structurally unique BSTs which has exactly n nodes of unique values from 1 to n. Return the answer in any order.', constraints: '1 <= n <= 8' },
    { id: 304, description: 'Given a string s, return the number of palindromic substrings in it. A string is a palindrome when it reads the same backward as forward. A substring is a contiguous sequence of characters within the string.', constraints: '1 <= s.length <= 1000\ns consists of lowercase English letters.' },
    { id: 305, description: 'Given a string s, return the longest palindromic substring in s.', constraints: '1 <= s.length <= 1000\ns consist of only digits and English letters.' },
    { id: 306, description: 'Given a string s, find the longest palindromic subsequence length in s. A subsequence is a sequence that can be derived from another sequence by deleting some or no elements without changing the order of the remaining elements.', constraints: '1 <= s.length <= 1000\ns consists only of lowercase English letters.' },
    { id: 307, description: 'Given a triangle array, return the minimum path sum from top to bottom. For each step, you may move to an adjacent number of the row below. More formally, if you are on index i on the current row, you may move to either index i or index i + 1 on the next row.', constraints: '1 <= triangle.length <= 200\ntriangle[0].length == 1\ntriangle[i].length == triangle[i - 1].length + 1\n-10^4 <= triangle[i][j] <= 10^4' },
    { id: 308, description: 'You are given an integer array prices where prices[i] is the price of a given stock on the ith day, and an integer k. Find the maximum profit you can achieve. You may complete at most k transactions. Note: You may not engage in multiple transactions simultaneously.', constraints: '1 <= k <= 100\n1 <= prices.length <= 1000\n0 <= prices[i] <= 1000' },
    { id: 309, description: 'You are given an integer array prices where prices[i] is the price of a given stock on the ith day. Find the maximum profit you can achieve. You may complete as many transactions as you like (i.e., buy one and sell one share of the stock multiple times) with the following restriction: After you sell your stock, you cannot buy stock on the next day (i.e., cooldown of one day). Note: You may not engage in multiple transactions simultaneously.', constraints: '1 <= prices.length <= 5000\n0 <= prices[i] <= 1000' },
    { id: 310, description: 'You are given an integer array prices where prices[i] is the price of a given stock on the ith day and an integer fee representing a transaction fee. Find the maximum profit you can achieve. You may complete as many transactions as you like, but you need to pay the transaction fee for each transaction. Note: You may not engage in multiple transactions simultaneously.', constraints: '1 <= prices.length <= 5 * 10^4\n1 <= prices[i] <= 5 * 10^4\n0 <= fee <= 5 * 10^4' },
    { id: 311, description: 'Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.\n\nA subsequence of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.', constraints: '1 <= text1.length, text2.length <= 1000\ntext1 and text2 consist of only lowercase English characters.' },
    { id: 312, description: 'Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word: Insert a character, Delete a character, Replace a character.', constraints: '0 <= word1.length, word2.length <= 500\nword1 and word2 consist of lowercase English letters.' },
    { id: 313, description: 'Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.\n\nNote that the same word in the dictionary may be reused multiple times in the segmentation.', constraints: '1 <= s.length <= 300\n1 <= wordDict.length <= 1000\n1 <= wordDict[i].length <= 20\ns and wordDict[i] consist of only lowercase English letters.\nAll the strings of wordDict are unique.' },
    { id: 314, description: 'Given a string s and a dictionary of strings wordDict, add spaces in s to construct a sentence where each word is a valid dictionary word. Return all such possible sentences in any order.\n\nNote that the same word in the dictionary may be reused multiple times in the segmentation.', constraints: '1 <= s.length <= 20\n1 <= wordDict.length <= 1000\n1 <= wordDict[i].length <= 10\ns and wordDict[i] consist of only lowercase English letters.\nAll the strings of wordDict are unique.\nInput is generated in a way that the length of the answer does not exceed 10^5.' },
    { id: 315, description: 'You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?', constraints: '1 <= n <= 45' },
    { id: 316, description: 'You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and it will automatically contact the police if two adjacent houses were broken into on the same night.\n\nGiven an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.', constraints: '1 <= nums.length <= 100\n0 <= nums[i] <= 400' },
    { id: 317, description: 'Given an integer array nums, return true if you can partition the array into two subsets such that the sum of the elements in both subsets is equal or false otherwise.', constraints: '1 <= nums.length <= 200\n1 <= nums[i] <= 100' },
    { id: 318, description: 'You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money. Return the number of combinations that make up that amount. If that amount cannot be made up, return 0.\n\nYou may assume that you have an infinite number of each kind of coin.', constraints: '1 <= coins.length <= 300\n1 <= coins[i] <= 5000\nAll the values of coins are unique.\n0 <= amount <= 5000' },
    { id: 319, description: 'You are given an integer array nums. You want to maximize the number of points you get by performing the following operation any number of times: Pick any nums[i] and delete it to earn nums[i] points. Afterwards, you must delete every element equal to nums[i] - 1 and every element equal to nums[i] + 1. Return the maximum number of points you can earn by applying the above operation some number of times.', constraints: '1 <= nums.length <= 2 * 10^4\n1 <= nums[i] <= 10^4' },
    { id: 320, description: 'Given a wooden stick of length n units. The stick is labelled from 0 to n. Given an integer array cuts where cuts[i] denotes a position you should perform a cut at. The cost of one cut is the length of the stick to be cut, the total cost is the sum of costs of all cuts. Return the minimum total cost of the cuts.', constraints: '2 <= n <= 10^6\n1 <= cuts.length <= min(n - 1, 100)\n1 <= cuts[i] <= n - 1\nAll the integers in cuts array are distinct.' },
];

async function run() {
    console.log('Batch 4: Updating ' + updates.length + ' problems...');
    let ok = 0, fail = 0;
    for (const u of updates) {
        const { error } = await supabaseAdmin.from('problems').update({
            description: u.description, constraints: u.constraints
        }).eq('id', u.id);
        if (error) { console.error('FAIL [' + u.id + ']: ' + error.message); fail++; }
        else { ok++; }
    }
    console.log('Batch 4 done: ' + ok + ' ok, ' + fail + ' fail');
}
run().catch(console.error);
