// Parameters
param location string
param tags object
param webAppName string
param logAnalyticsWorkspaceName string
param monitorWorkspaceName string
param grafanaName string
param appInsightsName string
param actionGroupEmail string = ''

// Existing App Service to attach diagnostics and metric alerts
resource webApp 'Microsoft.Web/sites@2024-04-01' existing = {
  name: webAppName
}

// Log Analytics for App Service diagnostics and centralized logs
resource logAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logAnalyticsWorkspaceName
  location: location
  tags: tags
  properties: {
    retentionInDays: 30
    features: {
      searchVersion: 1
      enableLogAccessUsingOnlyResourcePermissions: true
    }
    sku: {
      name: 'PerGB2018'
    }
  }
}

// Application Insights (workspace-based)
resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName
  location: location
  kind: 'web'
  tags: tags
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalyticsWorkspace.id
    IngestionMode: 'LogAnalytics'
    DisableIpMasking: false
  }
}

// Azure Monitor Workspace (foundation for managed Prometheus in AKS scenarios)
resource monitorWorkspace 'Microsoft.Monitor/accounts@2023-04-03' = {
  name: monitorWorkspaceName
  location: location
  tags: tags
  properties: {}
}

// Azure Managed Grafana
resource grafana 'Microsoft.Dashboard/grafana@2023-09-01' = {
  name: grafanaName
  location: location
  tags: tags
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    apiKey: 'Disabled'
    deterministicOutboundIP: 'Enabled'
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Enabled'
    grafanaMajorVersion: '11'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    grafanaIntegrations: {
      azureMonitorWorkspaceIntegrations: [
        {
          azureMonitorWorkspaceResourceId: monitorWorkspace.id
        }
      ]
    }
  }
}

// App Service diagnostic logs + platform metrics to Log Analytics
resource webAppDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'send-to-law'
  scope: webApp
  properties: {
    workspaceId: logAnalyticsWorkspace.id
    logs: [
      {
        category: 'AppServiceHTTPLogs'
        enabled: true
      }
      {
        category: 'AppServiceConsoleLogs'
        enabled: true
      }
      {
        category: 'AppServiceAppLogs'
        enabled: true
      }
      {
        category: 'AppServicePlatformLogs'
        enabled: true
      }
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
      }
    ]
  }
}

// Optional alerting channel via email
resource actionGroup 'Microsoft.Insights/actionGroups@2023-01-01' = if (!empty(actionGroupEmail)) {
  name: '${replace(grafanaName, '_', '-')}-ops-ag'
  location: 'global'
  tags: tags
  properties: {
    groupShortName: 'prepops'
    enabled: true
    emailReceivers: [
      {
        name: 'ops-email'
        emailAddress: actionGroupEmail
        useCommonAlertSchema: true
      }
    ]
  }
}

// Production guardrail alert for App Service 5xx responses
resource webApp5xxAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: '${replace(grafanaName, '_', '-')}-appservice-5xx'
  location: 'global'
  tags: tags
  properties: {
    description: 'App Service HTTP 5xx alert for preploop backend'
    severity: 2
    enabled: true
    scopes: [
      webApp.id
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT5M'
    criteria: {
      allOf: [
        {
          criterionType: 'StaticThresholdCriterion'
          name: 'http5xx-threshold'
          metricNamespace: 'Microsoft.Web/sites'
          metricName: 'Http5xx'
          operator: 'GreaterThan'
          timeAggregation: 'Total'
          threshold: 5
        }
      ]
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
    }
    autoMitigate: true
    targetResourceType: 'Microsoft.Web/sites'
    targetResourceRegion: location
    actions: !empty(actionGroupEmail) ? [
      {
        actionGroupId: actionGroup.id
      }
    ] : []
  }
}

// Outputs
output logAnalyticsWorkspaceId string = logAnalyticsWorkspace.id
output monitorWorkspaceId string = monitorWorkspace.id
output grafanaId string = grafana.id
output grafanaUrl string = grafana.properties.endpoint
output appInsightsConnectionString string = appInsights.properties.ConnectionString
