/// <reference path="./cloudflare-types.d.ts" />

// @ts-expect-error Resolved by Cloudflare Workers runtime and Wrangler.
import { EmailMessage } from "cloudflare:email";

export interface Env {
  SEND_EMAIL: {
    send: (message: EmailMessage) => Promise<void>;
  };
}

interface IncomingEmail {
  from: string;
  to: string;
  headers?: Headers;
  rawSize?: number;
  setReject?: (reason: string) => void;
  forward: (destination: string) => Promise<void>;
}

const DESTINATION_EMAIL = "preploop.me@gmail.com";
const MAX_EMAIL_SIZE_BYTES = 1024 * 1024 * 10;

function cleanHeaderValue(value: string): string {
  return value.replace(/[\r\n]+/g, " ").trim();
}

function isAutoGeneratedEmail(headers?: Headers): boolean {
  if (!headers) return false;
  const autoSubmitted = (headers.get("auto-submitted") || "").toLowerCase();
  const precedence = (headers.get("precedence") || "").toLowerCase();
  const xAutoResponseSuppress = (headers.get("x-auto-response-suppress") || "").toLowerCase();

  return (
    autoSubmitted.includes("auto") ||
    precedence.includes("bulk") ||
    precedence.includes("list") ||
    xAutoResponseSuppress.includes("all")
  );
}

export default {
  async email(message: IncomingEmail, env: Env, _ctx: ExecutionContext): Promise<void> {
    if (message.rawSize && message.rawSize > MAX_EMAIL_SIZE_BYTES) {
      message.setReject?.("Email too large to process");
      return;
    }

    if (isAutoGeneratedEmail(message.headers)) {
      message.setReject?.("Auto-generated email ignored");
      return;
    }

    if (message.from.toLowerCase() === DESTINATION_EMAIL.toLowerCase()) {
      // Prevent accidental forwarding/sending loops.
      message.setReject?.("Loop detected");
      return;
    }

    // Forward inbound mail to a destination inbox.
    await message.forward(DESTINATION_EMAIL);

    // Send a new summary email using a raw RFC 822 message body.
    const safeFrom = cleanHeaderValue(message.from);
    const safeTo = cleanHeaderValue(message.to);
    const rawMime = [
      `From: Preploop Worker <${safeTo}>`,
      `To: ${DESTINATION_EMAIL}`,
      "Subject: New email received",
      "MIME-Version: 1.0",
      'Content-Type: text/plain; charset="UTF-8"',
      "",
      `New email from ${safeFrom}`,
      "",
    ].join("\r\n");

    const outbound = new EmailMessage(safeTo, DESTINATION_EMAIL, rawMime);
    await env.SEND_EMAIL.send(outbound);
  },
};
